package ai.chat2db.plugin.mysql.completion.catalog;

import ai.chat2db.community.domain.api.model.completion.core.SqlCompletionCandidates;
import ai.chat2db.plugin.mysql.config.completion.MysqlSqlCompletionFunctionTokenConfig;
import ai.chat2db.community.domain.api.model.completion.SqlCompletionFunctionSpec;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;
import org.apache.commons.lang3.StringUtils;


public final class MysqlSqlCompletionFunctionCatalog {

    private static final List<SqlCompletionFunctionSpec> FUNCTIONS = List.of(
            metadata("ABS", "x:number", "number"),
            metadata("ACOS", "x:number", "number"),
            metadata("ADDDATE", "date:date, INTERVAL expr unit", "date"),
            metadata("ADDTIME", "expr1:time, expr2:time", "time"),
            metadata("AES_DECRYPT", "crypt_str:binary, key_str:string", "binary"),
            metadata("AES_ENCRYPT", "str:string, key_str:string", "binary"),
            metadata("AREA", "g:geometry", "number"),
            metadata("ASIN", "x:number", "number"),
            metadata("ASBINARY", "g:geometry", "binary"),
            metadata("ASTEXT", "g:geometry", "string"),
            metadata("ATAN", "x:number[, y:number]", "number"),
            metadata("ATAN2", "y:number, x:number", "number"),
            metadata("ASWKB", "g:geometry", "binary"),
            metadata("ASWKT", "g:geometry", "string"),
            metadata("ASYMMETRIC_DECRYPT", "algorithm:string, crypt_str:string, key_str:string", "string"),
            metadata("ASYMMETRIC_DERIVE", "pub_key:string, priv_key:string", "string"),
            metadata("ASYMMETRIC_ENCRYPT", "algorithm:string, str:string, key_str:string", "string"),
            metadata("ASYMMETRIC_SIGN", "algorithm:string, digest:string, priv_key:string", "string"),
            metadata("ASYMMETRIC_VERIFY", "algorithm:string, digest:string, sig:string, pub_key:string", "int"),
            metadata("AVG", "[DISTINCT] expr:number", "number"),
            metadata("BENCHMARK", "count:int, expr:any", "int"),
            metadata("BIN", "n:bigint", "string"),
            metadata("BIT_AND", "[ALL] expr:int", "int"),
            metadata("BIT_COUNT", "n:bigint", "int"),
            metadata("BIT_LENGTH", "str:string", "int"),
            metadata("BIT_OR", "[ALL] expr:int", "int"),
            metadata("BIT_XOR", "[ALL] expr:int", "int"),
            metadata("BUFFER", "g:geometry, distance:number", "geometry"),
            metadata("CAST", "expr:any AS type:data_type", "any"),
            metadata("CEIL", "x:number", "number"),
            metadata("CEILING", "x:number", "number"),
            metadata("CENTROID", "g:geometry", "point"),
            metadata("CHAR", "n:int* [USING charset_name]", "string"),
            metadata("CHAR_LENGTH", "str:string", "int"),
            metadata("CHARACTER_LENGTH", "str:string", "int"),
            metadata("CHARSET", "str:string", "string"),
            metadata("COERCIBILITY", "str:string", "int"),
            metadata("COALESCE", "expr:any*", "any"),
            metadata("COLLATION", "str:string", "string"),
            metadata("COMPRESS", "str:string", "binary"),
            metadata("CONCAT", "str:string*", "string"),
            metadata("CONCAT_WS", "separator:string, str:string*", "string"),
            metadata("CONNECTION_ID", "", "bigint"),
            metadata("CONV", "n:string, from_base:int, to_base:int", "string"),
            metadata("CONVERT", "expr:any, type:data_type", "any"),
            metadata("CONVERT_TZ", "dt:datetime, from_tz:string, to_tz:string", "datetime"),
            metadata("COS", "x:number", "number"),
            metadata("COT", "x:number", "number"),
            metadata("COUNT", "[{DISTINCT | ALL}] expr:any*", "int"),
            metadata("CREATE_ASYMMETRIC_PRIV_KEY", "algorithm:string, key_len:int", "string"),
            metadata("CREATE_ASYMMETRIC_PUB_KEY", "algorithm:string, priv_key:string", "string"),
            metadata("CREATE_DH_PARAMETERS", "key_len:int", "string"),
            metadata("CREATE_DIGEST", "digest_type:string, str:string", "string"),
            metadata("CRC32", "expr:string", "int"),
            metadata("CROSSES", "g1:geometry, g2:geometry", "int"),
            metadata("CUME_DIST", "", "number"),
            metadata("CURDATE", "", "date"),
            metadata("CURRENT_DATE", "", "date"),
            metadata("CURRENT_TIME", "[fsp:int]", "time"),
            metadata("CURRENT_TIMESTAMP", "[fsp:int]", "datetime"),
            metadata("CURRENT_USER", "", "string"),
            metadata("CURTIME", "[fsp:int]", "time"),
            metadata("DATABASE", "", "string"),
            metadata("DATE", "expr:datetime", "date"),
            metadata("DATEDIFF", "expr1:date, expr2:date", "int"),
            metadata("DATE_ADD", "date:datetime, INTERVAL expr unit", "datetime"),
            metadata("DATE_FORMAT", "date:date, format:string", "string"),
            metadata("DATE_SUB", "date:datetime, INTERVAL expr unit", "datetime"),
            metadata("DAY", "date:date", "int"),
            metadata("DAYNAME", "date:date", "string"),
            metadata("DAYOFMONTH", "date:date", "int"),
            metadata("DAYOFWEEK", "date:date", "int"),
            metadata("DAYOFYEAR", "date:date", "int"),
            metadata("DECODE", "crypt_str:string, pass_str:string", "string"),
            metadata("DEGREES", "x:number", "number"),
            metadata("DENSE_RANK", "", "int"),
            metadata("DES_DECRYPT", "crypt_str:string[, key_str:string]", "string"),
            metadata("DES_ENCRYPT", "str:string[, key_num:int]", "string"),
            metadata("DIMENSION", "g:geometry", "int"),
            metadata("DISJOINT", "g1:geometry, g2:geometry", "int"),
            metadata("DISTANCE", "g1:geometry, g2:geometry", "number"),
            metadata("ELT", "n:int, str:string*", "string"),
            metadata("ENCODE", "str:string, pass_str:string", "string"),
            metadata("ENCRYPT", "str:string[, salt:string]", "string"),
            metadata("ENDPOINT", "ls:linestring", "point"),
            metadata("ENVELOPE", "g:geometry", "geometry"),
            metadata("EQUALS", "g1:geometry, g2:geometry", "int"),
            metadata("EXP", "x:number", "number"),
            metadata("EXPORT_SET", "bits:int, on:string, off:string[, separator:string[, number_of_bits:int]]", "string"),
            metadata("EXTERIORRING", "poly:polygon", "linestring"),
            metadata("EXTRACT", "unit:interval_unit FROM expr:datetime", "int"),
            metadata("EXTRACTVALUE", "xml_frag:string, xpath_expr:string", "string"),
            metadata("FIELD", "str:any, str:any*", "int"),
            metadata("FIND_IN_SET", "str:string, strlist:string", "int"),
            metadata("FIRST_VALUE", "expr:any", "any"),
            metadata("FLOOR", "x:number", "number"),
            metadata("FORMAT", "x:number, d:int[, locale:string]", "string"),
            metadata("FOUND_ROWS", "", "bigint"),
            metadata("FROM_BASE64", "str:string", "binary"),
            metadata("FROM_DAYS", "n:int", "date"),
            metadata("FROM_UNIXTIME", "unix_timestamp:int[, format:string]", "datetime"),
            metadata("GEOMCOLLFROMTEXT", "wkt:string[, srid:int]", "geometrycollection"),
            metadata("GEOMCOLLFROMWKB", "wkb:binary[, srid:int]", "geometrycollection"),
            metadata("GEOMETRYCOLLECTION", "g:geometry*", "geometrycollection"),
            metadata("GEOMETRYCOLLECTIONFROMTEXT", "wkt:string[, srid:int]", "geometrycollection"),
            metadata("GEOMETRYCOLLECTIONFROMWKB", "wkb:binary[, srid:int]", "geometrycollection"),
            metadata("GEOMETRYFROMTEXT", "wkt:string[, srid:int]", "geometry"),
            metadata("GEOMETRYFROMWKB", "wkb:binary[, srid:int]", "geometry"),
            metadata("GEOMETRYN", "gc:geometrycollection, n:int", "geometry"),
            metadata("GEOMETRYTYPE", "g:geometry", "string"),
            metadata("GEOMFROMTEXT", "wkt:string[, srid:int]", "geometry"),
            metadata("GEOMFROMWKB", "wkb:binary[, srid:int]", "geometry"),
            metadata("GET_FORMAT", "type:date_time_type, format:string", "string"),
            metadata("GET_LOCK", "str:string, timeout:number", "int"),
            metadata("GLENGTH", "ls:linestring", "number"),
            metadata("GREATEST", "expr:any*", "any"),
            metadata("GROUP_CONCAT",
                    "[DISTINCT] expr:any* [ORDER BY ...] [SEPARATOR str]", "string"),
            metadata("GTID_SUBSET", "set1:string, set2:string", "int"),
            metadata("GTID_SUBTRACT", "set1:string, set2:string", "string"),
            metadata("HEX", "str_or_number:any", "string"),
            metadata("HOUR", "time:time", "int"),
            metadata("IF", "expr:boolean, if_true:any, if_false:any", "any"),
            metadata("IFNULL", "expr1:any, expr2:any", "any"),
            metadata("INET_ATON", "expr:string", "int"),
            metadata("INET_NTOA", "expr:int", "string"),
            metadata("INET6_ATON", "expr:string", "binary"),
            metadata("INET6_NTOA", "expr:binary", "string"),
            metadata("INSTR", "str:string, substr:string", "int"),
            metadata("INSERT", "str:string, pos:int, len:int, newstr:string", "string"),
            metadata("INTERIORRINGN", "poly:polygon, n:int", "linestring"),
            metadata("INTERSECTS", "g1:geometry, g2:geometry", "int"),
            metadata("ISCLOSED", "ls:linestring", "int"),
            metadata("ISEMPTY", "g:geometry", "int"),
            metadata("ISNULL", "expr:any", "int"),
            metadata("ISSIMPLE", "g:geometry", "int"),
            metadata("IS_FREE_LOCK", "str:string", "int"),
            metadata("IS_IPV4", "str:string", "int"),
            metadata("IS_IPV4_COMPAT", "expr:binary", "int"),
            metadata("IS_IPV4_MAPPED", "expr:binary", "int"),
            metadata("IS_IPV6", "str:string", "int"),
            metadata("IS_USED_LOCK", "str:string", "bigint"),
            metadata("JSON_ARRAY", "value:any*", "json"),
            metadata("JSON_ARRAY_APPEND", "json_doc:json, path:string, value:any*", "json"),
            metadata("JSON_ARRAY_INSERT", "json_doc:json, path:string, value:any*", "json"),
            metadata("JSON_ARRAYAGG", "expr:any", "json"),
            metadata("JSON_CONTAINS", "target:json, candidate:json[, path:string]", "int"),
            metadata("JSON_CONTAINS_PATH", "json_doc:json, one_or_all:string, path:string*", "int"),
            metadata("JSON_DEPTH", "json_doc:json", "int"),
            metadata("JSON_EXTRACT", "json_doc:json, path:string*", "json"),
            metadata("JSON_INSERT", "json_doc:json, path:string, value:any*", "json"),
            metadata("JSON_KEYS", "json_doc:json[, path:string]", "json"),
            metadata("JSON_LENGTH", "json_doc:json[, path:string]", "int"),
            metadata("JSON_MERGE", "json_doc:json*", "json"),
            metadata("JSON_MERGE_PATCH", "json_doc:json*", "json"),
            metadata("JSON_MERGE_PRESERVE", "json_doc:json*", "json"),
            metadata("JSON_OBJECT", "key:string, value:any*", "json"),
            metadata("JSON_OBJECTAGG", "key:any, value:any", "json"),
            metadata("JSON_OVERLAPS", "json_doc1:json, json_doc2:json", "int"),
            metadata("JSON_PRETTY", "json_doc:json", "string"),
            metadata("JSON_QUOTE", "str:string", "json"),
            metadata("JSON_REMOVE", "json_doc:json, path:string*", "json"),
            metadata("JSON_REPLACE", "json_doc:json, path:string, value:any*", "json"),
            metadata("JSON_SCHEMA_VALID", "schema:json, json_doc:json", "int"),
            metadata("JSON_SCHEMA_VALIDATION_REPORT", "schema:json, json_doc:json", "json"),
            metadata("JSON_SEARCH", "json_doc:json, one_or_all:string, search_str:string[, escape_char:string[, path:string*]]",
                    "json"),
            metadata("JSON_SET", "json_doc:json, path:string, value:any*", "json"),
            metadata("JSON_STORAGE_FREE", "json_doc:json", "int"),
            metadata("JSON_STORAGE_SIZE", "json_doc:json", "int"),
            metadata("JSON_TABLE", "expr:json, path:string COLUMNS columns:column_list", "table"),
            metadata("JSON_TYPE", "json_val:json", "string"),
            metadata("JSON_UNQUOTE", "json_val:json", "string"),
            metadata("JSON_VALID", "val:any", "int"),
            metadata("JSON_VALUE", "json_doc:json, path:string", "string"),
            metadata("LAG", "expr:any[, offset:int[, default:any]]", "any"),
            metadata("LAST_DAY", "date:date", "date"),
            metadata("LAST_INSERT_ID", "[expr:any]", "bigint"),
            metadata("LAST_VALUE", "expr:any", "any"),
            metadata("LCASE", "str:string", "string"),
            metadata("LEAD", "expr:any[, offset:int[, default:any]]", "any"),
            metadata("LEAST", "expr:any*", "any"),
            metadata("LEFT", "str:string, len:int", "string"),
            metadata("LENGTH", "str:string", "int"),
            metadata("LINEFROMTEXT", "wkt:string[, srid:int]", "linestring"),
            metadata("LINEFROMWKB", "wkb:binary[, srid:int]", "linestring"),
            metadata("LINESTRING", "point:point*", "linestring"),
            metadata("LINESTRINGFROMTEXT", "wkt:string[, srid:int]", "linestring"),
            metadata("LINESTRINGFROMWKB", "wkb:binary[, srid:int]", "linestring"),
            metadata("LN", "x:number", "number"),
            metadata("LOAD_FILE", "file_name:string", "string"),
            metadata("LOCATE", "substr:string, str:string[, pos:int]", "int"),
            metadata("LOG", "x:number[, base:number]", "number"),
            metadata("LOG10", "x:number", "number"),
            metadata("LOG2", "x:number", "number"),
            metadata("LOCALTIME", "[fsp:int]", "datetime"),
            metadata("LOCALTIMESTAMP", "[fsp:int]", "datetime"),
            metadata("LOWER", "str:string", "string"),
            metadata("LPAD", "str:string, len:int, padstr:string", "string"),
            metadata("LTRIM", "str:string", "string"),
            metadata("MAKEDATE", "year:int, dayofyear:int", "date"),
            metadata("MAKETIME", "hour:int, minute:int, second:int", "time"),
            metadata("MAKE_SET", "bits:int, str:string*", "string"),
            metadata("MASTER_POS_WAIT", "log_name:string, log_pos:int[, timeout:int]", "int"),
            metadata("MAX", "expr:any", "any"),
            metadata("MBRCONTAINS", "g1:geometry, g2:geometry", "int"),
            metadata("MBRDISJOINT", "g1:geometry, g2:geometry", "int"),
            metadata("MBREQUAL", "g1:geometry, g2:geometry", "int"),
            metadata("MBRINTERSECTS", "g1:geometry, g2:geometry", "int"),
            metadata("MBROVERLAPS", "g1:geometry, g2:geometry", "int"),
            metadata("MBRTOUCHES", "g1:geometry, g2:geometry", "int"),
            metadata("MBRWITHIN", "g1:geometry, g2:geometry", "int"),
            metadata("MD5", "str:string", "string"),
            metadata("MICROSECOND", "expr:time", "int"),
            metadata("MID", "str:string, pos:int[, len:int]", "string"),
            metadata("MIN", "expr:any", "any"),
            metadata("MINUTE", "time:time", "int"),
            metadata("MLINEFROMTEXT", "wkt:string[, srid:int]", "multilinestring"),
            metadata("MLINEFROMWKB", "wkb:binary[, srid:int]", "multilinestring"),
            metadata("MOD", "n:int, m:int", "int"),
            metadata("MONTH", "date:date", "int"),
            metadata("MONTHNAME", "date:date", "string"),
            metadata("MPOINTFROMTEXT", "wkt:string[, srid:int]", "multipoint"),
            metadata("MPOINTFROMWKB", "wkb:binary[, srid:int]", "multipoint"),
            metadata("MPOLYFROMTEXT", "wkt:string[, srid:int]", "multipolygon"),
            metadata("MPOLYFROMWKB", "wkb:binary[, srid:int]", "multipolygon"),
            metadata("MULTILINESTRING", "linestring:linestring*", "multilinestring"),
            metadata("MULTILINESTRINGFROMTEXT", "wkt:string[, srid:int]", "multilinestring"),
            metadata("MULTILINESTRINGFROMWKB", "wkb:binary[, srid:int]", "multilinestring"),
            metadata("MULTIPOINT", "point:point*", "multipoint"),
            metadata("MULTIPOINTFROMTEXT", "wkt:string[, srid:int]", "multipoint"),
            metadata("MULTIPOINTFROMWKB", "wkb:binary[, srid:int]", "multipoint"),
            metadata("MULTIPOLYGON", "polygon:polygon*", "multipolygon"),
            metadata("MULTIPOLYGONFROMTEXT", "wkt:string[, srid:int]", "multipolygon"),
            metadata("MULTIPOLYGONFROMWKB", "wkb:binary[, srid:int]", "multipolygon"),
            metadata("NAME_CONST", "name:string, value:any", "any"),
            metadata("NOW", "[fsp:int]", "datetime"),
            metadata("NTH_VALUE", "expr:any, n:int", "any"),
            metadata("NTILE", "buckets:int", "int"),
            metadata("NULLIF", "expr1:any, expr2:any", "any"),
            metadata("NUMGEOMETRIES", "gc:geometrycollection", "int"),
            metadata("NUMINTERIORRINGS", "poly:polygon", "int"),
            metadata("NUMPOINTS", "ls:linestring", "int"),
            metadata("OCT", "n:bigint", "string"),
            metadata("OCTET_LENGTH", "str:string", "int"),
            metadata("OLD_PASSWORD", "str:string", "string"),
            metadata("ORD", "str:string", "int"),
            metadata("OVERLAPS", "g1:geometry, g2:geometry", "int"),
            metadata("PASSWORD", "str:string", "string"),
            metadata("PERCENT_RANK", "", "number"),
            metadata("PERIOD_ADD", "period:int, months:int", "int"),
            metadata("PERIOD_DIFF", "period1:int, period2:int", "int"),
            metadata("PI", "", "number"),
            metadata("POINT", "x:number, y:number", "point"),
            metadata("POINTFROMTEXT", "wkt:string[, srid:int]", "point"),
            metadata("POINTFROMWKB", "wkb:binary[, srid:int]", "point"),
            metadata("POINTN", "ls:linestring, n:int", "point"),
            metadata("POLYFROMTEXT", "wkt:string[, srid:int]", "polygon"),
            metadata("POLYFROMWKB", "wkb:binary[, srid:int]", "polygon"),
            metadata("POLYGON", "linestring:linestring*", "polygon"),
            metadata("POLYGONFROMTEXT", "wkt:string[, srid:int]", "polygon"),
            metadata("POLYGONFROMWKB", "wkb:binary[, srid:int]", "polygon"),
            metadata("POSITION", "substr:string IN str:string", "int"),
            metadata("POW", "x:number, y:number", "number"),
            metadata("POWER", "x:number, y:number", "number"),
            metadata("QUARTER", "date:date", "int"),
            metadata("QUOTE", "str:string", "string"),
            metadata("RADIANS", "x:number", "number"),
            metadata("RAND", "[n:int]", "number"),
            metadata("RANDOM", "", "number"),
            metadata("RANDOM_BYTES", "len:int", "binary"),
            metadata("RANK", "", "int"),
            metadata("RELEASE_LOCK", "str:string", "int"),
            metadata("REGEXP_INSTR", "expr:string, pat:string[, pos:int[, occurrence:int[, return_option:int[, match_type:string]]]]", "int"),
            metadata("REGEXP_LIKE", "expr:string, pat:string[, match_type:string]", "int"),
            metadata("REGEXP_REPLACE", "expr:string, pat:string, repl:string[, pos:int[, occurrence:int[, match_type:string]]]", "string"),
            metadata("REGEXP_SUBSTR", "expr:string, pat:string[, pos:int[, occurrence:int[, match_type:string]]]", "string"),
            metadata("REPEAT", "str:string, count:int", "string"),
            metadata("REPLACE", "str:string, from_str:string, to_str:string", "string"),
            metadata("REVERSE", "str:string", "string"),
            metadata("RIGHT", "str:string, len:int", "string"),
            metadata("ROUND", "x:number[, d:int]", "number"),
            metadata("ROW_COUNT", "", "int"),
            metadata("ROW_NUMBER", "", "int"),
            metadata("RPAD", "str:string, len:int, padstr:string", "string"),
            metadata("RTRIM", "str:string", "string"),
            metadata("SCHEMA", "", "string"),
            metadata("SEC_TO_TIME", "seconds:int", "time"),
            metadata("SECOND", "time:time", "int"),
            metadata("SESSION_USER", "", "string"),
            metadata("SHA", "str:string", "string"),
            metadata("SHA1", "str:string", "string"),
            metadata("SHA2", "str:string, hash_length:int", "string"),
            metadata("SIGN", "x:number", "int"),
            metadata("SIN", "x:number", "number"),
            metadata("SLEEP", "duration:number", "int"),
            metadata("SOUNDEX", "str:string", "string"),
            metadata("SQL_THREAD_WAIT_AFTER_GTIDS", "gtid_set:string[, timeout:int]", "int"),
            metadata("SQRT", "x:number", "number"),
            metadata("SRID", "g:geometry", "int"),
            metadata("STARTPOINT", "ls:linestring", "point"),
            metadata("STATEMENT_DIGEST", "statement:string", "binary"),
            metadata("STATEMENT_DIGEST_TEXT", "statement:string", "string"),
            metadata("STD", "[ALL] expr:number", "number"),
            metadata("STDDEV", "[ALL] expr:number", "number"),
            metadata("STDDEV_POP", "[ALL] expr:number", "number"),
            metadata("STDDEV_SAMP", "[ALL] expr:number", "number"),
            metadata("STRCMP", "expr1:string, expr2:string", "int"),
            metadata("STR_TO_DATE", "str:string, format:string", "date"),
            metadata("ST_AREA", "g:geometry", "number"),
            metadata("ST_ASBINARY", "g:geometry", "binary"),
            metadata("ST_ASTEXT", "g:geometry", "string"),
            metadata("ST_ASWKB", "g:geometry", "binary"),
            metadata("ST_ASWKT", "g:geometry", "string"),
            metadata("ST_BUFFER", "g:geometry, distance:number", "geometry"),
            metadata("ST_CENTROID", "g:geometry", "point"),
            metadata("ST_CONTAINS", "g1:geometry, g2:geometry", "int"),
            metadata("ST_CROSSES", "g1:geometry, g2:geometry", "int"),
            metadata("ST_DIFFERENCE", "g1:geometry, g2:geometry", "geometry"),
            metadata("ST_DIMENSION", "g:geometry", "int"),
            metadata("ST_DISJOINT", "g1:geometry, g2:geometry", "int"),
            metadata("ST_DISTANCE", "g1:geometry, g2:geometry", "number"),
            metadata("ST_ENDPOINT", "ls:linestring", "point"),
            metadata("ST_ENVELOPE", "g:geometry", "geometry"),
            metadata("ST_EQUALS", "g1:geometry, g2:geometry", "int"),
            metadata("ST_EXTERIORRING", "poly:polygon", "linestring"),
            metadata("ST_GEOMCOLLFROMTEXT", "wkt:string[, srid:int]", "geometrycollection"),
            metadata("ST_GEOMCOLLFROMTXT", "wkt:string[, srid:int]", "geometrycollection"),
            metadata("ST_GEOMCOLLFROMWKB", "wkb:binary[, srid:int]", "geometrycollection"),
            metadata("ST_GEOMETRYCOLLECTIONFROMTEXT", "wkt:string[, srid:int]", "geometrycollection"),
            metadata("ST_GEOMETRYCOLLECTIONFROMWKB", "wkb:binary[, srid:int]", "geometrycollection"),
            metadata("ST_GEOMETRYFROMTEXT", "wkt:string[, srid:int]", "geometry"),
            metadata("ST_GEOMETRYFROMWKB", "wkb:binary[, srid:int]", "geometry"),
            metadata("ST_GEOMETRYN", "gc:geometrycollection, n:int", "geometry"),
            metadata("ST_GEOMETRYTYPE", "g:geometry", "string"),
            metadata("ST_GEOMFROMTEXT", "wkt:string[, srid:int]", "geometry"),
            metadata("ST_GEOMFROMWKB", "wkb:binary[, srid:int]", "geometry"),
            metadata("ST_INTERIORRINGN", "poly:polygon, n:int", "linestring"),
            metadata("ST_INTERSECTION", "g1:geometry, g2:geometry", "geometry"),
            metadata("ST_INTERSECTS", "g1:geometry, g2:geometry", "int"),
            metadata("ST_ISCLOSED", "ls:linestring", "int"),
            metadata("ST_ISEMPTY", "g:geometry", "int"),
            metadata("ST_ISSIMPLE", "g:geometry", "int"),
            metadata("ST_LINEFROMTEXT", "wkt:string[, srid:int]", "linestring"),
            metadata("ST_LINEFROMWKB", "wkb:binary[, srid:int]", "linestring"),
            metadata("ST_LINESTRINGFROMTEXT", "wkt:string[, srid:int]", "linestring"),
            metadata("ST_LINESTRINGFROMWKB", "wkb:binary[, srid:int]", "linestring"),
            metadata("ST_NUMGEOMETRIES", "gc:geometrycollection", "int"),
            metadata("ST_NUMINTERIORRING", "poly:polygon", "int"),
            metadata("ST_NUMINTERIORRINGS", "poly:polygon", "int"),
            metadata("ST_NUMPOINTS", "ls:linestring", "int"),
            metadata("ST_OVERLAPS", "g1:geometry, g2:geometry", "int"),
            metadata("ST_POINTFROMTEXT", "wkt:string[, srid:int]", "point"),
            metadata("ST_POINTFROMWKB", "wkb:binary[, srid:int]", "point"),
            metadata("ST_POINTN", "ls:linestring, n:int", "point"),
            metadata("ST_POLYFROMTEXT", "wkt:string[, srid:int]", "polygon"),
            metadata("ST_POLYFROMWKB", "wkb:binary[, srid:int]", "polygon"),
            metadata("ST_POLYGONFROMTEXT", "wkt:string[, srid:int]", "polygon"),
            metadata("ST_POLYGONFROMWKB", "wkb:binary[, srid:int]", "polygon"),
            metadata("ST_SRID", "g:geometry", "int"),
            metadata("ST_STARTPOINT", "ls:linestring", "point"),
            metadata("ST_SYMDIFFERENCE", "g1:geometry, g2:geometry", "geometry"),
            metadata("ST_TOUCHES", "g1:geometry, g2:geometry", "int"),
            metadata("ST_UNION", "g1:geometry, g2:geometry", "geometry"),
            metadata("ST_WITHIN", "g1:geometry, g2:geometry", "int"),
            metadata("ST_X", "point:point", "number"),
            metadata("ST_Y", "point:point", "number"),
            metadata("STRING_TO_VECTOR", "str:string", "vector"),
            metadata("SUBDATE", "date:datetime, INTERVAL expr unit", "datetime"),
            metadata("SUBSTR", "str:string, pos:int[, len:int]", "string"),
            metadata("SUBSTRING", "str:string, pos:int[, len:int]", "string"),
            metadata("SUBSTRING_INDEX", "str:string, delim:string, count:int", "string"),
            metadata("SUBTIME", "expr1:time, expr2:time", "time"),
            metadata("SUM", "[DISTINCT] expr:number", "number"),
            metadata("SYSDATE", "[fsp:int]", "datetime"),
            metadata("SYSTEM_USER", "", "string"),
            metadata("TAN", "x:number", "number"),
            metadata("TIME", "expr:datetime", "time"),
            metadata("TIMEDIFF", "expr1:time, expr2:time", "time"),
            metadata("TIMESTAMP", "expr1:datetime[, expr2:time]", "datetime"),
            metadata("TIMESTAMPADD", "unit:interval_unit, interval:int, datetime_expr:datetime", "datetime"),
            metadata("TIMESTAMPDIFF", "unit:interval_unit, datetime_expr1:datetime, datetime_expr2:datetime", "int"),
            metadata("TIME_FORMAT", "time:time, format:string", "string"),
            metadata("TIME_TO_SEC", "time:time", "int"),
            metadata("TOUCHES", "g1:geometry, g2:geometry", "int"),
            metadata("TO_BASE64", "str:string", "string"),
            metadata("TO_DAYS", "date:date", "int"),
            metadata("TO_SECONDS", "expr:datetime", "int"),
            metadata("TRIM", "[{BOTH | LEADING | TRAILING} [remstr:string] FROM] str:string", "string"),
            metadata("UCASE", "str:string", "string"),
            metadata("UNCOMPRESS", "str:binary", "binary"),
            metadata("UNCOMPRESSED_LENGTH", "str:binary", "int"),
            metadata("UNHEX", "str:string", "binary"),
            metadata("UNIX_TIMESTAMP", "[date:datetime]", "int"),
            metadata("UPDATEXML", "xml_target:string, xpath_expr:string, new_xml:string", "string"),
            metadata("UPPER", "str:string", "string"),
            metadata("UTC_DATE", "", "date"),
            metadata("UTC_TIME", "[fsp:int]", "time"),
            metadata("UTC_TIMESTAMP", "[fsp:int]", "datetime"),
            metadata("UUID", "", "string"),
            metadata("UUID_SHORT", "", "ulong"),
            metadata("VALIDATE_PASSWORD_STRENGTH", "str:string", "int"),
            metadata("VALUES", "column:column", "any"),
            metadata("VAR_POP", "[ALL] expr:number", "number"),
            metadata("VAR_SAMP", "[ALL] expr:number", "number"),
            metadata("VARIANCE", "[ALL] expr:number", "number"),
            metadata("VECTOR_DIM", "vector:vector", "int"),
            metadata("VECTOR_TO_STRING", "vector:vector", "string"),
            metadata("VERSION", "", "string"),
            metadata("WAIT_UNTIL_SQL_THREAD_AFTER_GTIDS", "gtid_set:string[, timeout:int]", "int"),
            metadata("WEEK", "date:date[, mode:int]", "int"),
            metadata("WEEKDAY", "date:date", "int"),
            metadata("WEEKOFYEAR", "date:date", "int"),
            metadata("WEIGHT_STRING", "str:string", "binary"),
            metadata("WITHIN", "g1:geometry, g2:geometry", "int"),
            metadata("X", "point:point", "number"),
            metadata("Y", "point:point", "number"),
            metadata("YEAR", "date:date", "int"),
            metadata("YEARWEEK", "date:date[, mode:int]", "int")
    );

    private static final Map<String, SqlCompletionFunctionSpec> SPEC_BY_NAME = specByName();

    private MysqlSqlCompletionFunctionCatalog() {
    }

    public static List<SqlCompletionFunctionSpec> functions(String prefix) {
        return FUNCTIONS.stream()
                .filter(spec -> matchesPrefix(spec.name(), prefix))
                .sorted(Comparator.comparing(SqlCompletionFunctionSpec::name, String.CASE_INSENSITIVE_ORDER))
                .toList();
    }

    public static SqlCompletionFunctionSpec function(Integer tokenType,
                                                     List<Integer> ruleList,
                                                     SqlCompletionCandidates c3Result) {
        if (!MysqlSqlCompletionFunctionTokenConfig.isFunctionToken(tokenType, ruleList, c3Result)) {
            return null;
        }
        String name = MysqlSqlCompletionFunctionTokenConfig.tokenName(tokenType);
        return StringUtils.isBlank(name) ? null : SPEC_BY_NAME.get(name);
    }

    private static boolean matchesPrefix(String label, String prefix) {
        return StringUtils.startsWithIgnoreCase(label, prefix);
    }

    private static Map<String, SqlCompletionFunctionSpec> specByName() {
        return FUNCTIONS.stream()
                .collect(Collectors.toUnmodifiableMap(SqlCompletionFunctionSpec::name,
                        Function.identity()));
    }

    private static SqlCompletionFunctionSpec metadata(String name, String parameters, String returnType) {
        return new SqlCompletionFunctionSpec(name, parameters, returnType);
    }
}
