import { DatabaseTypeCode } from '@/constants/common';
import { IFunction, IKeyword } from '.';

/** Mathematical functions. */
const Math_Functions: IFunction[] = [
  {
    name: 'ABS',
    description: '返回数值的绝对值。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT ABS(-10) AS absolute_value;',
  },
  {
    name: 'ACOS',
    description: '返回数值的反余弦（以弧度表示）。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT ACOS(0.5) AS arccosine;',
  },
  {
    name: 'ASIN',
    description: '返回数值的反正弦（以弧度表示）。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT ASIN(0.5) AS arcsine;',
  },
  {
    name: 'ATAN',
    description: '返回数值的反正切（以弧度表示）。',
    parameters: [
      { name: 'X', type: 'DECIMAL' },
      { name: 'Y', type: 'DECIMAL' },
    ],
    returnType: 'DECIMAL',
    example: 'SELECT ATAN(1) AS arctangent;',
  },
  {
    name: 'ATAN2',
    description: '返回两个参数的反正切（以弧度表示）。',
    parameters: [
      { name: 'y', type: 'DECIMAL' },
      { name: 'x', type: 'DECIMAL' },
    ],
    returnType: 'DECIMAL',
    example: 'SELECT ATAN2(1, 1) AS atan2_value;',
  },
  {
    name: 'CEIL',
    description: '返回不小于参数的最小整数值。',
    parameters: [{ name: 'number', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT CEIL(2.3) AS ceil_value;',
  },
  {
    name: 'CEILING',
    description: '返回不小于参数的最小整数值（与 CEIL() 相同）。',
    parameters: [{ name: 'number', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT CEILING(2.3) AS ceiling_value;',
  },
  {
    name: 'CONV',
    description: '在不同数字基数之间转换数字。',
    parameters: [
      { name: 'N', type: 'INT' },
      { name: 'from_base', type: 'INT' },
      { name: 'to_base', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT CONV('A', 16, 10) AS decimal_value;",
  },
  {
    name: 'COS',
    description: '返回数值的余弦。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT COS(PI()) AS cosine;',
  },
  {
    name: 'COT',
    description: '返回数值的余切。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT COT(1) AS cotangent;',
  },
  {
    name: 'CRC32',
    description: '计算循环冗余校验值。',
    parameters: [{ name: 'expr', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT CRC32('hello') AS crc_value;",
  },
  {
    name: 'DEGREES',
    description: '将弧度转换为度。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT DEGREES(PI()) AS degrees_value;',
  },
  {
    name: 'EXP',
    description: '返回 e 的指定次幂。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT EXP(1) AS exponential;',
  },
  {
    name: 'FLOOR',
    description: '返回不大于参数的最大整数值。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT FLOOR(2.7) AS floor_value;',
  },
  {
    name: 'LN',
    description: '返回参数的自然对数。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT LN(2.718281828459) AS natural_log;',
  },
  {
    name: 'LOG',
    description: '返回第一个参数的自然对数。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT LOG(2.718281828459) AS log_value;',
  },
  {
    name: 'LOG10',
    description: '返回参数的以 10 为底的对数。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT LOG10(100) AS log10_value;',
  },
  {
    name: 'LOG2',
    description: '返回参数的以 2 为底的对数。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT LOG2(8) AS log2_value;',
  },
  {
    name: 'MOD',
    description: '返回两个参数相除的余数。',
    parameters: [
      { name: 'N', type: 'INT' },
      { name: 'M', type: 'INT' },
    ],
    returnType: 'INT',
    example: 'SELECT MOD(10, 3) AS remainder;',
  },
  {
    name: 'PI',
    description: '返回 π（pi）的值。',
    parameters: [],
    returnType: 'DECIMAL',
    example: 'SELECT PI() AS pi_value;',
  },
  {
    name: 'POW',
    description: '返回第一个参数的第二个参数次幂。',
    parameters: [
      { name: 'X', type: 'DECIMAL' },
      { name: 'Y', type: 'DECIMAL' },
    ],
    returnType: 'DECIMAL',
    example: 'SELECT POW(2, 3) AS power_value;',
  },
  {
    name: 'POWER',
    description: '返回第一个参数的第二个参数次幂（与 POW() 相同）。',
    parameters: [
      { name: 'X', type: 'DECIMAL' },
      { name: 'Y', type: 'DECIMAL' },
    ],
    returnType: 'DECIMAL',
    example: 'SELECT POWER(2, 3) AS power_value;',
  },
  {
    name: 'RADIANS',
    description: '将角度值转换为弧度。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT RADIANS(180) AS radians_value;',
  },
  {
    name: 'RAND',
    description: '返回随机浮点值。',
    parameters: [{ name: 'N', type: 'INT', optional: true }],
    returnType: 'DECIMAL',
    example: 'SELECT RAND() AS random_value;',
  },
  {
    name: 'ROUND',
    description: '返回数值四舍五入到指定小数位数的结果。',
    parameters: [
      { name: 'X', type: 'DECIMAL' },
      { name: 'D', type: 'INT', optional: true },
    ],
    returnType: 'INT',
    example: 'SELECT ROUND(3.14159, 2) AS rounded_value;',
  },
  {
    name: 'SIGN',
    description: '返回参数的符号（-1, 0, 1）。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'INT',
    example: 'SELECT SIGN(-5) AS sign_value;',
  },
  {
    name: 'SIN',
    description: '返回参数的正弦。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT SIN(PI()/2) AS sine_value;',
  },
  {
    name: 'SQRT',
    description: '返回参数的平方根。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT SQRT(9) AS square_root;',
  },
  {
    name: 'TAN',
    description: '返回参数的正切。',
    parameters: [{ name: 'X', type: 'DECIMAL' }],
    returnType: 'DECIMAL',
    example: 'SELECT TAN(PI()/4) AS tangent_value;',
  },
  {
    name: 'TRUNCATE',
    description: '将数值截断到指定的小数位数。',
    parameters: [
      { name: 'X', type: 'DECIMAL' },
      { name: 'D', type: 'INT' },
    ],
    returnType: 'DECIMAL',
    example: 'SELECT TRUNCATE(3.14159, 2) AS truncated_value;',
  },
];
/** Date and time functions. */
const Date_Functions: IFunction[] = [
  {
    name: 'ADDDATE',
    description: '将时间值（间隔）添加到日期值。',
    parameters: [
      { name: 'date', type: 'DATE' },
      { name: 'interval', type: 'INT' },
    ],
    returnType: 'DATE',
    example: "SELECT ADDDATE('2024-08-05', INTERVAL 5 DAY) AS new_date;",
  },
  {
    name: 'ADDTIME',
    description: '添加时间间隔。',
    parameters: [
      { name: 'time', type: 'TIME' },
      { name: 'interval', type: 'TIME' },
    ],
    returnType: 'TIME',
    example: "SELECT ADDTIME('10:00:00', '02:30:00') AS new_time;",
  },
  {
    name: 'CONVERT_TZ',
    description: '从一个时区转换为另一个时区。',
    parameters: [
      { name: 'datetime', type: 'DATETIME' },
      { name: 'from_tz', type: 'VARCHAR' },
      { name: 'to_tz', type: 'VARCHAR' },
    ],
    returnType: 'DATETIME',
    example: "SELECT CONVERT_TZ('2024-08-05 12:00:00', 'UTC', 'Asia/Shanghai') AS shanghai_time;",
  },
  {
    name: 'CURDATE',
    description: '返回当前日期。',
    parameters: [],
    returnType: 'DATE',
    example: 'SELECT CURDATE() AS current_date;',
  },
  {
    name: 'CURRENT_DATE',
    description: 'CURDATE() 的同义词。',
    parameters: [],
    returnType: 'DATE',
    example: 'SELECT CURRENT_DATE() AS current_date;',
  },
  {
    name: 'CURRENT_TIME',
    description: 'CURTIME() 的同义词。',
    parameters: [],
    returnType: 'TIME',
    example: 'SELECT CURRENT_TIME() AS current_time;',
  },
  {
    name: 'CURRENT_TIMESTAMP',
    description: 'NOW() 的同义词。',
    parameters: [],
    returnType: 'DATETIME',
    example: 'SELECT CURRENT_TIMESTAMP() AS current_timestamp;',
  },
  {
    name: 'CURTIME',
    description: '返回当前时间。',
    parameters: [],
    returnType: 'TIME',
    example: 'SELECT CURTIME() AS current_time;',
  },
  {
    name: 'DATE',
    description: '提取日期或日期时间表达式的日期部分。',
    parameters: [{ name: 'datetime', type: 'DATETIME' }],
    returnType: 'DATE',
    example: "SELECT DATE('2024-08-05 12:34:56') AS date_part;",
  },
  {
    name: 'DATE_ADD',
    description: '将时间值（间隔）添加到日期值。',
    parameters: [
      { name: 'date', type: 'DATE' },
      { name: 'interval', type: 'INT' },
    ],
    returnType: 'DATE',
    example: "SELECT DATE_ADD('2024-08-05', INTERVAL 1 MONTH) AS new_date;",
  },
  {
    name: 'DATE_FORMAT',
    description: '按指定格式格式化日期。',
    parameters: [
      { name: 'date', type: 'DATE' },
      { name: 'format', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT DATE_FORMAT('2024-08-05', '%W, %M %d, %Y') AS formatted_date;",
  },
  {
    name: 'DATE_SUB',
    description: '从日期中减去时间值（间隔）。',
    parameters: [
      { name: 'date', type: 'DATE' },
      { name: 'interval', type: 'INT' },
    ],
    returnType: 'DATE',
    example: "SELECT DATE_SUB('2024-08-05', INTERVAL 5 DAY) AS new_date;",
  },
  {
    name: 'DATEDIFF',
    description: '返回两个日期之间的天数差。',
    parameters: [
      { name: 'date1', type: 'DATE' },
      { name: 'date2', type: 'DATE' },
    ],
    returnType: 'INT',
    example: "SELECT DATEDIFF('2024-08-05', '2024-08-01') AS days_diff;",
  },
  {
    name: 'DAY',
    description: 'DAYOFMONTH() 的同义词，返回月份中的日期（1-31）。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'INT',
    example: "SELECT DAY('2024-08-05') AS day_of_month;",
  },
  {
    name: 'DAYNAME',
    description: '返回星期几的名称。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'VARCHAR',
    example: "SELECT DAYNAME('2024-08-05') AS day_name;",
  },
  {
    name: 'DAYOFMONTH',
    description: '返回月份中的日期（1-31）。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'INT',
    example: "SELECT DAYOFMONTH('2024-08-05') AS day_of_month;",
  },
  {
    name: 'DAYOFWEEK',
    description: '返回参数的星期几索引（1=Sunday, 2=Monday, ..., 7=Saturday）。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'INT',
    example: "SELECT DAYOFWEEK('2024-08-05') AS weekday_index;",
  },
  {
    name: 'DAYOFYEAR',
    description: '返回一年中的某一天（1-366）。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'INT',
    example: "SELECT DAYOFYEAR('2024-08-05') AS day_of_year;",
  },
  {
    name: 'EXTRACT',
    description: '提取日期或时间的一部分。',
    parameters: [
      { name: 'unit', type: 'VARCHAR' },
      { name: 'datetime', type: 'DATETIME' },
    ],
    returnType: 'INT',
    example: "SELECT EXTRACT(YEAR FROM '2024-08-05') AS year_part;",
  },
  {
    name: 'FROM_DAYS',
    description: '将天数转换为日期。',
    parameters: [{ name: 'days', type: 'INT' }],
    returnType: 'DATE',
    example: 'SELECT FROM_DAYS(738000) AS date_value;',
  },
  {
    name: 'FROM_UNIXTIME',
    description: '将 Unix 时间戳格式化为日期。',
    parameters: [{ name: 'timestamp', type: 'INT' }],
    returnType: 'DATETIME',
    example: 'SELECT FROM_UNIXTIME(1628208000) AS formatted_date;',
  },
  {
    name: 'GET_FORMAT',
    description: '返回日期格式字符串，用于指定日期和时间格式。',
    parameters: [
      { name: 'type', type: 'VARCHAR' },
      { name: 'format', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT GET_FORMAT(DATE, 'USA') AS usa_format;",
  },
  {
    name: 'HOUR',
    description: '提取小时部分。',
    parameters: [{ name: 'time', type: 'TIME' }],
    returnType: 'INT',
    example: "SELECT HOUR('12:34:56') AS hour_value;",
  },
  {
    name: 'LAST_DAY',
    description: '返回参数所在月份的最后一天。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'DATE',
    example: "SELECT LAST_DAY('2024-08-05') AS last_day_of_month;",
  },
  {
    name: 'LOCALTIME',
    description: 'NOW() 的同义词。',
    parameters: [],
    returnType: 'DATETIME',
    example: 'SELECT LOCALTIME() AS local_time;',
  },
  {
    name: 'LOCALTIMESTAMP',
    description: 'NOW() 的同义词。',
    parameters: [],
    returnType: 'DATETIME',
    example: 'SELECT LOCALTIMESTAMP() AS local_timestamp;',
  },
  {
    name: 'MAKEDATE',
    description: '根据年份和一年中的某一天创建日期。',
    parameters: [
      { name: 'year', type: 'INT' },
      { name: 'day_of_year', type: 'INT' },
    ],
    returnType: 'DATE',
    example: 'SELECT MAKEDATE(2024, 32) AS date_value;',
  },
  {
    name: 'MAKETIME',
    description: '根据时、分、秒创建时间。',
    parameters: [
      { name: 'hour', type: 'INT' },
      { name: 'minute', type: 'INT' },
      { name: 'second', type: 'INT' },
    ],
    returnType: 'TIME',
    example: 'SELECT MAKETIME(12, 34, 56) AS time_value;',
  },
  {
    name: 'MICROSECOND',
    description: '返回参数中的微秒数。',
    parameters: [{ name: 'time', type: 'TIME' }],
    returnType: 'INT',
    example: "SELECT MICROSECOND('10:10:10.123456') AS microseconds;",
  },
  {
    name: 'MINUTE',
    description: '从参数中返回分钟部分。',
    parameters: [{ name: 'time', type: 'TIME' }],
    returnType: 'INT',
    example: "SELECT MINUTE('12:34:56') AS minute_value;",
  },
  {
    name: 'MONTH',
    description: '返回指定日期中的月份。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'INT',
    example: "SELECT MONTH('2024-08-05') AS month_value;",
  },
  {
    name: 'MONTHNAME',
    description: '返回月份名称。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'VARCHAR',
    example: "SELECT MONTHNAME('2024-08-05') AS month_name;",
  },
  {
    name: 'NOW',
    description: '返回当前日期和时间。',
    parameters: [],
    returnType: 'DATETIME',
    example: 'SELECT NOW() AS current_datetime;',
  },
  {
    name: 'PERIOD_ADD',
    description: '为年月添加间隔（月份）。',
    parameters: [
      { name: 'period', type: 'INT' },
      { name: 'months', type: 'INT' },
    ],
    returnType: 'INT',
    example: 'SELECT PERIOD_ADD(202408, 2) AS new_period;',
  },
  {
    name: 'PERIOD_DIFF',
    description: '返回两个期间之间的月份数。',
    parameters: [
      { name: 'period1', type: 'INT' },
      { name: 'period2', type: 'INT' },
    ],
    returnType: 'INT',
    example: 'SELECT PERIOD_DIFF(202408, 202307) AS month_diff;',
  },
  {
    name: 'QUARTER',
    description: '从日期参数返回季度。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'INT',
    example: "SELECT QUARTER('2024-08-05') AS quarter_value;",
  },
  {
    name: 'SEC_TO_TIME',
    description: '将秒转换为"hh:mm:ss"格式。',
    parameters: [{ name: 'seconds', type: 'INT' }],
    returnType: 'TIME',
    example: 'SELECT SEC_TO_TIME(3661) AS time_format;',
  },
  {
    name: 'SECOND',
    description: '返回秒数（0-59）。',
    parameters: [{ name: 'time', type: 'TIME' }],
    returnType: 'INT',
    example: "SELECT SECOND('12:34:56') AS second_value;",
  },
  {
    name: 'STR_TO_DATE',
    description: '将字符串转换为日期。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'format', type: 'VARCHAR' },
    ],
    returnType: 'DATE',
    example: "SELECT STR_TO_DATE('31-12-2024', '%d-%m-%Y') AS date_value;",
  },
  {
    name: 'SUBDATE',
    description: '使用三个参数调用时与 DATE_SUB() 相同。',
    parameters: [
      { name: 'date', type: 'DATE' },
      { name: 'interval', type: 'INTERVAL' },
    ],
    returnType: 'DATE',
    example: "SELECT SUBDATE('2024-08-05', INTERVAL 5 DAY) AS new_date;",
  },
  {
    name: 'SUBTIME',
    description: '从时间中减去时间。',
    parameters: [
      { name: 'time1', type: 'TIME' },
      { name: 'time2', type: 'TIME' },
    ],
    returnType: 'TIME',
    example: "SELECT SUBTIME('12:34:56', '01:00:00') AS new_time;",
  },
  {
    name: 'SYSDATE',
    description: '返回函数执行的时间。',
    parameters: [],
    returnType: 'DATETIME',
    example: 'SELECT SYSDATE() AS system_date_time;',
  },
  {
    name: 'TIME',
    description: '提取传递的表达式的时间部分。',
    parameters: [{ name: 'expression', type: 'DATETIME | TIME' }],
    example: "SELECT TIME('12:34:56') AS time_part;",
    returnType: 'TIME',
  },
  {
    name: 'TIME_FORMAT',
    description: '按指定格式格式化时间。',
    parameters: [
      { name: 'time', type: 'TIME' },
      { name: 'format', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT TIME_FORMAT('12:34:56', '%H:%i') AS formatted_time;",
  },
  {
    name: 'TIME_TO_SEC',
    description: '返回转换为秒数的参数。',
    parameters: [{ name: 'time', type: 'TIME' }],
    returnType: 'INT',
    example: "SELECT TIME_TO_SEC('12:34:56') AS seconds_value;",
  },
  {
    name: 'TIMEDIFF',
    description: '返回两个时间之间的差值。',
    parameters: [
      { name: 'time1', type: 'TIME' },
      { name: 'time2', type: 'TIME' },
    ],
    returnType: 'TIME',
    example: "SELECT TIMEDIFF('12:34:56', '11:30:00') AS time_difference;",
  },
  {
    name: 'TIMESTAMP',
    description: '使用单个参数时返回日期或日期时间表达式；使用两个参数时返回参数的总和。',
    parameters: [
      { name: 'datetime1', type: 'DATETIME' },
      { name: 'datetime2', type: 'DATETIME', optional: true },
    ],
    returnType: 'DATETIME',
    example: "SELECT TIMESTAMP('2024-08-05', '12:34:56') AS combined_timestamp;",
  },
  {
    name: 'TIMESTAMPADD',
    description: '向日期时间表达式添加间隔。',
    parameters: [
      { name: 'unit', type: 'VARCHAR' },
      { name: 'interval', type: 'INT' },
      { name: 'datetime', type: 'DATETIME' },
    ],
    example: "SELECT TIMESTAMPADD(MINUTE, 30, '2024-08-05 10:00:00') AS new_time;",
    returnType: 'DATETIME',
  },
  {
    name: 'TIMESTAMPDIFF',
    description: '返回两个日期时间表达式之间的差值，以指定的单位表示。',
    parameters: [
      { name: 'unit', type: 'VARCHAR' },
      { name: 'datetime1', type: 'DATETIME' },
      { name: 'datetime2', type: 'DATETIME' },
    ],
    returnType: 'INT',
    example: "SELECT TIMESTAMPDIFF(DAY, '2024-08-01', '2024-08-05') AS days_diff;",
  },
  {
    name: 'TO_DAYS',
    description: '返回转换为天数的日期参数。',
    parameters: [{ name: 'date', type: 'DATE' }],
    returnType: 'INT',
    example: "SELECT TO_DAYS('2024-08-05') AS days_value;",
  },
  {
    name: 'TO_SECONDS',
    description: '返回日期或日期时间参数转换为自第 0 年起的秒数。',
    parameters: [{ name: 'datetime', type: 'DATETIME' }],
    returnType: 'INT',
    example: "SELECT TO_SECONDS('2024-08-05 12:34:56') AS seconds_value;",
  },
  {
    name: 'UNIX_TIMESTAMP',
    description: '返回 Unix 时间戳。',
    parameters: [{ name: 'datetime', type: 'DATETIME' }],
    example: "SELECT UNIX_TIMESTAMP('2024-08-05 12:34:56') AS unix_time;",
    returnType: 'INT',
  },
  {
    name: 'UTC_DATE',
    description: '返回当前 UTC 日期。',
    parameters: [],
    example: 'SELECT UTC_DATE() AS utc_date;',
    returnType: 'DATE',
  },
  {
    name: 'UTC_TIME',
    description: '返回当前 UTC 时间。',
    parameters: [],
    example: 'SELECT UTC_TIME() AS utc_time;',
    returnType: 'TIME',
  },
  {
    name: 'UTC_TIMESTAMP',
    description: '返回当前 UTC 日期和时间。',
    parameters: [],
    example: 'SELECT UTC_TIMESTAMP() AS utc_timestamp;',
    returnType: 'DATETIME',
  },
  {
    name: 'WEEK',
    description: '返回日期的周数。',
    parameters: [{ name: 'date', type: 'DATE' }],
    example: "SELECT WEEK('2024-08-05') AS week_number;",
    returnType: 'INT',
  },
  {
    name: 'WEEKDAY',
    description: '返回星期几索引（0=Monday, 1=Tuesday, ..., 6=Sunday）。',
    parameters: [{ name: 'date', type: 'DATE' }],
    example: "SELECT WEEKDAY('2024-08-05') AS weekday_index;",
    returnType: 'INT',
  },
  {
    name: 'WEEKOFYEAR',
    description: '返回日期的日历周数（1-53）。',
    parameters: [{ name: 'date', type: 'DATE' }],
    example: "SELECT WEEKOFYEAR('2024-08-05') AS week_of_year;",
    returnType: 'INT',
  },
  {
    name: 'YEAR',
    description: '返回年份。',
    parameters: [{ name: 'date', type: 'DATE' }],
    example: "SELECT YEAR('2024-08-05') AS year_value;",
    returnType: 'INT',
  },
  {
    name: 'YEARWEEK',
    description: '返回年份和周数。',
    parameters: [{ name: 'date', type: 'DATE' }],
    example: "SELECT YEARWEEK('2024-08-05') AS year_week;",
    returnType: 'INT',
  },
];

/** Conversion functions. */
const Conversion_Functions: IFunction[] = [
  {
    name: 'CAST',
    description: '将值转换为特定的数据类型。',
    parameters: [
      { name: 'value', type: 'ANY' },
      { name: 'as_type', type: 'DATA_TYPE' },
    ],
    returnType: 'ANY',
    example: "SELECT CAST('123' AS UNSIGNED) AS cast_value;",
  },
  {
    name: 'CONVERT',
    description: '将值转换为特定的数据类型，功能与 CAST() 类似。',
    parameters: [
      { name: 'value', type: 'ANY' },
      { name: 'as_type', type: 'DATA_TYPE' },
    ],
    returnType: 'ANY',
    example: "SELECT CONVERT('2024-08-05', DATE) AS converted_date;",
  },
];

/** XML functions. */
const XML_Functions: IFunction[] = [
  {
    name: 'ExtractValue',
    description:
      '使用 XPath 表示法从 XML 字符串中提取值。`ExtractValue()` 函数允许从 XML 文档中提取特定的内容节点或属性值。',
    parameters: [
      { name: 'xml_fragment', type: 'VARCHAR' },
      { name: 'xpath_expression', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT ExtractValue('<person><name>John Doe</name></person>', '/person/name') AS name;",
  },
  {
    name: 'UpdateXML',
    description:
      '用于在给定的 XML 字符串中更新指定节点或属性的值，并返回替换后的 XML 片段。`UpdateXML()` 函数使用 XPath 表达式来定位 XML 结构中的节点。',
    parameters: [
      { name: 'xml_fragment', type: 'VARCHAR' },
      { name: 'xpath_expression', type: 'VARCHAR' },
      { name: 'new_value', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT UpdateXML('<person><name>John Doe</name></person>', '/person/name', 'Jane Smith') AS updated_xml;",
  },
];

/** Encryption functions. */
const Encryption_Functions: IFunction[] = [
  {
    name: 'AES_DECRYPT',
    description: '使用高级加密标准（AES）算法解密数据。返回值为 BLOB 类型。',
    parameters: [
      { name: 'encrypted_data', type: 'BLOB' },
      { name: 'key', type: 'VARCHAR' },
    ],
    returnType: 'BLOB',
    example: "SELECT AES_DECRYPT(@encrypted, 'encryption_key') AS decrypted_data;",
  },
  {
    name: 'AES_ENCRYPT',
    description: '使用高级加密标准（AES）算法加密数据。返回值为 BLOB 类型。',
    parameters: [
      { name: 'data', type: 'VARCHAR' },
      { name: 'key', type: 'VARCHAR' },
    ],
    returnType: 'BLOB',
    example: "SELECT AES_ENCRYPT('MySecretData', 'encryption_key') AS encrypted_data;",
  },
  {
    name: 'COMPRESS',
    description: '使用 zlib 算法压缩字符串并以二进制字符串形式返回结果。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'BLOB',
    example: "SELECT COMPRESS('This is a test string') AS compressed_data;",
  },
  {
    name: 'MD5',
    description: '计算字符串的 MD5 哈希值，返回一个 32 字符的十六进制字符串。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT MD5('hello') AS md5_hash;",
  },
  {
    name: 'RANDOM_BYTES',
    description: '返回一个指定长度的随机字节向量。用于生成随机数据。',
    parameters: [{ name: 'length', type: 'INT' }],
    returnType: 'BLOB',
    example: 'SELECT RANDOM_BYTES(16) AS random_bytes;',
  },
  {
    name: 'SHA1',
    description: '计算字符串的 SHA-1 哈希值，返回一个 40 字符的十六进制字符串。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT SHA1('hello') AS sha1_hash;",
  },
  {
    name: 'SHA',
    description: '计算字符串的 SHA-1 哈希值，返回一个 40 字符的十六进制字符串。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT SHA('hello') AS sha1_hash;",
  },
  {
    name: 'SHA2',
    description: '计算字符串的 SHA-2 哈希值，支持 224、256、384 或 512 位摘要。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'hash_length', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT SHA2('hello', 256) AS sha256_hash;",
  },
  {
    name: 'STATEMENT_DIGEST',
    description: '计算语句的摘要哈希值，用于 SQL 查询分析。',
    parameters: [{ name: 'sql_statement', type: 'VARCHAR' }],
    returnType: 'BLOB',
    example: "SELECT STATEMENT_DIGEST('SELECT * FROM users') AS digest;",
  },
  {
    name: 'STATEMENT_DIGEST_TEXT',
    description: '计算 SQL 语句的规范化摘要文本。',
    parameters: [{ name: 'sql_statement', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT STATEMENT_DIGEST_TEXT('SELECT * FROM users') AS digest_text;",
  },
  {
    name: 'UNCOMPRESS',
    description: '解压缩使用 COMPRESS() 函数压缩的字符串。',
    parameters: [{ name: 'compressed_data', type: 'BLOB' }],
    returnType: 'BLOB',
    example: "SELECT UNCOMPRESS(COMPRESS('This is a test string')) AS uncompressed_data;",
  },
  {
    name: 'UNCOMPRESSED_LENGTH',
    description: '返回压缩前字符串的原始长度。',
    parameters: [{ name: 'compressed_data', type: 'BLOB' }],
    returnType: 'INT',
    example: "SELECT UNCOMPRESSED_LENGTH(COMPRESS('This is a test string')) AS original_length;",
  },
  {
    name: 'VALIDATE_PASSWORD_STRENGTH',
    description: '确定密码的强度，返回密码的强度分数。',
    parameters: [{ name: 'password', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT VALIDATE_PASSWORD_STRENGTH('StrongPassword123!') AS strength_score;",
  },
];

/** Spatial functions. */
const Spatial_Functions: IFunction[] = [
  {
    name: 'GeomCollection',
    description: '根据几何图形构建几何图形集合。',
    parameters: [
      { name: 'geometry1', type: 'GEOMETRY' },
      { name: 'geometry2', type: 'GEOMETRY' },
      { name: 'geometryN', type: 'GEOMETRY', optional: true },
    ],
    returnType: 'GEOMETRYCOLLECTION',
    example:
      'SELECT ST_AsText(GeomCollection(Point(1, 1), LineString(Point(0, 0), Point(2, 2)))) AS geometry_collection;',
  },
  {
    name: 'LineString',
    description: '根据点值构造线串。',
    parameters: [
      { name: 'point1', type: 'POINT' },
      { name: 'point2', type: 'POINT' },
      { name: 'pointN', type: 'POINT', optional: true },
    ],
    returnType: 'LINESTRING',
    example: 'SELECT ST_AsText(LineString(Point(0, 0), Point(1, 1), Point(2, 2))) AS line_string;',
  },
  {
    name: 'MBRContains',
    description: '检查一个几何体的最小边界矩形（MBR）是否包含另一个几何体的 MBR。',
    parameters: [
      { name: 'geometry1', type: 'GEOMETRY' },
      { name: 'geometry2', type: 'GEOMETRY' },
    ],
    returnType: 'BOOL',
    example: "SELECT MBRContains(GeomFromText('POLYGON((0 0,0 3,3 3,3 0,0 0))'), Point(1, 1)) AS is_contained;",
  },
  {
    name: 'MBRCoveredBy',
    description: '检查一个 MBR 是否被另一个 MBR 覆盖。',
    parameters: [
      { name: 'geometry1', type: 'GEOMETRY' },
      { name: 'geometry2', type: 'GEOMETRY' },
    ],
    returnType: 'BOOL',
    example: "SELECT MBRCoveredBy(Point(1, 1), GeomFromText('POLYGON((0 0,0 3,3 3,3 0,0 0))')) AS is_covered;",
  },
  {
    name: 'MBRCovers',
    description: '检查一个 MBR 是否覆盖另一个 MBR。',
    parameters: [
      { name: 'geometry1', type: 'GEOMETRY' },
      { name: 'geometry2', type: 'GEOMETRY' },
    ],
    returnType: 'BOOL',
    example: "SELECT MBRCovers(GeomFromText('POLYGON((0 0,0 3,3 3,3 0,0 0))'), Point(1, 1)) AS does_cover;",
  },
  // Similar definitions are omitted.
  {
    name: 'ST_X',
    description: '返回点的 X 坐标。',
    parameters: [{ name: 'point', type: 'POINT' }],
    returnType: 'DOUBLE',
    example: 'SELECT ST_X(Point(1, 2)) AS x_coordinate;',
  },
  {
    name: 'ST_Y',
    description: '返回点的 Y 坐标。',
    parameters: [{ name: 'point', type: 'POINT' }],
    returnType: 'DOUBLE',
    example: 'SELECT ST_Y(Point(1, 2)) AS y_coordinate;',
  },
];

/** JSON functions. */
const JSON_Functions: IFunction[] = [
  {
    name: '->',
    description: '从 JSON 列评估路径后返回值，相当于 JSON_EXTRACT()。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
    ],
    returnType: 'JSON',
    example: "SELECT @json->'$.name' AS name;",
  },
  {
    name: '->>',
    description: '从 JSON 列评估路径并取消引用结果后返回值，相当于 JSON_UNQUOTE(JSON_EXTRACT())。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT @json->>'$.age' AS age;",
  },
  {
    name: 'JSON_ARRAY',
    description: '创建 JSON 数组。',
    parameters: [
      { name: 'value1', type: 'ANY' },
      { name: 'value2', type: 'ANY', optional: true },
      { name: 'value3', type: 'ANY', optional: true },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_ARRAY('apple', 'banana', 'cherry') AS json_array;",
  },
  {
    name: 'JSON_ARRAY_APPEND',
    description: '将数据附加到 JSON 文档。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
      { name: 'value', type: 'ANY' },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_ARRAY_APPEND(@json, '$', 'cherry') AS updated_json;",
  },
  {
    name: 'JSON_ARRAY_INSERT',
    description: '在 JSON 数组中插入数据。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
      { name: 'value', type: 'ANY' },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_ARRAY_INSERT(@json, '$[1]', 'banana') AS updated_json;",
  },
  {
    name: 'JSON_CONTAINS',
    description: '检查 JSON 文档是否包含路径中的特定对象。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'value', type: 'ANY' },
      { name: 'path', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT JSON_CONTAINS(@json, '\"Alice\"', '$.name') AS is_present;",
  },
  {
    name: 'JSON_CONTAINS_PATH',
    description: '检查 JSON 文档是否包含路径处的任何数据。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'one_or_all', type: 'VARCHAR' },
      { name: 'path1', type: 'VARCHAR' },
      { name: 'path2', type: 'VARCHAR', optional: true },
    ],
    returnType: 'BOOL',
    example: "SELECT JSON_CONTAINS_PATH(@json, 'one', '$.name', '$.gender') AS path_exists;",
  },
  {
    name: 'JSON_DEPTH',
    description: '返回 JSON 文档的最大深度。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'INT',
    example: 'SELECT JSON_DEPTH(@json) AS depth;',
  },
  {
    name: 'JSON_EXTRACT',
    description: '从 JSON 文档返回数据。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_EXTRACT(@json, '$.age') AS age;",
  },
  {
    name: 'JSON_INSERT',
    description: '将数据插入 JSON 文档。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
      { name: 'value', type: 'ANY' },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_INSERT(@json, '$.age', 30) AS updated_json;",
  },
  {
    name: 'JSON_KEYS',
    description: '返回 JSON 文档中的键数组。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'JSON',
    example: 'SELECT JSON_KEYS(@json) AS keys;',
  },
  {
    name: 'JSON_LENGTH',
    description: '返回 JSON 文档中的元素数量。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'INT',
    example: 'SELECT JSON_LENGTH(@json) AS length;',
  },
  {
    name: 'JSON_MERGE',
    description: '合并 JSON 文档，保留重复键。为 JSON_MERGE_PRESERVE() 的同义词。',
    parameters: [
      { name: 'json_doc1', type: 'JSON' },
      { name: 'json_doc2', type: 'JSON' },
    ],
    returnType: 'JSON',
    example: 'SELECT JSON_MERGE(@json1, @json2) AS merged_json;',
  },
  {
    name: 'JSON_MERGE_PATCH',
    description: '合并 JSON 文档，替换重复键的值。',
    parameters: [
      { name: 'json_doc1', type: 'JSON' },
      { name: 'json_doc2', type: 'JSON' },
    ],
    returnType: 'JSON',
    example: 'SELECT JSON_MERGE_PATCH(@json1, @json2) AS merged_json;',
  },
  {
    name: 'JSON_MERGE_PRESERVE',
    description: '合并 JSON 文档，保留重复的键。',
    parameters: [
      { name: 'json_doc1', type: 'JSON' },
      { name: 'json_doc2', type: 'JSON' },
    ],
    returnType: 'JSON',
    example: 'SELECT JSON_MERGE_PRESERVE(@json1, @json2) AS merged_json;',
  },
  {
    name: 'JSON_OBJECT',
    description: '创建 JSON 对象。',
    parameters: [
      { name: 'key1', type: 'VARCHAR' },
      { name: 'value1', type: 'ANY' },
      { name: 'key2', type: 'VARCHAR', optional: true },
      { name: 'value2', type: 'ANY', optional: true },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_OBJECT('name', 'Alice', 'age', 30) AS json_object;",
  },
  {
    name: 'JSON_OVERLAPS',
    description: '比较两个 JSON 文档，如果它们具有任何共同的键值对或数组元素，则返回 TRUE (1)，否则返回 FALSE (0)。',
    parameters: [
      { name: 'json_doc1', type: 'JSON' },
      { name: 'json_doc2', type: 'JSON' },
    ],
    returnType: 'BOOL',
    example: 'SELECT JSON_OVERLAPS(@json1, @json2) AS does_overlap;',
  },
  {
    name: 'JSON_PRETTY',
    description: '以人类可读的格式打印 JSON 文档。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'VARCHAR',
    example: 'SELECT JSON_PRETTY(@json) AS pretty_json;',
  },
  {
    name: 'JSON_QUOTE',
    description: '引用 JSON 文档。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: 'SELECT JSON_QUOTE(\'Alice said, "Hello!"\') AS quoted_json;',
  },
  {
    name: 'JSON_REMOVE',
    description: '从 JSON 文档中删除数据。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_REMOVE(@json, '$.age') AS updated_json;",
  },
  {
    name: 'JSON_REPLACE',
    description: '替换 JSON 文档中的值。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
      { name: 'value', type: 'ANY' },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_REPLACE(@json, '$.age', 31) AS updated_json;",
  },
  {
    name: 'JSON_SCHEMA_VALID',
    description: '根据 JSON 模式验证 JSON 文档；如果文档符合模式，则返回 TRUE/1，否则返回 FALSE/0。',
    parameters: [
      { name: 'schema', type: 'JSON' },
      { name: 'json_document', type: 'JSON' },
    ],
    returnType: 'BOOL',
    example: 'SELECT JSON_SCHEMA_VALID(@schema, @json) AS is_valid;',
  },
  {
    name: 'JSON_SCHEMA_VALIDATION_REPORT',
    description: '根据 JSON 模式验证 JSON 文档；以 JSON 格式返回验证结果报告，包括成功或失败以及失败的原因。',
    parameters: [
      { name: 'schema', type: 'JSON' },
      { name: 'json_document', type: 'JSON' },
    ],
    returnType: 'JSON',
    example: 'SELECT JSON_SCHEMA_VALIDATION_REPORT(@schema, @json) AS validation_report;',
  },
  {
    name: 'JSON_SEARCH',
    description: '查找 JSON 文档中值的路径。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'one_or_all', type: 'VARCHAR' },
      { name: 'value', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT JSON_SEARCH(@json, 'one', 'Alice') AS path;",
  },
  {
    name: 'JSON_SET',
    description: '将数据插入 JSON 文档。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
      { name: 'value', type: 'ANY' },
    ],
    returnType: 'JSON',
    example: "SELECT JSON_SET(@json, '$.age', 30) AS updated_json;",
  },
  {
    name: 'JSON_STORAGE_FREE',
    description: '返回部分更新后 JSON 列值的二进制表示中的释放空间。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'INT',
    example: "SELECT JSON_STORAGE_FREE(JSON_OBJECT('key', 'value')) AS storage_free;",
  },
  {
    name: 'JSON_STORAGE_SIZE',
    description: '返回用于存储 JSON 文档二进制表示的空间。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'INT',
    example: "SELECT JSON_STORAGE_SIZE(JSON_OBJECT('key', 'value')) AS storage_size;",
  },
  {
    name: 'JSON_TABLE',
    description: '将 JSON 表达式中的数据作为关系表返回。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
      { name: 'columns', type: 'COLUMN_LIST' },
    ],
    returnType: 'TABLE',
    example:
      "SELECT * FROM JSON_TABLE(@json, '$[*]' COLUMNS (name VARCHAR(50) PATH '$.name', age INT PATH '$.age')) AS jt;",
  },
  {
    name: 'JSON_TYPE',
    description: '返回 JSON 值的类型。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'VARCHAR',
    example: 'SELECT JSON_TYPE(@json) AS json_type;',
  },
  {
    name: 'JSON_UNQUOTE',
    description: '取消引用 JSON 值。',
    parameters: [{ name: 'json_value', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: 'SELECT JSON_UNQUOTE(\'"Hello, World!"\') AS unquoted_value;',
  },
  {
    name: 'JSON_VALID',
    description: '检查 JSON 值是否有效。',
    parameters: [{ name: 'json_document', type: 'JSON' }],
    returnType: 'BOOL',
    example: 'SELECT JSON_VALID(\'{"name": "Alice"}\') AS is_valid;',
  },
  {
    name: 'JSON_VALUE',
    description: '从提供的路径指向的位置的 JSON 文档中提取值；以 VARCHAR(512) 或指定类型返回此值。',
    parameters: [
      { name: 'json_document', type: 'JSON' },
      { name: 'path', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT JSON_VALUE(@json, '$.name') AS name;",
  },
  {
    name: 'MEMBER OF',
    description:
      '如果第一个操作数与作为第二个操作数传递的 JSON 数组的任何元素匹配，则返回 true (1)，否则返回 false (0)。',
    parameters: [
      { name: 'element', type: 'ANY' },
      { name: 'json_array', type: 'JSON' },
    ],
    returnType: 'BOOL',
    example: "SELECT 'apple' MEMBER OF('['banana', 'apple', 'cherry']') AS is_member;",
  },
];

/** String functions. */
const String_Functions: IFunction[] = [
  {
    name: 'ASCII',
    description: '返回字符串中最左边字符的 ASCII 码值。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT ASCII('A') AS ascii_value;",
  },
  {
    name: 'BIN',
    description: '返回数字的二进制表示形式的字符串。',
    parameters: [{ name: 'number', type: 'INT' }],
    returnType: 'VARCHAR',
    example: 'SELECT BIN(5) AS binary_value;',
  },
  {
    name: 'BIT_LENGTH',
    description: '返回字符串的长度（以位为单位）。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT BIT_LENGTH('hello') AS bit_length;",
  },
  {
    name: 'CHAR',
    description: '返回传递的每个整数对应的字符。',
    parameters: [
      { name: 'int1', type: 'INT' },
      { name: 'int2', type: 'INT', optional: true },
      { name: 'int3', type: 'INT', optional: true },
    ],
    returnType: 'VARCHAR',
    example: 'SELECT CHAR(65, 66, 67) AS char_value;',
  },
  {
    name: 'CHAR_LENGTH',
    description: '返回字符串中的字符数。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT CHAR_LENGTH('hello') AS char_length;",
  },
  {
    name: 'CHARACTER_LENGTH',
    description: 'CHAR_LENGTH() 的同义词。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT CHARACTER_LENGTH('hello') AS char_length;",
  },
  {
    name: 'CONCAT',
    description: '返回连接后的字符串。',
    parameters: [
      { name: 'string1', type: 'VARCHAR' },
      { name: 'string2', type: 'VARCHAR' },
      { name: 'string3', type: 'VARCHAR', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT CONCAT('Hello', ' ', 'World') AS concatenated_string;",
  },
  {
    name: 'CONCAT_WS',
    description: '使用指定分隔符连接字符串。',
    parameters: [
      { name: 'separator', type: 'VARCHAR' },
      { name: 'string1', type: 'VARCHAR' },
      { name: 'string2', type: 'VARCHAR' },
      { name: 'string3', type: 'VARCHAR', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT CONCAT_WS('-', '2024', '08', '05') AS concatenated_string;",
  },
  {
    name: 'ELT',
    description: '返回指定索引号处的字符串。',
    parameters: [
      { name: 'index', type: 'INT' },
      { name: 'string1', type: 'VARCHAR' },
      { name: 'string2', type: 'VARCHAR', optional: true },
      { name: 'string3', type: 'VARCHAR', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT ELT(2, 'red', 'green', 'blue') AS elt_value;",
  },
  {
    name: 'EXPORT_SET',
    description: '返回一个字符串，对于值位中设置的每个位，得到一个开启字符串；对于每个未设置的位，得到一个关闭字符串。',
    parameters: [
      { name: 'bits', type: 'INT' },
      { name: 'on', type: 'VARCHAR' },
      { name: 'off', type: 'VARCHAR' },
      { name: 'separator', type: 'VARCHAR', optional: true },
      { name: 'number_of_bits', type: 'INT', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT EXPORT_SET(5, 'Y', 'N', ',', 4) AS export_set_value;",
  },
  {
    name: 'FIELD',
    description: '返回第一个参数在后续参数中的索引（位置）。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'string1', type: 'VARCHAR' },
      { name: 'string2', type: 'VARCHAR' },
      { name: 'string3', type: 'VARCHAR', optional: true },
    ],
    returnType: 'INT',
    example: "SELECT FIELD('b', 'a', 'b', 'c', 'd') AS field_index;",
  },
  {
    name: 'FIND_IN_SET',
    description: '返回第一个参数在第二个参数中的索引（位置），第二个参数是以逗号分隔的字符串列表。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'string_list', type: 'VARCHAR' },
    ],
    returnType: 'INT',
    example: "SELECT FIND_IN_SET('b', 'a,b,c,d') AS find_index;",
  },
  {
    name: 'FORMAT',
    description: '返回格式化为指定小数位数的数字。',
    parameters: [
      { name: 'number', type: 'DECIMAL' },
      { name: 'decimals', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: 'SELECT FORMAT(12345.6789, 2) AS formatted_number;',
  },
  {
    name: 'FROM_BASE64',
    description: '解码 base64 编码的字符串并返回结果。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'BLOB',
    example: "SELECT FROM_BASE64('SGVsbG8=') AS decoded_value;",
  },
  {
    name: 'HEX',
    description: '返回十进制或字符串值的十六进制表示。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT HEX('Hello') AS hex_value;",
  },
  {
    name: 'INSERT',
    description: '在指定位置插入子字符串，最多可插入指定数量的字符。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'position', type: 'INT' },
      { name: 'length', type: 'INT' },
      { name: 'substring', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT INSERT('Hello World', 7, 5, 'MySQL') AS inserted_string;",
  },
  {
    name: 'INSTR',
    description: '返回子字符串第一次出现的索引。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'substring', type: 'VARCHAR' },
    ],
    returnType: 'INT',
    example: "SELECT INSTR('Hello World', 'World') AS instr_index;",
  },
  {
    name: 'LCASE',
    description: 'LOWER() 的同义词。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT LCASE('HELLO') AS lower_case;",
  },
  {
    name: 'LEFT',
    description: '返回最左边的指定字符数。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'length', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT LEFT('Hello World', 5) AS left_string;",
  },
  {
    name: 'LENGTH',
    description: '返回字符串的长度（以字节为单位）。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT LENGTH('Hello') AS byte_length;",
  },
  {
    name: 'LIKE',
    description: '用于简单模式匹配。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT 'Hello' LIKE 'H%' AS is_match;",
  },
  {
    name: 'LOAD_FILE',
    description: '加载指定文件的内容。',
    parameters: [{ name: 'file_name', type: 'VARCHAR' }],
    returnType: 'BLOB',
    example: "SELECT LOAD_FILE('/path/to/file.txt') AS file_content;",
  },
  {
    name: 'LOCATE',
    description: '返回子字符串第一次出现的位置。',
    parameters: [
      { name: 'substring', type: 'VARCHAR' },
      { name: 'string', type: 'VARCHAR' },
      { name: 'start_position', type: 'INT', optional: true },
    ],
    returnType: 'INT',
    example: "SELECT LOCATE('World', 'Hello World') AS locate_index;",
  },
  {
    name: 'LOWER',
    description: '以小写形式返回参数。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT LOWER('HELLO') AS lower_case;",
  },
  {
    name: 'LPAD',
    description: '返回字符串参数，左侧填充指定的字符串以达到指定长度。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'length', type: 'INT' },
      { name: 'pad_string', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT LPAD('Hello', 10, '*') AS padded_string;",
  },
  {
    name: 'LTRIM',
    description: '删除前导空格。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT LTRIM('   Hello') AS trimmed_string;",
  },
  {
    name: 'MAKE_SET',
    description: '返回一组以逗号分隔的字符串，这些字符串在位集中具有相应的位。',
    parameters: [
      { name: 'bits', type: 'INT' },
      { name: 'string1', type: 'VARCHAR' },
      { name: 'string2', type: 'VARCHAR' },
      { name: 'string3', type: 'VARCHAR', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT MAKE_SET(5, 'a', 'b', 'c', 'd') AS make_set_value;",
  },
  {
    name: 'MATCH',
    description: '执行全文搜索。',
    parameters: [
      { name: 'columns', type: 'COLUMN_LIST' },
      { name: 'against', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT * FROM articles WHERE MATCH(title, content) AGAINST('search term');",
  },
  {
    name: 'MID',
    description: '返回从指定位置开始的子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'start_position', type: 'INT' },
      { name: 'length', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT MID('Hello World', 7, 5) AS substring;",
  },
  {
    name: 'NOT LIKE',
    description: '简单模式匹配的否定。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT 'Hello' NOT LIKE 'H%' AS is_not_match;",
  },
  {
    name: 'NOT REGEXP',
    description: 'REGEXP 的否定，检查字符串是否不匹配正则表达式。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT 'Hello' NOT REGEXP '^H' AS is_not_match;",
  },
  {
    name: 'OCT',
    description: '返回数字的八进制表示形式的字符串。',
    parameters: [{ name: 'number', type: 'INT' }],
    returnType: 'VARCHAR',
    example: 'SELECT OCT(8) AS octal_value;',
  },
  {
    name: 'OCTET_LENGTH',
    description: 'LENGTH() 的同义词。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT OCTET_LENGTH('Hello') AS byte_length;",
  },
  {
    name: 'ORD',
    description: '返回参数最左边字符的字符代码。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'INT',
    example: "SELECT ORD('A') AS ord_value;",
  },
  {
    name: 'POSITION',
    description: 'LOCATE() 的同义词。',
    parameters: [
      { name: 'substring', type: 'VARCHAR' },
      { name: 'string', type: 'VARCHAR' },
    ],
    returnType: 'INT',
    example: "SELECT POSITION('World' IN 'Hello World') AS position_index;",
  },
  {
    name: 'QUOTE',
    description: '转义 SQL 语句中使用的参数。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT QUOTE('Hello World') AS quoted_string;",
  },
  {
    name: 'REGEXP',
    description: '检查字符串是否与正则表达式匹配。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT 'Hello' REGEXP '^H' AS is_match;",
  },
  {
    name: 'REGEXP_INSTR',
    description: '返回匹配正则表达式的子字符串的起始索引。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'INT',
    example: "SELECT REGEXP_INSTR('abcdefg', 'c.e') AS regex_index;",
  },
  {
    name: 'REGEXP_LIKE',
    description: '检查字符串是否与正则表达式匹配。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT REGEXP_LIKE('Hello', '^H') AS is_match;",
  },
  {
    name: 'REGEXP_REPLACE',
    description: '替换与正则表达式匹配的子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
      { name: 'replacement', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT REGEXP_REPLACE('abc def ghi', '\\\\s', '-') AS replaced_string;",
  },
  {
    name: 'REGEXP_SUBSTR',
    description: '返回与正则表达式匹配的子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT REGEXP_SUBSTR('abcdefg', 'c.e') AS matched_substr;",
  },
  {
    name: 'REPEAT',
    description: '返回指定次数的重复字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'count', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT REPEAT('Hello', 3) AS repeated_string;",
  },
  {
    name: 'REPLACE',
    description: '替换字符串中的所有指定出现。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'from_string', type: 'VARCHAR' },
      { name: 'to_string', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT REPLACE('Hello World', 'World', 'MySQL') AS replaced_string;",
  },
  {
    name: 'REVERSE',
    description: '反转字符串中的字符。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT REVERSE('Hello') AS reversed_string;",
  },
  {
    name: 'RIGHT',
    description: '返回最右边的指定字符数。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'length', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT RIGHT('Hello World', 5) AS right_string;",
  },
  {
    name: 'RLIKE',
    description: 'REGEXP 的同义词，检查字符串是否与正则表达式匹配。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'pattern', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT 'Hello' RLIKE '^H' AS is_match;",
  },
  {
    name: 'RPAD',
    description: '右侧填充指定的字符串以达到指定长度。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'length', type: 'INT' },
      { name: 'pad_string', type: 'VARCHAR' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT RPAD('Hello', 10, '*') AS padded_string;",
  },
  {
    name: 'RTRIM',
    description: '删除尾随空格。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT RTRIM('Hello   ') AS trimmed_string;",
  },
  {
    name: 'SOUNDEX',
    description: '返回字符串的 Soundex 表示，用于语音相似性比较。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT SOUNDEX('Hello') AS soundex_value;",
  },
  {
    name: 'SOUNDS LIKE',
    description: '检查两个字符串的 Soundex 表示是否相似。',
    parameters: [
      { name: 'string1', type: 'VARCHAR' },
      { name: 'string2', type: 'VARCHAR' },
    ],
    returnType: 'BOOL',
    example: "SELECT 'Hello' SOUNDS LIKE 'Hillo' AS is_similar;",
  },
  {
    name: 'SPACE',
    description: '返回指定数量的空格字符串。',
    parameters: [{ name: 'count', type: 'INT' }],
    returnType: 'VARCHAR',
    example: 'SELECT SPACE(5) AS space_string;',
  },
  {
    name: 'STRCMP',
    description: '比较两个字符串。',
    parameters: [
      { name: 'string1', type: 'VARCHAR' },
      { name: 'string2', type: 'VARCHAR' },
    ],
    returnType: 'INT',
    example: "SELECT STRCMP('Hello', 'World') AS compare_result;",
  },
  {
    name: 'SUBSTR',
    description: '返回从指定位置开始的子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'start_position', type: 'INT' },
      { name: 'length', type: 'INT', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT SUBSTR('Hello World', 7, 5) AS substring;",
  },
  {
    name: 'SUBSTRING',
    description: '返回从指定位置开始的子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'start_position', type: 'INT' },
      { name: 'length', type: 'INT', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT SUBSTRING('Hello World', 7, 5) AS substring;",
  },
  {
    name: 'SUBSTRING_INDEX',
    description: '返回字符串中分隔符出现指定次数之前的子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR' },
      { name: 'delimiter', type: 'VARCHAR' },
      { name: 'count', type: 'INT' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT SUBSTRING_INDEX('a,b,c,d', ',', 2) AS substring;",
  },
  {
    name: 'TO_BASE64',
    description: '返回转换为 base64 字符串的参数。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT TO_BASE64('Hello') AS base64_value;",
  },
  {
    name: 'TRIM',
    description: '删除前导空格和尾随空格。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT TRIM('   Hello   ') AS trimmed_string;",
  },
  {
    name: 'UCASE',
    description: 'UPPER() 的同义词。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT UCASE('hello') AS upper_case;",
  },
  {
    name: 'UNHEX',
    description: '将十六进制表示的字符串转换为 ASCII 字符串。',
    parameters: [{ name: 'hex_string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT UNHEX('48656C6C6F') AS ascii_string;",
  },
  {
    name: 'UPPER',
    description: '将字符串转换为大写。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT UPPER('hello') AS upper_case;",
  },
  {
    name: 'WEIGHT_STRING',
    description: '返回字符串的权重字符串，用于排序规则比较。',
    parameters: [{ name: 'string', type: 'VARCHAR' }],
    returnType: 'VARCHAR',
    example: "SELECT WEIGHT_STRING('hello') AS weight_str;",
  },
];

/** Aggregate functions. */
const Aggregate_Functions: IFunction[] = [
  {
    name: 'AVG',
    description: '返回参数的平均值。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT AVG(salary) AS average_salary FROM employees;',
  },
  {
    name: 'BIT_AND',
    description: '返回按位与操作的结果。',
    parameters: [{ name: 'integer_expression', type: 'INT' }],
    returnType: 'INT',
    example: 'SELECT BIT_AND(flags) AS bitwise_and_result FROM settings;',
  },
  {
    name: 'BIT_OR',
    description: '返回按位或操作的结果。',
    parameters: [{ name: 'integer_expression', type: 'INT' }],
    returnType: 'INT',
    example: 'SELECT BIT_OR(flags) AS bitwise_or_result FROM settings;',
  },
  {
    name: 'BIT_XOR',
    description: '返回按位异或操作的结果。',
    parameters: [{ name: 'integer_expression', type: 'INT' }],
    returnType: 'INT',
    example: 'SELECT BIT_XOR(flags) AS bitwise_xor_result FROM settings;',
  },
  {
    name: 'COUNT',
    description: '返回满足条件的行数。',
    parameters: [{ name: 'expression', type: 'ANY', optional: true }],
    returnType: 'INT',
    example: 'SELECT COUNT(*) AS total_rows FROM employees;',
  },
  {
    name: 'COUNT(DISTINCT)',
    description: '返回不同值的数量。',
    parameters: [{ name: 'expression', type: 'ANY' }],
    returnType: 'INT',
    example: 'SELECT COUNT(DISTINCT department) AS unique_departments FROM employees;',
  },
  {
    name: 'GROUP_CONCAT',
    description: '返回连接字符串，通常用于连接分组中的多个值。',
    parameters: [
      { name: 'expression', type: 'VARCHAR' },
      { name: 'order_by_clause', type: 'ORDER BY', optional: true },
      { name: 'separator', type: 'VARCHAR', optional: true },
    ],
    returnType: 'VARCHAR',
    example: 'SELECT department, GROUP_CONCAT(employee_name) AS employee_names FROM employees GROUP BY department;',
  },
  {
    name: 'JSON_ARRAYAGG',
    description: '以单个 JSON 数组形式返回结果集。',
    parameters: [{ name: 'expression', type: 'ANY' }],
    returnType: 'JSON',
    example: "SELECT JSON_ARRAYAGG(employee_name) AS employee_names_json FROM employees WHERE department = 'Sales';",
  },
  {
    name: 'JSON_OBJECTAGG',
    description: '将结果集作为单个 JSON 对象返回。',
    parameters: [
      { name: 'key_expression', type: 'ANY' },
      { name: 'value_expression', type: 'ANY' },
    ],
    returnType: 'JSON',
    example: 'SELECT JSON_OBJECTAGG(employee_id, employee_name) AS employee_data_json FROM employees;',
  },
  {
    name: 'MAX',
    description: '返回最大值。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'NUMERIC',
    example: 'SELECT MAX(salary) AS highest_salary FROM employees;',
  },
  {
    name: 'MIN',
    description: '返回最小值。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'NUMERIC',
    example: 'SELECT MIN(salary) AS lowest_salary FROM employees;',
  },
  {
    name: 'STD',
    description: '返回总体标准差。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT STD(salary) AS salary_stddev FROM employees;',
  },
  {
    name: 'STDDEV',
    description: '返回总体标准差，STD() 的同义词。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT STDDEV(salary) AS salary_stddev FROM employees;',
  },
  {
    name: 'STDDEV_POP',
    description: '返回总体标准差。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT STDDEV_POP(salary) AS salary_stddev_pop FROM employees;',
  },
  {
    name: 'STDDEV_SAMP',
    description: '返回样本标准差。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT STDDEV_SAMP(salary) AS salary_stddev_samp FROM employees;',
  },
  {
    name: 'SUM',
    description: '返回数值的总和。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT SUM(salary) AS total_salary FROM employees;',
  },
  {
    name: 'VAR_POP',
    description: '返回总体标准方差。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT VAR_POP(salary) AS salary_var_pop FROM employees;',
  },
  {
    name: 'VAR_SAMP',
    description: '返回样本方差。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT VAR_SAMP(salary) AS salary_var_samp FROM employees;',
  },
  {
    name: 'VARIANCE',
    description: '返回总体标准方差。',
    parameters: [{ name: 'numeric_expression', type: 'NUMERIC' }],
    returnType: 'DECIMAL',
    example: 'SELECT VARIANCE(salary) AS salary_variance FROM employees;',
  },
];

/** Window functions. */
const Window_Functions: IFunction[] = [
  {
    name: 'CUME_DIST',
    description: '计算当前行的累计分配值，即当前行在分区内的累积分布。',
    parameters: [],
    returnType: 'DECIMAL',
    example: 'SELECT employee_name, salary, CUME_DIST() OVER (ORDER BY salary) AS cume_dist FROM employees;',
  },
  {
    name: 'DENSE_RANK',
    description: '为当前行在分区内的排名，无间隙。',
    parameters: [],
    returnType: 'INT',
    example: 'SELECT employee_name, salary, DENSE_RANK() OVER (ORDER BY salary DESC) AS dense_rank FROM employees;',
  },
  {
    name: 'FIRST_VALUE',
    description: '返回来自窗口框架第一行的参数值。',
    parameters: [{ name: 'expression', type: 'ANY' }],
    returnType: 'ANY',
    insert_text: 'FIRST_VALUE(${1:}) OVER(${2:}); ',
    example:
      'SELECT employee_name, salary, FIRST_VALUE(salary) OVER (ORDER BY hire_date) AS first_salary FROM employees;',
  },
  {
    name: 'LAG',
    description: '返回分区内当前行之前第 n 行的参数值。',
    parameters: [
      { name: 'expression', type: 'ANY' },
      { name: 'offset', type: 'INT', optional: true },
      { name: 'default_value', type: 'ANY', optional: true },
    ],
    returnType: 'ANY',
    example:
      'SELECT employee_name, salary, LAG(salary, 1, 0) OVER (ORDER BY hire_date) AS previous_salary FROM employees;',
  },
  {
    name: 'LAST_VALUE',
    description: '返回窗口框架最后一行的参数值。',
    parameters: [{ name: 'expression', type: 'ANY' }],
    returnType: 'ANY',
    example:
      'SELECT employee_name, salary, LAST_VALUE(salary) OVER (ORDER BY hire_date RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS last_salary FROM employees;',
  },
  {
    name: 'LEAD',
    description: '返回分区内当前行之后第 n 行的参数值。',
    parameters: [
      { name: 'expression', type: 'ANY' },
      { name: 'offset', type: 'INT', optional: true },
      { name: 'default_value', type: 'ANY', optional: true },
    ],
    returnType: 'ANY',
    example:
      'SELECT employee_name, salary, LEAD(salary, 1, 0) OVER (ORDER BY hire_date) AS next_salary FROM employees;',
  },
  {
    name: 'NTH_VALUE',
    description: '返回来自窗口框架第 N 行的参数值。',
    parameters: [
      { name: 'expression', type: 'ANY' },
      { name: 'n', type: 'INT' },
    ],
    returnType: 'ANY',
    example:
      'SELECT employee_name, salary, NTH_VALUE(salary, 3) OVER (ORDER BY hire_date RANGE BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS nth_salary FROM employees;',
  },
  {
    name: 'NTILE',
    description: '将行分配到指定数量的桶中，返回当前行的桶号。',
    parameters: [{ name: 'buckets', type: 'INT' }],
    returnType: 'INT',
    example: 'SELECT employee_name, salary, NTILE(4) OVER (ORDER BY salary DESC) AS bucket_number FROM employees;',
  },
  {
    name: 'PERCENT_RANK',
    description: '返回当前行的百分比排名值。',
    parameters: [],
    returnType: 'DECIMAL',
    example: 'SELECT employee_name, salary, PERCENT_RANK() OVER (ORDER BY salary DESC) AS percent_rank FROM employees;',
  },
  {
    name: 'RANK',
    description: '为当前行在分区内的排名，有间隙。',
    parameters: [],
    returnType: 'INT',
    example: 'SELECT employee_name, salary, RANK() OVER (ORDER BY salary DESC) AS rank FROM employees;',
  },
  {
    name: 'ROW_NUMBER',
    description: '返回分区内当前行的行号。',
    parameters: [],
    returnType: 'INT',
    example: 'SELECT employee_name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_number FROM employees;',
  },
];

const MySQL: IKeyword = {
  type: DatabaseTypeCode.MYSQL,
  priority_keywords: [
    'SELECT',
    'FROM',
    'WHERE',
    'ORDER BY',
    'JOIN',
    'INNER JOIN',
    'LEFT JOIN',
    'RIGHT JOIN',
    'OUTER JOIN',
    'ON',
    'AND',
    'OR',
    'NOT',
    'INSERT',
    'UPDATE',
    'DELETE',
    'CREATE',
    'ALTER',
    'DROP',
    'TABLE',
    'INDEX',
    'VIEW',
  ],
  keywords: [
    'PROCEDURE',
    'FUNCTION',
    'TRIGGER',
    'DATABASE',
    'SCHEMA',
    'IN',
    'LIKE',
    'BETWEEN',
    'IS NULL',
    'IS NOT NULL',
    'AS',
    'GROUP BY',
    'HAVING',
    'LIMIT',
    'OFFSET',
    'UNION',
    'UNION ALL',
    'DISTINCT',
    'COUNT',
    'SUM',
    'AVG',
    'MAX',
    'MIN',
    'CASE',
    'WHEN',
    'THEN',
    'ELSE',
    'END',
    'IF',
    'IFNULL',
    'COALESCE',
    'NULLIF',
    'PRIMARY KEY',
    'FOREIGN KEY',
    'REFERENCES',
    'CASCADE',
    'SET NULL',
    'AUTO_INCREMENT',
    'DEFAULT',
    'CONSTRAINT',
    'UNIQUE',
    'CHECK',
    'TRUNCATE',
    'EXPLAIN',
    'DESC',
    'ASC',
    'SHOW',
    'USE',
    'GRANT',
    'REVOKE',
    'COMMIT',
    'ROLLBACK',
    'START TRANSACTION',
    'SAVEPOINT',
    'LOCK TABLES',
    'UNLOCK TABLES',
    // Other less common keywords are omitted.
    'ACCESSIBLE',
    'ADD',
    'ALL',
    'ANALYZE',
    'ASENSITIVE',
    'BEFORE',
    'BIGINT',
    'BINARY',
    'BLOB',
    'BOTH',
    'CALL',
    'CHANGE',
    'CHAR',
    'CHARACTER',
    'COLLATE',
    'COLUMN',
    'CONDITION',
    'CONTINUE',
    'CONVERT',
    'CROSS',
    'CUBE',
    'CUME_DIST',
    'CURRENT_DATE',
    'CURRENT_TIME',
    'CURRENT_TIMESTAMP',
    'CURRENT_USER',
    'CURSOR',
    'DATABASES',
    'DAY_HOUR',
    'DAY_MICROSECOND',
    'DAY_MINUTE',
    'DAY_SECOND',
    'DEC',
    'DECIMAL',
    'DECLARE',
    'DELAYED',
    'DENSE_RANK',
    'DESCRIBE',
    'DETERMINISTIC',
    'DISTINCTROW',
    'DIV',
    'DOUBLE',
    'DUAL',
    'EACH',
    'ELSEIF',
    'EMPTY',
    'ENCLOSED',
    'ESCAPED',
    'EXCEPT',
    'EXISTS',
    'EXIT',
    'FALSE',
    'FETCH',
    'FIRST_VALUE',
    'FLOAT',
    'FLOAT4',
    'FLOAT8',
    'FOR',
    'FORCE',
    'FULLTEXT',
    'GENERATED',
    'GET',
    'GROUPING',
    'GROUPS',
    'HIGH_PRIORITY',
    'HOUR_MICROSECOND',
    'HOUR_MINUTE',
    'HOUR_SECOND',
    'IGNORE',
    'INFILE',
    'INOUT',
    'INSENSITIVE',
    'INT',
    'INT1',
    'INT2',
    'INT3',
    'INT4',
    'INT8',
    'INTEGER',
    'INTERVAL',
    'INTO',
    'IO_AFTER_GTIDS',
    'IO_BEFORE_GTIDS',
    'ITERATE',
    'JSON_TABLE',
    'KEYS',
    'KILL',
    'LAG',
    'LAST_VALUE',
    'LATERAL',
    'LEAD',
    'LEADING',
    'LEAVE',
    'LINEAR',
    'LINES',
    'LOAD',
    'LOCALTIME',
    'LOCALTIMESTAMP',
    'LOCK',
    'LONG',
    'LONGBLOB',
    'LONGTEXT',
    'LOOP',
    'LOW_PRIORITY',
    'MASTER_BIND',
    'MASTER_SSL_VERIFY_SERVER_CERT',
    'MATCH',
    'MAXVALUE',
    'MEDIUMBLOB',
    'MEDIUMINT',
    'MEDIUMTEXT',
    'MIDDLEINT',
    'MINUTE_MICROSECOND',
    'MINUTE_SECOND',
    'MOD',
    'MODIFIES',
    'NATURAL',
    'NO_WRITE_TO_BINLOG',
    'NTH_VALUE',
    'NTILE',
    'NUMERIC',
    'OF',
    'OPTIMIZE',
    'OPTIMIZER_COSTS',
    'OPTION',
    'OPTIONALLY',
    'OUTFILE',
    'OVER',
    'PARTITION',
    'PERCENT_RANK',
    'PRECISION',
    'PURGE',
    'RANGE',
    'RANK',
    'READS',
    'READ_WRITE',
    'REAL',
    'RECURSIVE',
    'REGEXP',
    'RELEASE',
    'RENAME',
    'REPEAT',
    'REPLACE',
    'REQUIRE',
    'RESIGNAL',
    'RESTRICT',
    'RETURN',
    'RIGHT',
    'RLIKE',
    'ROW',
    'ROWS',
    'ROW_NUMBER',
    'SCHEMAS',
    'SECOND_MICROSECOND',
    'SENSITIVE',
    'SEPARATOR',
    'SET',
    'SIGNAL',
    'SMALLINT',
    'SPATIAL',
    'SPECIFIC',
    'SQL',
    'SQLEXCEPTION',
    'SQLSTATE',
    'SQLWARNING',
    'SQL_BIG_RESULT',
    'SQL_CALC_FOUND_ROWS',
    'SQL_SMALL_RESULT',
    'SQL_NO_CACHE',
    'SSL',
    'STARTING',
    'STORED',
    'STRAIGHT_JOIN',
    'SYSTEM',
    'TERMINATED',
    'TINYBLOB',
    'TINYINT',
    'TINYTEXT',
    'TO',
    'TRAILING',
    'TRUE',
    'UNDO',
    'UNSIGNED',
    'USAGE',
    'USING',
    'UTC_DATE',
    'UTC_TIME',
    'UTC_TIMESTAMP',
    'VALUES',
    'VARBINARY',
    'VARCHAR',
    'VARCHARACTER',
    'VARYING',
    'VIRTUAL',
    'WHILE',
    'WINDOW',
    'WITH',
    'WRITE',
    'XOR',
    'YEAR_MONTH',
    'ZEROFILL',
  ],
  priority_functions: [],
  functions: [
    ...Math_Functions,
    ...Date_Functions,
    ...Conversion_Functions,
    ...XML_Functions,
    ...Encryption_Functions,
    ...Spatial_Functions,
    ...JSON_Functions,
    ...String_Functions,
    ...Aggregate_Functions,
    ...Window_Functions,
  ],
};

export default MySQL;
