import { DatabaseTypeCode } from '@/constants/common';
import { IFunction, IKeyword } from '.';

const Math_Functions: IFunction[] = [
  {
    name: 'ABS',
    description: '返回数值的绝对值。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT ABS(-15) AS absolute_value FROM DUAL;',
  },
  {
    name: 'ACOS',
    description: '返回数值的反余弦值（以弧度表示）。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT ACOS(0.5) AS arccosine FROM DUAL;',
  },
  {
    name: 'ASIN',
    description: '返回数值的反正弦值（以弧度表示）。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT ASIN(0.5) AS arcsine FROM DUAL;',
  },
  {
    name: 'ATAN',
    description: '返回数值的反正切值（以弧度表示）。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT ATAN(1) AS arctangent FROM DUAL;',
  },
  {
    name: 'ATAN2',
    description: '返回两个数值的反正切值（以弧度表示）。',
    parameters: [
      { name: 'y', type: 'NUMBER' },
      { name: 'x', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT ATAN2(1, 1) AS arctangent FROM DUAL;',
  },
  {
    name: 'BITAND',
    description: '返回两个整数的按位与运算结果。',
    parameters: [
      { name: 'expr1', type: 'NUMBER' },
      { name: 'expr2', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT BITAND(6, 3) AS bitwise_and FROM DUAL;',
  },
  {
    name: 'CEIL',
    description: '返回大于或等于指定数值的最小整数。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT CEIL(15.7) AS ceiling_value FROM DUAL;',
  },
  {
    name: 'COS',
    description: '返回数值的余弦值（以弧度表示）。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT COS(0) AS cosine FROM DUAL;',
  },
  {
    name: 'COSH',
    description: '返回数值的双曲余弦值。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT COSH(0) AS hyperbolic_cosine FROM DUAL;',
  },
  {
    name: 'EXP',
    description: '返回自然常数e的指定次幂。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT EXP(1) AS exponential_value FROM DUAL;',
  },
  {
    name: 'FLOOR',
    description: '返回小于或等于指定数值的最大整数。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT FLOOR(15.7) AS floor_value FROM DUAL;',
  },
  {
    name: 'LN',
    description: '返回数值的自然对数。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT LN(1) AS natural_log FROM DUAL;',
  },
  {
    name: 'LOG',
    description: '返回以指定底数的对数。',
    parameters: [
      { name: 'base', type: 'NUMBER' },
      { name: 'number', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT LOG(10, 100) AS logarithm FROM DUAL;',
  },
  {
    name: 'MOD',
    description: '返回两个数值相除后的余数。',
    parameters: [
      { name: 'number1', type: 'NUMBER' },
      { name: 'number2', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT MOD(10, 3) AS remainder FROM DUAL;',
  },
  {
    name: 'NANVL',
    description: '如果第一个参数是NaN，则返回第二个参数。',
    parameters: [
      { name: 'expr1', type: 'NUMBER' },
      { name: 'expr2', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT NANVL(NAN, 10) AS nan_value FROM DUAL;',
  },
  {
    name: 'POWER',
    description: '返回指定底数的指定次幂。',
    parameters: [
      { name: 'base', type: 'NUMBER' },
      { name: 'exponent', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT POWER(2, 3) AS power_value FROM DUAL;',
  },
  {
    name: 'REMAINDER',
    description: '返回两个数值相除后的余数，符号与被除数相同。',
    parameters: [
      { name: 'number1', type: 'NUMBER' },
      { name: 'number2', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT REMAINDER(9, 4) AS remainder_value FROM DUAL;',
  },
  {
    name: 'ROUND',
    description: '将数字四舍五入到指定的小数位数。',
    parameters: [
      { name: 'number', type: 'NUMBER' },
      { name: 'decimals', type: 'NUMBER', optional: true },
    ],
    returnType: 'NUMBER',
    example: 'SELECT ROUND(15.678, 2) AS rounded_value FROM DUAL;',
  },
  {
    name: 'SIGN',
    description: '返回数值的符号：1（正数）、0（零）或-1（负数）。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT SIGN(-15) AS sign_value FROM DUAL;',
  },
  {
    name: 'SIN',
    description: '返回数值的正弦值（以弧度表示）。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT SIN(0) AS sine FROM DUAL;',
  },
  {
    name: 'SINH',
    description: '返回数值的双曲正弦值。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT SINH(0) AS hyperbolic_sine FROM DUAL;',
  },
  {
    name: 'SQRT',
    description: '返回数值的平方根。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT SQRT(16) AS square_root FROM DUAL;',
  },
  {
    name: 'TAN',
    description: '返回数值的正切值（以弧度表示）。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT TAN(0) AS tangent FROM DUAL;',
  },
  {
    name: 'TANH',
    description: '返回数值的双曲正切值。',
    parameters: [{ name: 'number', type: 'NUMBER' }],
    returnType: 'NUMBER',
    example: 'SELECT TANH(0) AS hyperbolic_tangent FROM DUAL;',
  },
  {
    name: 'TRUNC',
    description: '将数字截断到指定的小数位数。',
    parameters: [
      { name: 'number', type: 'NUMBER' },
      { name: 'decimals', type: 'NUMBER', optional: true },
    ],
    returnType: 'NUMBER',
    example: 'SELECT TRUNC(15.678, 2) AS truncated_value FROM DUAL;',
  },
  {
    name: 'WIDTH_BUCKET',
    description: '将数值映射到指定范围内的分桶中。',
    parameters: [
      { name: 'expr', type: 'NUMBER' },
      { name: 'min_value', type: 'NUMBER' },
      { name: 'max_value', type: 'NUMBER' },
      { name: 'num_buckets', type: 'NUMBER' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT WIDTH_BUCKET(5, 0, 10, 5) AS bucket_number FROM DUAL;',
  },
];

const String_Functions: IFunction[] = [
  {
    name: 'CHR',
    description: '返回对应于指定ASCII码值的字符。',
    parameters: [{ name: 'number', type: 'NUMBER', description: 'ASCII码值。' }],
    returnType: 'VARCHAR',
    example: 'SELECT CHR(65) AS character FROM DUAL;',
  },
  {
    name: 'CONCAT',
    description: '连接两个字符串。',
    parameters: [
      { name: 'string1', type: 'VARCHAR', description: '第一个字符串。' },
      { name: 'string2', type: 'VARCHAR', description: '第二个字符串。' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT CONCAT('Hello', ' World') AS concatenated_string FROM DUAL;",
  },
  {
    name: 'INITCAP',
    description: '将字符串的每个单词的首字母大写。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
    example: "SELECT INITCAP('oracle database') AS capitalized_string FROM DUAL;",
  },
  {
    name: 'LOWER',
    description: '将字符串转换为小写。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
    example: "SELECT LOWER('Oracle Database') AS lowercase_string FROM DUAL;",
  },
  {
    name: 'LPAD',
    description: '在字符串左侧填充指定字符，使其达到指定长度。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'length', type: 'NUMBER', description: '填充后的总长度。' },
      { name: 'pad_string', type: 'VARCHAR', description: '用于填充的字符串，默认为空格。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT LPAD('123', 5, '0') AS padded_string FROM DUAL;",
  },
  {
    name: 'LTRIM',
    description: '删除字符串左侧的空格或指定字符。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'trim_string', type: 'VARCHAR', description: '要删除的字符，默认为空格。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT LTRIM('  Oracle', ' ') AS trimmed_string FROM DUAL;",
  },
  {
    name: 'NCHR',
    description: '返回对应于指定国家字符集代码的字符。',
    parameters: [{ name: 'number', type: 'NUMBER', description: '国家字符集代码。' }],
    returnType: 'VARCHAR',
    example: 'SELECT NCHR(233) AS national_character FROM DUAL;',
  },
  {
    name: 'NLS_INITCAP',
    description: '将字符串的每个单词的首字母大写，基于NLS（国家语言支持）设置。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
    example: "SELECT NLS_INITCAP('oracle database') AS nls_capitalized_string FROM DUAL;",
  },
  {
    name: 'NLS_LOWER',
    description: '将字符串转换为小写，基于NLS（国家语言支持）设置。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
    example: "SELECT NLS_LOWER('Oracle Database') AS nls_lowercase_string FROM DUAL;",
  },
  {
    name: 'NLS_UPPER',
    description: '将字符串转换为大写，基于NLS（国家语言支持）设置。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
    example: "SELECT NLS_UPPER('Oracle Database') AS nls_uppercase_string FROM DUAL;",
  },
  {
    name: 'NLSSORT',
    description: '返回用于排序的字符串转换结果，基于NLS（国家语言支持）设置。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '要排序的字符串。' },
      { name: 'nls_sort', type: 'VARCHAR', description: 'NLS排序参数。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT NLSSORT('Oracle', 'NLS_SORT=BINARY') AS sorted_value FROM DUAL;",
  },
  {
    name: 'REGEXP_REPLACE',
    description: '使用正则表达式替换字符串中的子字符串。',
    parameters: [
      { name: 'source_string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'pattern', type: 'VARCHAR', description: '要匹配的正则表达式模式。' },
      { name: 'replace_string', type: 'VARCHAR', description: '用于替换的字符串。' },
      { name: 'position', type: 'NUMBER', description: '开始搜索的位置。', optional: true },
      { name: 'occurrence', type: 'NUMBER', description: '要替换的匹配项出现次数。', optional: true },
      { name: 'match_parameter', type: 'VARCHAR', description: '匹配行为的参数。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT REGEXP_REPLACE('Hello World', 'World', 'Oracle') AS replaced_string FROM DUAL;",
  },
  {
    name: 'REGEXP_SUBSTR',
    description: '使用正则表达式从字符串中提取子字符串。',
    parameters: [
      { name: 'source_string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'pattern', type: 'VARCHAR', description: '要匹配的正则表达式模式。' },
      { name: 'position', type: 'NUMBER', description: '开始搜索的位置。', optional: true },
      { name: 'occurrence', type: 'NUMBER', description: '匹配项的出现次数。', optional: true },
      { name: 'match_parameter', type: 'VARCHAR', description: '匹配行为的参数。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT REGEXP_SUBSTR('Hello Oracle World', 'Oracle') AS substring FROM DUAL;",
  },
  {
    name: 'REPLACE',
    description: '用新的子字符串替换字符串中的子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'search_string', type: 'VARCHAR', description: '要替换的子字符串。' },
      { name: 'replace_string', type: 'VARCHAR', description: '用于替换的字符串。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT REPLACE('Hello World', 'World', 'Oracle') AS replaced_string FROM DUAL;",
  },
  {
    name: 'RPAD',
    description: '在字符串右侧填充指定字符，使其达到指定长度。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'length', type: 'NUMBER', description: '填充后的总长度。' },
      { name: 'pad_string', type: 'VARCHAR', description: '用于填充的字符串，默认为空格。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT RPAD('123', 5, '0') AS padded_string FROM DUAL;",
  },
  {
    name: 'RTRIM',
    description: '删除字符串右侧的空格或指定字符。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'trim_string', type: 'VARCHAR', description: '要删除的字符，默认为空格。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT RTRIM('Oracle   ', ' ') AS trimmed_string FROM DUAL;",
  },
  {
    name: 'SOUNDEX',
    description: '返回字符串的SOUNDEX代码，用于进行语音匹配。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
    example: "SELECT SOUNDEX('Oracle') AS soundex_code FROM DUAL;",
  },
  {
    name: 'SUBSTR',
    description: '从字符串中提取子字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'start_position', type: 'NUMBER', description: '子字符串的起始位置。' },
      { name: 'length', type: 'NUMBER', description: '子字符串的长度。', optional: true },
    ],
    returnType: 'VARCHAR',
    example: "SELECT SUBSTR('Oracle Database', 1, 6) AS substring FROM DUAL;",
  },
  {
    name: 'TRANSLATE',
    description: '将字符串中的字符转换为其他字符。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'from_string', type: 'VARCHAR', description: '包含要转换的字符。' },
      { name: 'to_string', type: 'VARCHAR', description: '包含对应的新字符。' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT TRANSLATE('abc', 'abc', '123') AS translated_string FROM DUAL;",
  },
  {
    name: 'TRANSLATE',
    description: '使用指定的字符集转换字符串。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'character_set', type: 'VARCHAR', description: '用于转换的字符集。' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT TRANSLATE('Oracle', USING 'NCHAR_CS') AS translated_string FROM DUAL;",
  },
  {
    name: 'TRIM',
    description: '删除字符串两侧的空格或指定字符。',
    parameters: [
      { name: 'trim_character', type: 'VARCHAR', description: '要删除的字符。', optional: true },
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
    ],
    returnType: 'VARCHAR',
    example: "SELECT TRIM(' ' FROM ' Oracle ') AS trimmed_string FROM DUAL;",
  },
  {
    name: 'UPPER',
    description: '将字符串转换为大写。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
    example: "SELECT UPPER('oracle database') AS uppercase_string FROM DUAL;",
  },
  {
    name: 'ASCII',
    description: '返回字符的ASCII码值。',
    parameters: [{ name: 'character', type: 'VARCHAR', description: '要获取ASCII码的字符。' }],
    returnType: 'NUMBER',
    example: "SELECT ASCII('A') AS ascii_value FROM DUAL;",
  },
  {
    name: 'INSTR',
    description: '返回子字符串在字符串中出现的位置。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'substring', type: 'VARCHAR', description: '要查找的子字符串。' },
      { name: 'start_position', type: 'NUMBER', description: '开始搜索的位置，默认为1。', optional: true },
      { name: 'occurrence', type: 'NUMBER', description: '指定要查找的出现次数，默认为1。', optional: true },
    ],
    returnType: 'NUMBER',
    example: "SELECT INSTR('Oracle Database', 'a') AS position FROM DUAL;",
  },
  {
    name: 'LENGTH',
    description: '返回字符串的长度。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要计算长度的字符串。' }],
    returnType: 'NUMBER',
    example: "SELECT LENGTH('Oracle Database') AS length_value FROM DUAL;",
  },
  {
    name: 'REGEXP_COUNT',
    description: '返回正则表达式模式在字符串中出现的次数。',
    parameters: [
      { name: 'source_string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'pattern', type: 'VARCHAR', description: '正则表达式模式。' },
      { name: 'position', type: 'NUMBER', description: '开始搜索的位置，默认为1。', optional: true },
      { name: 'match_parameter', type: 'VARCHAR', description: '匹配行为的参数。', optional: true },
    ],
    returnType: 'NUMBER',
    example: "SELECT REGEXP_COUNT('Oracle Database', 'a') AS count_value FROM DUAL;",
  },
  {
    name: 'REGEXP_INSTR',
    description: '返回正则表达式模式在字符串中首次出现的位置。',
    parameters: [
      { name: 'source_string', type: 'VARCHAR', description: '原字符串。' },
      { name: 'pattern', type: 'VARCHAR', description: '正则表达式模式。' },
      { name: 'position', type: 'NUMBER', description: '开始搜索的位置，默认为1。', optional: true },
      { name: 'occurrence', type: 'NUMBER', description: '指定要查找的出现次数，默认为1。', optional: true },
      {
        name: 'return_option',
        type: 'NUMBER',
        description: '指定返回匹配位置还是匹配后的第一个字符位置。',
        optional: true,
      },
      { name: 'match_parameter', type: 'VARCHAR', description: '匹配行为的参数。', optional: true },
    ],
    returnType: 'NUMBER',
    example: "SELECT REGEXP_INSTR('Oracle Database', 'a', 1, 1, 0) AS instr_value FROM DUAL;",
  },
];

const String_Collection_Functions: IFunction[] = [
  {
    name: 'NLS_CHARSET_DECL_LEN',
    description: '返回字符在指定字符集中的声明长度。',
    parameters: [
      { name: 'expression', type: 'VARCHAR', description: '包含要计算长度的字符串表达式。' },
      { name: 'charset_id', type: 'NUMBER', description: '字符集的ID。' },
    ],
    returnType: 'NUMBER',
    example: "SELECT NLS_CHARSET_DECL_LEN('Hello', NLS_CHARSET_ID('AL32UTF8')) AS decl_length FROM DUAL;",
  },
  {
    name: 'NLS_CHARSET_ID',
    description: '返回指定字符集名称的字符集ID。',
    parameters: [{ name: 'charset_name', type: 'VARCHAR', description: '字符集的名称。' }],
    returnType: 'NUMBER',
    example: "SELECT NLS_CHARSET_ID('AL32UTF8') AS charset_id FROM DUAL;",
  },
  {
    name: 'NLS_CHARSET_NAME',
    description: '返回指定字符集ID的字符集名称。',
    parameters: [{ name: 'charset_id', type: 'NUMBER', description: '字符集的ID。' }],
    returnType: 'VARCHAR',
    example: 'SELECT NLS_CHARSET_NAME(873) AS charset_name FROM DUAL;',
  },
];

const Sort_Functions: IFunction[] = [
  {
    name: 'COLLATION',
    description: '返回表达式的排序设置。',
    parameters: [{ name: 'expression', type: 'VARCHAR', description: '要获取排序设置的字符串表达式。' }],
    returnType: 'VARCHAR',
    example: "SELECT COLLATION('Hello') AS collation_setting FROM DUAL;",
  },
  {
    name: 'NLS_COLLATION_ID',
    description: '返回指定排序名称的排序ID。',
    parameters: [{ name: 'collation_name', type: 'VARCHAR', description: '排序的名称。' }],
    returnType: 'NUMBER',
    example: "SELECT NLS_COLLATION_ID('BINARY') AS collation_id FROM DUAL;",
  },
  {
    name: 'NLS_COLLATION_NAME',
    description: '返回指定排序ID的排序名称。',
    parameters: [{ name: 'collation_id', type: 'NUMBER', description: '排序的ID。' }],
    returnType: 'VARCHAR',
    example: 'SELECT NLS_COLLATION_NAME(128) AS collation_name FROM DUAL;',
  },
];

const Date_Functions: IFunction[] = [
  {
    name: 'ADD_MONTHS',
    description: '向指定日期添加指定的月份数。',
    parameters: [
      { name: 'date', type: 'DATE', description: '要添加月份的日期。' },
      { name: 'months', type: 'NUMBER', description: '要添加的月份数。' },
    ],
    returnType: 'DATE',
    example: 'SELECT ADD_MONTHS(SYSDATE, 3) AS new_date FROM DUAL;',
  },
  {
    name: 'CURRENT_DATE',
    description: '返回会话的当前日期。',
    parameters: [],
    returnType: 'DATE',
    example: 'SELECT CURRENT_DATE AS current_date FROM DUAL;',
  },
  {
    name: 'CURRENT_TIMESTAMP',
    description: '返回当前会话时区的日期和时间，包括时区。',
    parameters: [],
    returnType: 'TIMESTAMP WITH TIME ZONE',
    example: 'SELECT CURRENT_TIMESTAMP AS current_timestamp FROM DUAL;',
  },
  {
    name: 'DBTIMEZONE',
    description: '返回数据库时区。',
    parameters: [],
    returnType: 'VARCHAR',
    example: 'SELECT DBTIMEZONE AS db_timezone FROM DUAL;',
  },
  {
    name: 'EXTRACT',
    description: '从日期或间隔值中提取指定的日期部分。',
    parameters: [
      { name: 'component', type: 'VARCHAR', description: '要提取的部分（如 YEAR, MONTH）。' },
      { name: 'source', type: 'DATE|TIMESTAMP', description: '日期或时间戳值。' },
    ],
    returnType: 'NUMBER',
    example: 'SELECT EXTRACT(YEAR FROM SYSDATE) AS year FROM DUAL;',
  },
  {
    name: 'FROM_TZ',
    description: '将TIMESTAMP值与时区结合并返回TIMESTAMP WITH TIME ZONE值。',
    parameters: [
      { name: 'timestamp', type: 'TIMESTAMP', description: '时间戳值。' },
      { name: 'timezone', type: 'VARCHAR', description: '时区。' },
    ],
    returnType: 'TIMESTAMP WITH TIME ZONE',
    example: "SELECT FROM_TZ(TIMESTAMP '2024-08-01 10:00:00', 'UTC') AS ts_with_tz FROM DUAL;",
  },
  {
    name: 'LAST_DAY',
    description: '返回指定日期所在月份的最后一天。',
    parameters: [{ name: 'date', type: 'DATE', description: '日期。' }],
    returnType: 'DATE',
    example: 'SELECT LAST_DAY(SYSDATE) AS last_day FROM DUAL;',
  },
  {
    name: 'LOCALTIMESTAMP',
    description: '返回当前会话时区的日期和时间，不包含时区。',
    parameters: [],
    returnType: 'TIMESTAMP',
    example: 'SELECT LOCALTIMESTAMP AS local_timestamp FROM DUAL;',
  },
  {
    name: 'MONTHS_BETWEEN',
    description: '返回两个日期之间的月份数。',
    parameters: [
      { name: 'date1', type: 'DATE', description: '第一个日期。' },
      { name: 'date2', type: 'DATE', description: '第二个日期。' },
    ],
    returnType: 'NUMBER',
    example: "SELECT MONTHS_BETWEEN(SYSDATE, DATE '2024-01-01') AS months_between FROM DUAL;",
  },
  {
    name: 'NEW_TIME',
    description: '将日期从一个时区转换为另一个时区。',
    parameters: [
      { name: 'date', type: 'DATE', description: '原始日期。' },
      { name: 'from_timezone', type: 'VARCHAR', description: '原时区。' },
      { name: 'to_timezone', type: 'VARCHAR', description: '目标时区。' },
    ],
    returnType: 'DATE',
    example: "SELECT NEW_TIME(SYSDATE, 'EST', 'PST') AS new_time FROM DUAL;",
  },
  {
    name: 'NEXT_DAY',
    description: '返回指定日期之后的下一个指定工作日。',
    parameters: [
      { name: 'date', type: 'DATE', description: '起始日期。' },
      { name: 'weekday', type: 'VARCHAR', description: "工作日名称（如 'MONDAY', 'TUESDAY'）。" },
    ],
    returnType: 'DATE',
    example: "SELECT NEXT_DAY(SYSDATE, 'MONDAY') AS next_monday FROM DUAL;",
  },
  {
    name: 'NUMTODSINTERVAL',
    description: '将数字转换为间隔类型INTERVAL DAY TO SECOND。',
    parameters: [
      { name: 'number', type: 'NUMBER', description: '数值。' },
      { name: 'unit', type: 'VARCHAR', description: "单位（如 'DAY', 'HOUR', 'MINUTE', 'SECOND'）。" },
    ],
    returnType: 'INTERVAL DAY TO SECOND',
    example: "SELECT NUMTODSINTERVAL(10, 'DAY') AS interval_value FROM DUAL;",
  },
  {
    name: 'NUMTOYMINTERVAL',
    description: '将数字转换为间隔类型INTERVAL YEAR TO MONTH。',
    parameters: [
      { name: 'number', type: 'NUMBER', description: '数值。' },
      { name: 'unit', type: 'VARCHAR', description: "单位（如 'YEAR', 'MONTH'）。" },
    ],
    returnType: 'INTERVAL YEAR TO MONTH',
    example: "SELECT NUMTOYMINTERVAL(1, 'YEAR') AS interval_value FROM DUAL;",
  },
  {
    name: 'ORA_DST_AFFECTED',
    description: '检查日期时间是否受到当前时间段的夏令时影响。',
    parameters: [{ name: 'date', type: 'DATE', description: '日期时间值。' }],
    returnType: 'VARCHAR',
    example: "SELECT ORA_DST_AFFECTED(TIMESTAMP '2024-03-10 02:00:00') AS dst_affected FROM DUAL;",
  },
  {
    name: 'ORA_DST_CONVERT',
    description: '将日期时间从标准时间转换为夏令时，或相反。',
    parameters: [{ name: 'timestamp', type: 'TIMESTAMP', description: '时间戳值。' }],
    returnType: 'TIMESTAMP WITH TIME ZONE',
    example: "SELECT ORA_DST_CONVERT(TIMESTAMP '2024-03-10 02:00:00') AS dst_converted FROM DUAL;",
  },
  {
    name: 'ORA_DST_ERROR',
    description: '检查日期时间是否存在DST（夏令时）错误。',
    parameters: [{ name: 'date', type: 'DATE', description: '日期时间值。' }],
    returnType: 'VARCHAR',
    example: "SELECT ORA_DST_ERROR(TIMESTAMP '2024-03-10 02:00:00') AS dst_error FROM DUAL;",
  },
  {
    name: 'ROUND',
    description: '将日期四舍五入到指定的时间单位。',
    parameters: [
      { name: 'date', type: 'DATE', description: '要四舍五入的日期。' },
      { name: 'format', type: 'VARCHAR', description: "四舍五入的时间单位（如 'MONTH', 'YEAR'）。", optional: true },
    ],
    returnType: 'DATE',
    example: "SELECT ROUND(SYSDATE, 'MONTH') AS rounded_date FROM DUAL;",
  },
  {
    name: 'SESSIONTIMEZONE',
    description: '返回当前会话的时区。',
    parameters: [],
    returnType: 'VARCHAR',
    example: 'SELECT SESSIONTIMEZONE AS session_tz FROM DUAL;',
  },
  {
    name: 'SYS_EXTRACT_UTC',
    description: '将带有时区的时间戳转换为UTC时间。',
    parameters: [{ name: 'timestamp', type: 'TIMESTAMP WITH TIME ZONE', description: '带有时区的时间戳。' }],
    returnType: 'TIMESTAMP',
    example: 'SELECT SYS_EXTRACT_UTC(SYSTIMESTAMP) AS utc_time FROM DUAL;',
  },
  {
    name: 'SYSDATE',
    description: '返回当前系统日期和时间。',
    parameters: [],
    returnType: 'DATE',
    example: 'SELECT SYSDATE AS current_date FROM DUAL;',
  },
  {
    name: 'SYSTIMESTAMP',
    description: '返回当前系统时间戳，包括时区。',
    parameters: [],
    returnType: 'TIMESTAMP WITH TIME ZONE',
    example: 'SELECT SYSTIMESTAMP AS current_timestamp FROM DUAL;',
  },
  {
    name: 'TO_DSINTERVAL',
    description: '将字符串转换为间隔类型INTERVAL DAY TO SECOND。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '表示间隔的字符串。' }],
    returnType: 'INTERVAL DAY TO SECOND',
    example: "SELECT TO_DSINTERVAL('5 04:12:10') AS interval_value FROM DUAL;",
  },
  {
    name: 'TO_TIMESTAMP',
    description: '将字符串转换为时间戳。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '要转换的字符串。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'TIMESTAMP',
    example: "SELECT TO_TIMESTAMP('2024-08-01 10:00:00', 'YYYY-MM-DD HH24:MI:SS') AS timestamp_value FROM DUAL;",
  },
  {
    name: 'TO_TIMESTAMP_TZ',
    description: '将字符串转换为带时区的时间戳。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '要转换的字符串。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'TIMESTAMP WITH TIME ZONE',
    example:
      "SELECT TO_TIMESTAMP_TZ('2024-08-01 10:00:00 UTC', 'YYYY-MM-DD HH24:MI:SS TZR') AS timestamp_tz_value FROM DUAL;",
  },
  {
    name: 'TO_YMINTERVAL',
    description: '将字符串转换为间隔类型INTERVAL YEAR TO MONTH。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '表示间隔的字符串。' }],
    returnType: 'INTERVAL YEAR TO MONTH',
    example: "SELECT TO_YMINTERVAL('1-2') AS interval_value FROM DUAL;",
  },
  {
    name: 'TRUNC',
    description: '将日期截断到指定的时间单位。',
    parameters: [
      { name: 'date', type: 'DATE', description: '要截断的日期。' },
      { name: 'format', type: 'VARCHAR', description: "截断的时间单位（如 'MONTH', 'YEAR'）。", optional: true },
    ],
    returnType: 'DATE',
    example: "SELECT TRUNC(SYSDATE, 'MONTH') AS truncated_date FROM DUAL;",
  },
  {
    name: 'TZ_OFFSET',
    description: '返回指定时区的时区偏移量。',
    parameters: [{ name: 'timezone', type: 'VARCHAR', description: '时区名称。' }],
    returnType: 'VARCHAR',
    example: "SELECT TZ_OFFSET('America/New_York') AS tz_offset FROM DUAL;",
  },
];

const Compare_Functions: IFunction[] = [
  {
    name: 'GREATEST',
    description: '返回一组表达式中最大的值。',
    parameters: [{ name: 'expr', type: 'any*', description: '要比较的值列表。' }],
    example: 'SELECT GREATEST(10, 20, 5) AS greatest_value FROM DUAL;',
    returnType: 'Typeof(1)',
  },
  {
    name: 'LEAST',
    description: '返回一组表达式中最小的值。',
    parameters: [{ name: 'expr', type: 'any*', description: '要比较的值列表。' }],
    example: 'SELECT LEAST(10, 20, 5) AS least_value FROM DUAL;',
    returnType: 'Typeof(1)',
  },
];

const Change_Functions: IFunction[] = [
  {
    name: 'ASCIISTR',
    description: '将字符串转换为ASCII字符串，其中非ASCII字符被转义为\\XXXX格式的Unicode。',
    parameters: [{ name: 'char', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'BIN_TO_NUM',
    description: '将二进制值转换为数字。',
    parameters: [{ name: 'expr', type: 'NUMBER*', description: '二进制位值。' }],
    example: 'SELECT BIN_TO_NUM(1, 0, 1) AS num_value FROM DUAL;',
    returnType: 'NUMBER',
  },
  {
    name: 'CAST',
    description: '将一种数据类型转换为另一种数据类型。',
    parameters: [
      { name: 'expression', type: 'ANY', description: '要转换的表达式。' },
      { name: 'datatype', type: 'VARCHAR', description: '目标数据类型。' },
    ],
    example: "SELECT CAST('123' AS NUMBER) AS num_value FROM DUAL;",
    returnType: 'Typeof(2)',
  },
  {
    name: 'CHARTOROWID',
    description: '将字符串转换为ROWID类型。',
    parameters: [{ name: 'char', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'NUMBER',
  },
  {
    name: 'COMPOSE',
    description: '将字符串转换为标准格式的组合Unicode字符串。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'CONVERT',
    description: '将字符串从一个字符集转换为另一个字符集。',
    parameters: [
      { name: 'char', type: 'VARCHAR', description: '要转换的字符串。' },
      { name: 'to_charset', type: 'VARCHAR', description: '目标字符集。' },
      { name: 'from_charset', type: 'VARCHAR', description: '源字符集。', optional: true },
    ],
    returnType: 'VARCHAR',
  },
  {
    name: 'DECOMPOSE',
    description: '将组合字符分解为基字符和组合字符的序列。',
    parameters: [{ name: 'char', type: 'VARCHAR', description: '要分解的字符串。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'HEXTORAW',
    description: '将十六进制字符串转换为RAW类型。',
    parameters: [{ name: 'hex_string', type: 'VARCHAR', description: '十六进制字符串。' }],
    returnType: 'NUMBER',
  },
  {
    name: 'NUMTODSINTERVAL',
    description: '将数字转换为间隔类型INTERVAL DAY TO SECOND。',
    parameters: [
      { name: 'number', type: 'NUMBER', description: '数值。' },
      { name: 'unit', type: 'VARCHAR', description: "单位（如 'DAY', 'HOUR', 'MINUTE', 'SECOND'）。" },
    ],
    returnType: 'VARCHAR',
  },
  {
    name: 'NUMTOYMINTERVAL',
    description: '将数字转换为间隔类型INTERVAL YEAR TO MONTH。',
    parameters: [
      { name: 'number', type: 'NUMBER', description: '数值。' },
      { name: 'unit', type: 'VARCHAR', description: "单位（如 'YEAR', 'MONTH'）。" },
    ],
    returnType: 'VARCHAR',
  },
  {
    name: 'RAWTOHEX',
    description: '将RAW类型转换为十六进制字符串。',
    parameters: [{ name: 'raw', type: 'NUMBER', description: '要转换的RAW值。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'RAWTONHEX',
    description: '将RAW类型转换为带前导零的十六进制字符串。',
    parameters: [{ name: 'raw', type: 'NUMBER', description: '要转换的RAW值。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'ROWIDTOCHAR',
    description: '将ROWID类型转换为字符串。',
    parameters: [{ name: 'rowid', type: 'NUMBER', description: '要转换的ROWID值。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'ROWIDTONCHAR',
    description: '将ROWID类型转换为国家字符集中的字符串。',
    parameters: [{ name: 'rowid', type: 'ROWID', description: '要转换的ROWID值。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'SCN_TO_TIMESTAMP',
    description: '将系统更改号（SCN）转换为时间戳。',
    parameters: [{ name: 'scn', type: 'NUMBER', description: '系统更改号。' }],
    returnType: 'TIMESTAMP',
  },
  {
    name: 'TIMESTAMP_TO_SCN',
    description: '将时间戳转换为系统更改号（SCN）。',
    parameters: [{ name: 'timestamp', type: 'TIMESTAMP', description: '时间戳值。' }],
    returnType: 'NUMBER',
  },
  {
    name: 'TO_BINARY_DOUBLE',
    description: '将表达式转换为BINARY_DOUBLE类型。',
    parameters: [{ name: 'expression', type: 'ANY', description: '要转换的表达式。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_BINARY_FLOAT',
    description: '将表达式转换为BINARY_FLOAT类型。',
    parameters: [{ name: 'expression', type: 'ANY', description: '要转换的表达式。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_BLOB',
    description: '将BFILE数据转换为BLOB类型。',
    parameters: [{ name: 'bfile', type: 'BFILE', description: '要转换的BFILE。' }],
    returnType: 'NUMBER',
  },
  {
    name: 'TO_CHAR',
    description: '将数字转换为字符串。',
    parameters: [{ name: 'nchar', type: 'VARCHAR', description: '要转换的数字。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_CHAR',
    description: '将数字转换为字符串。',
    parameters: [
      { name: 'number', type: 'NUMBER', description: '要转换的数字。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_CHAR',
    description: '将日期或时间戳转换为字符串。',
    parameters: [
      { name: 'date', type: 'TIMESTAMP|INTERVAL', description: '要转换的日期或时间戳。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_CLOB',
    description: '将字符数据转换为CLOB类型。',
    parameters: [{ name: 'char', type: 'CHAR|VARCHAR|NCHAR|NVARCHAR', description: '要转换的字符数据。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_DATE',
    description: '将字符串转换为日期。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '要转换的字符串。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'DATE',
  },
  {
    name: 'TO_DSINTERVAL',
    description: '将字符串转换为间隔类型INTERVAL DAY TO SECOND。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '表示间隔的字符串。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_LOB',
    description: '将LONG数据类型转换为LOB数据类型。',
    parameters: [{ name: 'long', type: 'LONG', description: '要转换的LONG数据。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_MULTI_BYTE',
    description: '将字符数据转换为多字节格式。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_NCHAR',
    description: '将字符数据转换为NCHAR类型。',
    parameters: [{ name: 'varchar', type: 'VARCHAR|TIMESTAMP|NUMBER|INTERVAL', description: '要转换的字符数据。' }],
    returnType: 'Typeof(1)',
  },
  {
    name: 'TO_NCLOB',
    description: '将字符数据转换为NCLOB类型。',
    parameters: [{ name: 'char', type: 'VARCHAR', description: '要转换的字符数据。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_NUMBER',
    description: '将字符串转换为数字。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '要转换的字符串。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'NUMBER',
  },
  {
    name: 'TO_SINGLE_BYTE',
    description: '将字符数据转换为单字节格式。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '要转换的字符串。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TO_TIMESTAMP',
    description: '将字符串转换为时间戳。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '要转换的字符串。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'TIMESTAMP',
  },
  {
    name: 'TO_TIMESTAMP_TZ',
    description: '将字符串转换为带时区的时间戳。',
    parameters: [
      { name: 'string', type: 'VARCHAR', description: '要转换的字符串。' },
      { name: 'format', type: 'VARCHAR', description: '格式化模式。', optional: true },
    ],
    returnType: 'TIMESTAMP',
  },
  {
    name: 'TO_YMINTERVAL',
    description: '将字符串转换为间隔类型INTERVAL YEAR TO MONTH。',
    parameters: [{ name: 'char', type: 'VARCHAR', description: '表示间隔的字符串。' }],
    returnType: 'VARCHAR',
  },
  {
    name: 'TREAT',
    description: '以指定的数据类型对表达式进行处理。',
    parameters: [
      { name: 'expression', type: 'ANY', description: '要处理的表达式。' },
      { name: 'datatype', type: 'VARCHAR', description: '数据类型。' },
    ],
    returnType: 'VARCHAR',
  },
  {
    name: 'UNISTR',
    description: '将Unicode码点序列转换为字符串。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '包含Unicode转义序列的字符串。' }],
    returnType: 'VARCHAR',
  },
];

const BigObject_Functions: IFunction[] = [
  {
    name: 'BFILENAME',
    description: '创建一个BFILE类型，表示文件系统中的二进制文件。',
    parameters: [
      { name: 'directory', type: 'VARCHAR', description: '目录对象名称。' },
      { name: 'filename', type: 'VARCHAR', description: '文件名称。' },
    ],
    example: "SELECT BFILENAME('MY_DIR', 'myfile.dat') AS bfile_value FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'EMPTY_BLOB',
    description: '返回一个初始化为空的BLOB。',
    parameters: [],
    example: 'INSERT INTO my_table (blob_column) VALUES (EMPTY_BLOB());',
    returnType: 'VARCHAR',
  },
  {
    name: 'EMPTY_CLOB',
    description: '返回一个初始化为空的CLOB。',
    parameters: [],
    example: 'INSERT INTO my_table (clob_column) VALUES (EMPTY_CLOB());',
    returnType: 'VARCHAR',
  },
];

const Common_Functions: IFunction[] = [
  {
    name: 'CARDINALITY',
    description: '返回嵌套表或VARRAY中的元素数量。',
    parameters: [{ name: 'collection', type: 'reference/TABLE', description: '要计算元素数量的集合。' }],
    example:
      'SELECT CARDINALITY(CAST(MULTISET(SELECT department_id FROM employees) AS SYS.ODCINUMBERLIST)) AS num_elements FROM DUAL;',
    returnType: 'VARCHAR',
  },
  {
    name: 'COLLECT',
    description: '将查询结果聚合为一个集合。',
    parameters: [{ name: 'expression', type: 'ANY', description: '要聚合的表达式。' }],
    example: 'SELECT COLLECT(department_id) AS department_ids FROM employees;',
    returnType: 'VARCHAR',
  },
  {
    name: 'POWERMULTISET',
    description: '返回集合的幂集。',
    parameters: [{ name: 'collection', type: 'reference/TABLE', description: '要计算幂集的集合。' }],
    example:
      'SELECT POWERMULTISET(CAST(MULTISET(SELECT department_id FROM employees) AS SYS.ODCINUMBERLIST)) AS power_set FROM DUAL;',
    returnType: 'table',
  },
  {
    name: 'POWERMULTISET_BY_CARDINALITY',
    description: '返回集合的幂集中具有指定基数的子集。',
    parameters: [
      { name: 'collection', type: 'reference/TABLE', description: '要计算幂集的集合。' },
      { name: 'cardinality', type: 'NUMBER', description: '指定的基数。' },
    ],
    example:
      'SELECT POWERMULTISET_BY_CARDINALITY(CAST(MULTISET(SELECT department_id FROM employees) AS SYS.ODCINUMBERLIST), 2) AS subsets FROM DUAL;',
    returnType: 'table',
  },
  {
    name: 'SET',
    description: '将集合中的元素去重。',
    parameters: [{ name: 'collection', type: 'reference/TABLE', description: '要去重的集合。' }],
    example:
      'SELECT SET(CAST(MULTISET(SELECT department_id FROM employees) AS SYS.ODCINUMBERLIST)) AS distinct_elements FROM DUAL;',
    returnType: 'table',
  },
];

const XML_Functions: IFunction[] = [
  {
    name: 'DEPTH',
    description: '返回XML文档中节点的深度。',
    parameters: [{ name: 'xml_expression', type: 'XMLType', description: '要检查的XML文档或片段。' }],
    example: 'SELECT DEPTH(xml_data) AS node_depth FROM my_table;',
    returnType: 'NUMBER',
  },
  {
    name: 'EXISTSNODE',
    description: '检查XML文档中是否存在匹配的节点。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要检查的XML文档或片段。' },
      { name: 'Xpath_string', type: 'VARCHAR', description: '指定节点路径的XPath表达式。' },
    ],
    example: "SELECT EXISTSNODE(xml_data, '/book/title') AS node_exists FROM my_table;",
    returnType: 'VARCHAR',
  },
  {
    name: 'EXTRACT',
    description: '从XML文档中提取匹配节点。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要从中提取数据的XML文档或片段。' },
      { name: 'Xpath_string', type: 'VARCHAR', description: '指定节点路径的XPath表达式。' },
    ],
    example: "SELECT EXTRACT(xml_data, '/book/title') AS extracted_data FROM my_table;",
    returnType: 'VARCHAR',
  },
  {
    name: 'EXTRACTVALUE',
    description: '提取并返回XML文档中匹配节点的文本值。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要从中提取数据的XML文档或片段。' },
      { name: 'Xpath_string', type: 'VARCHAR', description: '指定节点路径的XPath表达式。' },
    ],
    example: "SELECT EXTRACTVALUE(xml_data, '/book/title') AS title FROM my_table;",
    returnType: 'VARCHAR',
  },
  {
    name: 'PATH',
    description: '返回XML文档中指定路径的节点。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要从中提取数据的XML文档或片段。' },
      { name: 'Xpath_string', type: 'VARCHAR', description: '指定节点路径的XPath表达式。' },
    ],
    example: "SELECT PATH(xml_data, '/book/title') AS node_path FROM my_table;",
    returnType: 'VARCHAR',
  },
  {
    name: 'SYS_DBURIGEN',
    description: '生成数据库URI，引用数据库中存储的文档。',
    parameters: [{ name: 'value_expr', type: 'VARCHAR', description: '生成URI的值。' }],
    example: "SELECT SYS_DBURIGEN('/my_dir/my_file.xml') AS db_uri FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'SYS_XMLAGG',
    description: '聚合多个XML片段为一个XML片段。',
    parameters: [{ name: 'xml_expression', type: 'XMLType', description: '要聚合的XML文档或片段。' }],
    example: "SELECT SYS_XMLAGG(XMLELEMENT('book', title)) AS aggregated_xml FROM books;",
    returnType: 'VARCHAR',
  },
  {
    name: 'SYS_XMLGEN',
    description: '根据提供的查询生成XML数据。',
    parameters: [{ name: 'query', type: 'VARCHAR', description: '生成XML数据的查询。' }],
    example: 'SELECT SYS_XMLGEN(SELECT * FROM employees WHERE employee_id = 101) AS xml_data FROM DUAL;',
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLAGG',
    description: '将一组XML片段聚合为一个XML文档。',
    parameters: [{ name: 'xml_expression', type: 'XMLType', description: '要聚合的XML文档或片段。' }],
    example: "SELECT XMLAGG(XMLELEMENT('book', title)) AS aggregated_xml FROM books;",
    returnType: 'XMLType',
  },
  {
    name: 'XMLCAST',
    description: '将XMLType数据转换为SQL数据类型。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要转换的XML数据。' },
      { name: 'datatype', type: 'datetype', description: '目标数据类型。' },
    ],
    example: 'SELECT XMLCAST(CAST(xml_data AS VARCHAR(100))) AS text_data FROM my_table;',
    returnType: 'Typeof(2)',
  },
  {
    name: 'XMLCDATA',
    description: '在XML文档中创建一个CDATA部分。',
    parameters: [{ name: 'value_expr', type: 'VARCHAR', description: '要包含在CDATA部分中的文本。' }],
    example: "SELECT XMLELEMENT('note', XMLCDATA('This is a CDATA section')) AS cdata_example FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLCOLATTVAL',
    description: '将XML列的值作为属性值返回。',
    parameters: [{ name: 'column', type: 'VARCHAR', description: '包含XML数据的列。' }],
    example: 'SELECT XMLCOLATTVAL(xml_column) AS attr_value FROM my_table;',
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLCOMMENT',
    description: '在XML文档中创建注释节点。',
    parameters: [{ name: 'comment', type: 'VARCHAR', description: '注释内容。' }],
    example: "SELECT XMLELEMENT('note', XMLCOMMENT('This is a comment')) AS comment_example FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLCONCAT',
    description: '将多个XML片段连接成一个XML文档。',
    parameters: [{ name: 'XMLType_instance', type: 'VARCHAR*', description: '要连接的XML文档或片段。' }],
    example:
      "SELECT XMLCONCAT(XMLELEMENT('first', 'Hello'), XMLELEMENT('second', 'World')) AS concatenated_xml FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLDIFF',
    description: '返回两个XML片段之间的差异。',
    parameters: [
      { name: 'XMLType_document1', type: 'XMLType', description: '第一个XML文档或片段。' },
      { name: 'XMLType_document2', type: 'XMLType', description: '第二个XML文档或片段。' },
    ],
    example: 'SELECT XMLDIFF(xml_data1, xml_data2) AS xml_difference FROM my_table;',
    returnType: 'NUMBER',
  },
  {
    name: 'XMLELEMENT',
    description: '创建一个XML元素。',
    parameters: [
      { name: 'element_name', type: 'VARCHAR', description: '元素名称。' },
      { name: 'value_expr', type: 'ANY', description: '元素内容。', optional: true },
    ],
    example: "SELECT XMLELEMENT('greeting', 'Hello World') AS xml_element FROM DUAL;",
    returnType: 'NUMBER',
  },
  {
    name: 'XMLEXISTS',
    description: '检查XML数据中是否存在匹配的节点。',
    parameters: [
      { name: 'XQuery_string', type: 'VARCHAR', description: '指定节点路径的XQuery表达式。' },
      { name: 'xml_expression', type: 'XMLType', description: '要检查的XML文档或片段。' },
    ],
    example:
      'SELECT XMLEXISTS(\'declare default element namespace "http://example.org"; /bookstore/book/title\' PASSING xml_data) AS exists FROM my_table;',
    returnType: 'NUMBER',
  },
  {
    name: 'XMLFOREST',
    description: '将多个表达式转换为XML元素，并以平面结构返回。',
    parameters: [{ name: 'expression', type: 'ANY', description: '要转换为XML元素的表达式。' }],
    example: 'SELECT XMLFOREST(first_name AS "firstName", last_name AS "lastName") AS xml_forest FROM employees;',
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLISVALID',
    description: '检查XML数据是否有效。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要检查的XML文档或片段。' },
      { name: 'schema_url', type: 'VARCHAR', description: '用于验证的XML Schema的URL。', optional: true },
    ],
    example: "SELECT XMLISVALID(xml_data, 'http://example.org/schema.xsd') AS is_valid FROM my_table;",
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLPARSE',
    description: '将字符串解析为XMLType数据。',
    parameters: [{ name: 'string', type: 'VARCHAR', description: '包含XML数据的字符串。' }],
    example: "SELECT XMLPARSE(DOCUMENT '<book><title>XML Guide</title></book>') AS xml_data FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLPATCH',
    description: '对XML文档应用XML Patch更新。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要更新的XML文档。' },
      { name: 'patch_expression', type: 'XMLType', description: '包含XML Patch的文档。' },
    ],
    example: 'SELECT XMLPATCH(xml_data, patch_data) AS updated_xml FROM my_table;',
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLPI',
    description: '创建一个XML处理指令。',
    parameters: [
      { name: 'target', type: 'VARCHAR', description: '处理指令的目标。' },
      { name: 'value_expr', type: 'VARCHAR', description: '处理指令的内容。', optional: true },
    ],
    example:
      'SELECT XMLPI(NAME xml-stylesheet, \'type="text/xsl" href="style.xsl"\') AS processing_instruction FROM DUAL;',
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLQUERY',
    description: '执行XQuery并返回结果。',
    parameters: [
      { name: 'XQuery_string', type: 'VARCHAR', description: 'XQuery表达式。' },
      { name: 'xml_expression', type: 'XMLType', description: '要查询的XML文档或片段。' },
    ],
    example:
      'SELECT XMLQUERY(\'declare default element namespace "http://example.org"; /bookstore/book/title\' PASSING xml_data RETURNING CONTENT) AS query_result FROM my_table;',
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLROOT',
    description: '为XML文档设置根元素。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要设置根元素的XML文档。' },
      { name: 'version', type: 'VARCHAR', description: '根元素的版本信息。' },
      { name: 'standalone', type: 'VARCHAR', description: 'standalone属性值。', optional: true },
    ],
    example: "SELECT XMLROOT(xml_data, VERSION '1.0') AS rooted_xml FROM my_table;",
    returnType: 'NUMBER',
  },
  {
    name: 'XMLSEQUENCE',
    description: '将XML数据转换为一个序列。',
    parameters: [{ name: 'xml_expression', type: 'XMLType', description: '要转换的XML文档或片段。' }],
    example:
      "SELECT COLUMN_VALUE FROM XMLTABLE('/bookstore/book' PASSING xml_data COLUMNS COLUMN_VALUE XMLTYPE PATH '.') AS books;",
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLSERIALIZE',
    description: '将XMLType数据序列化为字符串。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要序列化的XML数据。' },
      { name: 'datatype', type: 'SQL数据类型', description: '输出字符串的数据类型。' },
    ],
    example: 'SELECT XMLSERIALIZE(DOCUMENT xml_data AS CLOB) AS serialized_xml FROM my_table;',
    returnType: 'VARCHAR',
  },
  {
    name: 'XMLTRANSFORM',
    description: '使用XSLT样式表转换XML文档。',
    parameters: [
      { name: 'xml_expression', type: 'XMLType', description: '要转换的XML文档。' },
      { name: 'xsl_expression', type: 'XMLType', description: 'XSLT样式表。' },
    ],
    example: 'SELECT XMLTRANSFORM(xml_data, xsl_data) AS transformed_xml FROM my_table;',
    returnType: 'NUMBER',
  },
];

const JSON_Functions: IFunction[] = [
  {
    name: 'JSON_QUERY',
    description: '从JSON数据中提取JSON对象或数组。',
    parameters: [
      { name: 'json_column', type: 'CLOB|BLOB|VARCHAR2', description: '包含JSON数据的列。' },
      { name: 'path', type: 'VARCHAR2', description: 'JSON路径表达式。' },
    ],
    example: "SELECT JSON_QUERY(json_data, '$.employee') AS employee_data FROM my_table;",
    returnType: 'any',
  },
  {
    name: 'JSON_TABLE',
    description: '将JSON数据转换为关系数据。',
    parameters: [
      { name: 'json_column', type: 'CLOB|BLOB|VARCHAR2', description: '包含JSON数据的列。' },
      { name: 'path', type: 'VARCHAR2', description: 'JSON路径表达式。' },
      { name: 'columns', type: '列定义', description: '要提取的列和路径。' },
    ],
    example:
      "SELECT * FROM JSON_TABLE(json_data, '$.employees[*]' COLUMNS (employee_id NUMBER PATH '$.id', employee_name VARCHAR2(100) PATH '$.name')) AS jt;",
    returnType: 'Table',
  },
  {
    name: 'JSON_VALUE',
    description: '从JSON数据中提取标量值。',
    parameters: [
      { name: 'json_column', type: 'CLOB|BLOB|VARCHAR2', description: '包含JSON数据的列。' },
      { name: 'path', type: 'VARCHAR2', description: 'JSON路径表达式。' },
    ],
    example: "SELECT JSON_VALUE(json_data, '$.employee.name') AS employee_name FROM my_table;",
    returnType: 'VARCHAR',
  },
  {
    name: 'JSON_ARRAY',
    description: '生成包含JSON值的JSON数组。',
    parameters: [{ name: 'value_expr1, value_expr2, ...', type: 'any', description: '要包含在JSON数组中的值。' }],
    example: "SELECT JSON_ARRAY(1, 'abc', 3.14) AS json_array FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'JSON_ARRAYAGG',
    description: '将一组值聚合为JSON数组。',
    parameters: [{ name: 'value_expr', type: 'any', description: '要聚合的值。' }],
    example: 'SELECT JSON_ARRAYAGG(employee_id) AS employee_ids FROM employees;',
    returnType: 'VARCHAR',
  },
  {
    name: 'JSON_OBJECT',
    description: '生成包含键值对的JSON对象。',
    parameters: [{ name: 'key1, value_expr1, key2, value_expr2, ...', type: 'VARCHAR2, any', description: '键值对。' }],
    example: "SELECT JSON_OBJECT('id' VALUE 1, 'name' VALUE 'John Doe') AS json_object FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'JSON_OBJECTAGG',
    description: '将一组键值对聚合为JSON对象。',
    parameters: [
      { name: 'key_expr', type: 'VARCHAR2', description: '键表达式。' },
      { name: 'value_expr', type: 'any', description: '值表达式。' },
    ],
    example: 'SELECT JSON_OBJECTAGG(employee_id VALUE employee_name) AS employee_map FROM employees;',
    returnType: 'VARCHAR',
  },
  {
    name: 'JSON_DATAGUIDE',
    description: '创建JSON数据指南，提供JSON数据结构的信息。',
    parameters: [{ name: 'json_column', type: 'CLOB|BLOB|VARCHAR2', description: '包含JSON数据的列。' }],
    example: 'SELECT JSON_DATAGUIDE(json_data) AS data_guide FROM my_table;',
    returnType: 'VARCHAR',
  },
];

const NULL_Functions: IFunction[] = [
  {
    name: 'COALESCE',
    description: '返回参数列表中第一个非NULL的值。',
    parameters: [{ name: 'expr', type: 'any*', description: '要检查的表达式列表。' }],
    example: "SELECT COALESCE(NULL, NULL, 'First non-null value') AS result FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'LNNVL',
    description: '对逻辑表达式进行求值，如果结果为FALSE或UNKNOWN，则返回TRUE，否则返回FALSE。',
    parameters: [{ name: 'condition', type: 'BOOLEAN', description: '要评估的逻辑条件。' }],
    example: 'SELECT LNNVL(salary > 5000) AS result FROM employees WHERE employee_id = 101;',
    returnType: 'BOOLEAN',
  },
  {
    name: 'NANVL',
    description: '如果表达式为NaN（非数字），则返回替换值。',
    parameters: [
      { name: 'x', type: 'FLOAT', description: '要检查的数字表达式。' },
      { name: 'y', type: 'FLOAT', description: '如果x为NaN，则返回的替换值。' },
    ],
    example: 'SELECT NANVL(NAN, 0) AS result FROM DUAL;',
    returnType: 'FLOAT',
  },
  {
    name: 'NULLIF',
    description: '如果两个表达式相等，则返回NULL，否则返回第一个表达式。',
    parameters: [
      { name: 'expr1', type: 'any', description: '第一个表达式。' },
      { name: 'expr2', type: 'any', description: '第二个表达式。' },
    ],
    example: "SELECT NULLIF('abc', 'abc') AS result FROM DUAL;",
    returnType: 'Typeof(1)',
  },
  {
    name: 'NVL',
    description: '如果表达式为NULL，则返回替换值。',
    parameters: [
      { name: 'expr', type: 'any', description: '要检查的表达式。' },
      { name: 'replacement', type: 'any', description: '如果expr为NULL，则返回的替换值。' },
    ],
    example: "SELECT NVL(NULL, 'replacement') AS result FROM DUAL;",
    returnType: 'VARCHAR',
  },
  {
    name: 'NVL2',
    description: '如果第一个表达式不为NULL，则返回第二个表达式，否则返回第三个表达式。',
    parameters: [
      { name: 'expr1', type: 'any', description: '要检查的表达式。' },
      { name: 'expr2', type: 'any', description: '如果expr1不为NULL，则返回的值。' },
      { name: 'expr3', type: 'any', description: '如果expr1为NULL，则返回的值。' },
    ],
    example: "SELECT NVL2(NULL, 'not null', 'null') AS result FROM DUAL;",
    returnType: 'VARCHAR',
  },
];

const Orther_Functions: IFunction[] = [
  {
    name: 'SYS_CONNECT_BY_PATH',
    description: '在层次查询中，返回从根节点到当前节点的路径。',
    parameters: [
      { name: 'column', type: 'NUMBER', description: '路径中要连接的列。' },
      { name: 'delimiter', type: 'VARCHAR', description: '用于分隔路径中元素的分隔符。' },
    ],
    returnType: 'VARCHAR',
  },
];

const Oracle: IKeyword = {
  type: DatabaseTypeCode.ORACLE,
  priority_keywords: ['SELECT'],
  keywords: [
    'LEFT JOIN',
    'LEFT OUTER JOIN',
    'RIGHT JOIN',
    'RIGHT OUTER JOIN',
    'INNER JOIN',
    'OUTER JOIN',
    'ACCESS',
    'ADD',
    'ALL',
    'ALTER',
    'AND',
    'ANY',
    'AS',
    'ASC',
    'AUDIT',
    'BETWEEN',
    'BY',
    'CHAR',
    'CHECK',
    'CLUSTER',
    'COLUMN',
    'COMMENT',
    'COMPRESS',
    'CONNECT',
    'CREATE',
    'CREATE TABLE',
    'CREATE DATABASE',
    'CREATE FUNCTION',
    'CREATE INDEX',
    'CREATE PROCEDURE',
    'CREATE VIEW',
    'CURRENT',
    'DATE',
    'DECIMAL',
    'DEFAULT',
    'DELETE',
    'DESC',
    'DISTINCT',
    'DROP',
    'DROP TABLE',
    'DROP DATABASE',
    'DROP FUNCTION',
    'DROP INDEX',
    'DROP PROCEDURE',
    'DROP VIEW',
    'DROP ROLE',
    'DROP USER',
    'ELSE',
    'EXCLUSIVE',
    'EXISTS',
    'FILE',
    'FLOAT',
    'FOR',
    'FROM',
    'GRANT',
    'GROUP',
    'GROUP BY',
    'HAVING',
    'IDENTIFIED',
    'IMMEDIATE',
    'IN',
    'INCREMENT',
    'INDEX',
    'INITIAL',
    'INSERT',
    'INTEGER',
    'INTERSECT',
    'INTO',
    'IS',
    'LEVEL',
    'LIKE',
    'LOCK',
    'LONG',
    'MAXEXTENTS',
    'MINUS',
    'MLSLABEL',
    'MODE',
    'MODIFY',
    'NOAUDIT',
    'NOCOMPRESS',
    'NOT',
    'NOWAIT',
    'NULL',
    'NUMBER',
    'OF',
    'OFFLINE',
    'ON',
    'ONLINE',
    'OPTION',
    'OR',
    'ORDER',
    'ORDER BY',
    'PCTFREE',
    'PRIOR',
    'PRIVILEGES',
    'PUBLIC',
    'RAW',
    'RENAME',
    'RESOURCE',
    'REVOKE',
    'ROW',
    'ROWID',
    'ROWNUM',
    'ROWS',
    'SESSION',
    'SET',
    'SHARE',
    'SIZE',
    'SMALLINT',
    'START',
    'SUCCESSFUL',
    'SYNONYM',
    'SYSDATE',
    'TABLE',
    'THEN',
    'TRUNCATE',
    'TRUNCATE TABLE',
    'TO',
    'TRIGGER',
    'UID',
    'UNION',
    'UNIQUE',
    'UPDATE',
    'USER',
    'VALIDATE',
    'VALUES',
    'VARCHAR',
    'VARCHAR',
    'VIEW',
    'WHENEVER',
    'WHERE',
    'WITH',
    'JOIN',
    'ALTER SESSION',
    'CURRENT_SCHEMA',
  ],
  priority_functions: [],
  functions: [
    ...Math_Functions,
    ...String_Functions,
    ...String_Collection_Functions,
    ...Sort_Functions,
    ...Date_Functions,
    ...Compare_Functions,
    ...Change_Functions,
    ...BigObject_Functions,
    ...Common_Functions,
    ...XML_Functions,
    ...JSON_Functions,
    ...NULL_Functions,

    ...Orther_Functions,
  ],
};

export default Oracle;
