import { DatabaseTypeCode } from '@/constants';
import { IFunction, IKeyword } from '.';

const Math_Functions: IFunction[] = [
  {
    name: 'ABS',
    description: '返回数值的绝对值。',
    parameters: [{ name: 'number', type: 'numeric' }],
    returnType: 'numeric',
    example: 'SELECT ABS(-10) AS absolute_value;',
  },
  {
    name: 'CEIL',
    description: '返回不小于指定数值的最小整数。',
    parameters: [{ name: 'number', type: 'numeric' }],
    returnType: 'bigint or double precision',
    example: 'SELECT CEIL(9.4) AS ceiling;',
  },
  {
    name: 'FLOOR',
    description: '返回不大于指定数值的最大整数。',
    parameters: [{ name: 'number', type: 'numeric' }],
    returnType: 'bigint or double precision',
    example: 'SELECT FLOOR(9.4) AS floor;',
  },
  {
    name: 'ROUND',
    description: '将数值四舍五入到指定的小数位数。',
    parameters: [
      { name: 'number', type: 'numeric' },
      { name: 'decimal_places', type: 'integer', optional: true },
    ],
    returnType: 'numeric',
    example: 'SELECT ROUND(9.5627, 2) AS rounded;',
  },
  {
    name: 'POWER',
    description: '返回数的指数次幂。',
    parameters: [
      { name: 'base', type: 'numeric' },
      { name: 'exponent', type: 'numeric' },
    ],
    returnType: 'numeric',
    example: 'SELECT POWER(2, 3) AS power_value;',
  },
  {
    name: 'SQRT',
    description: '计算平方根。',
    parameters: [{ name: 'number', type: 'numeric' }],
    returnType: 'numeric',
    example: 'SELECT SQRT(16) AS square_root;',
  },
];

const String_Functions: IFunction[] = [
  {
    name: 'CONCAT',
    description: '连接两个或多个字符串。',
    parameters: [
      { name: 'string1', type: 'text' },
      { name: 'string2', type: 'text' },
      { name: 'additional_strings', type: 'text', optional: true },
    ],
    returnType: 'text',
    example: "SELECT CONCAT('Chat', 'GPT') AS concatenated_string;",
  },
  {
    name: 'LENGTH',
    description: '返回字符串的字符数。',
    parameters: [{ name: 'string|bit|bytea|char', type: 'text' }],
    returnType: 'integer',
    example: "SELECT LENGTH('Hello') AS length_of_hello;",
  },

  {
    name: 'SUBSTRING',
    description: '从字符串中提取子字符串。',
    parameters: [
      { name: 'string', type: 'text' },
      { name: 'start', type: 'integer' },
      { name: 'length', type: 'integer' },
    ],
    returnType: 'text',
    example: "SELECT SUBSTRING('Hello, world!', 1, 5) AS substring;",
  },
  {
    name: 'TRIM',
    description: '从字符串的两端删除指定的字符。',
    parameters: [
      { name: 'characters', type: 'text', optional: true },
      { name: 'from_string', type: 'text' },
    ],
    returnType: 'text',
    example: "SELECT TRIM(BOTH 'x' FROM 'xHellox') AS trimmed_string;",
  },
  {
    name: 'LOWER',
    description: '将字符串中的所有字符转换为小写。',
    parameters: [{ name: 'string', type: 'text' }],
    returnType: 'text',
    example: "SELECT LOWER('HeLLo') AS lower_case_string;",
  },
  {
    name: 'UPPER',
    description: '将字符串中的所有字符转换为大写。',
    parameters: [{ name: 'string', type: 'text' }],
    returnType: 'text',
    example: "SELECT UPPER('hello') AS upper_case_string;",
  },
  {
    name: 'POSITION',
    description: '返回子字符串在字符串中首次出现的位置。',
    parameters: [
      { name: 'substring', type: 'text' },
      { name: 'in_string', type: 'text' },
    ],
    returnType: 'integer',
    example: "SELECT POSITION('world' IN 'Hello, world!') AS position_of_world;",
  },
  {
    name: 'REPLACE',
    description: '在字符串中用新字符串替换所有出现的旧字符串。',
    parameters: [
      { name: 'string', type: 'text' },
      { name: 'from_substring', type: 'text' },
      { name: 'to_substring', type: 'text' },
    ],
    returnType: 'text',
    example: "SELECT REPLACE('Hello, world!', 'world', 'PostgreSQL') AS replaced_string;",
  },
];

const Date_Functions: IFunction[] = [
  {
    name: 'CURRENT_DATE',
    description: '返回当前日期。',
    parameters: [],
    returnType: 'date',
    example: 'SELECT CURRENT_DATE AS today;',
  },
  {
    name: 'CURRENT_TIME',
    description: '返回当前时间。',
    parameters: [],
    returnType: 'time with time zone',
    example: 'SELECT CURRENT_TIME AS now;',
  },
  {
    name: 'AGE',
    description: '计算两个日期之间的年龄，如果只提供一个参数，则计算该日期到当前日期的年龄。',
    parameters: [
      { name: 'timestamp1', type: 'timestamp', optional: true },
      { name: 'timestamp2', type: 'timestamp' },
    ],
    returnType: 'interval',
    example: "SELECT AGE(timestamp '2000-01-01') AS age_since_2000;",
  },
  {
    name: 'DATE_PART',
    description: '从日期/时间值中提取指定的部分（如年、月、日、小时等）。',
    parameters: [
      { name: 'field', type: 'text' },
      { name: 'source', type: 'timestamp or interval' },
    ],
    returnType: 'double precision',
    example: "SELECT DATE_PART('year', timestamp '2023-08-30') AS year_part;",
  },
  {
    name: 'EXTRACT',
    description: '与 DATE_PART 类似，用于从日期/时间值中提取指定的部分。',
    parameters: [
      { name: 'field', type: 'text' },
      { name: 'source', type: 'timestamp or interval' },
    ],
    returnType: 'double precision',
    example: "SELECT EXTRACT(month FROM timestamp '2023-08-30') AS month_part;",
  },
  {
    name: 'NOW',
    description: '返回当前的日期和时间。',
    parameters: [],
    returnType: 'timestamp with time zone',
    example: 'SELECT NOW() AS current_timestamp;',
  },
  {
    name: 'TO_DATE',
    description: '将字符串转换为日期。',
    parameters: [
      { name: 'text', type: 'text' },
      { name: 'format', type: 'text' },
    ],
    returnType: 'date',
    example: "SELECT TO_DATE('2023-08-30', 'YYYY-MM-DD') AS date_conversion;",
  },
  {
    name: 'TO_TIMESTAMP',
    description: '将字符串转换为时间戳。',
    parameters: [
      { name: 'text', type: 'text' },
      { name: 'format', type: 'text' },
    ],
    returnType: 'timestamp',
    example: "SELECT TO_TIMESTAMP('2023-08-30 14:00', 'YYYY-MM-DD HH24:MI') AS timestamp_conversion;",
  },
];

const Aggregation_Functions: IFunction[] = [
  {
    name: 'SUM',
    description: '计算数值列的总和。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
    example: 'SELECT SUM(price) AS total_price FROM sales;',
  },
  {
    name: 'AVG',
    description: '计算数值列的平均值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
    example: 'SELECT AVG(price) AS average_price FROM sales;',
  },
  {
    name: 'COUNT',
    description: '计算行数或非空值的数量。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'bigint',
    example: 'SELECT COUNT(*) AS total_rows FROM sales;',
  },
  {
    name: 'MAX',
    description: '返回列中的最大值。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'same as input type',
    example: 'SELECT MAX(price) AS highest_price FROM sales;',
  },
  {
    name: 'MIN',
    description: '返回列中的最小值。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'same as input type',
    example: 'SELECT MIN(price) AS lowest_price FROM sales;',
  },
];

const Window_Functions: IFunction[] = [
  {
    name: 'ROW_NUMBER',
    description: '为每个行返回一个唯一的行号。',
    parameters: [],
    returnType: 'bigint',
    example: 'SELECT ROW_NUMBER() OVER (ORDER BY price DESC) AS row_num FROM sales;',
  },
  {
    name: 'RANK',
    description: '根据排序给行分配一个排名，相同值的行会得到相同的排名，并留下间隔。',
    parameters: [],
    returnType: 'bigint',
    example: 'SELECT RANK() OVER (ORDER BY price DESC) AS rank FROM sales;',
  },
  {
    name: 'DENSE_RANK',
    description: '根据排序给行分配一个排名，相同值的行会得到相同的排名，但不留下间隔。',
    parameters: [],
    returnType: 'bigint',
    example: 'SELECT DENSE_RANK() OVER (ORDER BY price DESC) AS dense_rank FROM sales;',
  },
  {
    name: 'LEAD',
    description: '返回当前行后面的第 N 行的值。',
    parameters: [
      { name: 'expression', type: 'any' },
      { name: 'offset', type: 'integer', optional: true },
      { name: 'default', type: 'any', optional: true },
    ],
    returnType: 'same as input type',
    example: 'SELECT LEAD(price, 1) OVER (ORDER BY date) AS next_price FROM sales;',
  },
  {
    name: 'LAG',
    description: '返回当前行前面的第 N 行的值。',
    parameters: [
      { name: 'expression', type: 'any' },
      { name: 'offset', type: 'integer', optional: true },
      { name: 'default', type: 'any', optional: true },
    ],
    returnType: 'same as input type',
    example: 'SELECT LAG(price, 1) OVER (ORDER BY date) AS prev_price FROM sales;',
  },
];

const Geometry_Functions: IFunction[] = [
  {
    name: 'ST_Distance',
    description: '计算两个地理空间对象之间的最短距离。',
    parameters: [
      { name: 'geo1', type: 'geometry' },
      { name: 'geo2', type: 'geometry' },
    ],
    returnType: 'float',
    example: 'SELECT ST_Distance(geo1, geo2) AS distance FROM locations;',
  },
  {
    name: 'ST_Area',
    description: '计算地理空间对象的面积。',
    parameters: [{ name: 'geo', type: 'geometry' }],
    returnType: 'float',
    example: 'SELECT ST_Area(geo) AS area FROM regions;',
  },
  {
    name: 'ST_Intersection',
    description: '返回两个地理空间对象的交集。',
    parameters: [
      { name: 'geo1', type: 'geometry' },
      { name: 'geo2', type: 'geometry' },
    ],
    returnType: 'geometry',
    example: 'SELECT ST_Intersection(geo1, geo2) AS intersection FROM areas;',
  },
  {
    name: 'ST_Buffer',
    description: '对地理空间对象进行缓冲区分析，即围绕对象创建一个指定距离的区域。',
    parameters: [
      { name: 'geo', type: 'geometry' },
      { name: 'radius', type: 'float' },
    ],
    returnType: 'geometry',
    example: 'SELECT ST_Buffer(geo, 10.0) AS buffer FROM roads;',
  },
];

const System_Functions: IFunction[] = [
  {
    name: 'VERSION',
    description: '返回 PostgreSQL 服务器的版本信息。',
    parameters: [],
    returnType: 'text',
    example: 'SELECT VERSION() AS version;',
  },
  {
    name: 'CURRENT_SETTING',
    description: '获取指定的 PostgreSQL 配置参数值。',
    parameters: [{ name: 'setting_name', type: 'text' }],
    returnType: 'text',
    example: "SELECT CURRENT_SETTING('max_connections') AS max_connections;",
  },
  {
    name: 'PG_BACKEND_PID',
    description: '返回当前 PostgreSQL 后端进程的进程 ID。',
    parameters: [],
    returnType: 'integer',
    example: 'SELECT PG_BACKEND_PID() AS pid;',
  },
];

const Type_Functions: IFunction[] = [
  {
    name: 'CAST',
    description: '将一个表达式转换为另一种数据类型。',
    parameters: [
      { name: 'expression', type: 'any' },
      { name: 'target_type', type: 'data type' },
    ],
    returnType: 'data type',
    example: "SELECT CAST('2023-01-01' AS date) AS date_cast;",
  },
  {
    name: 'TO_CHAR',
    description: '将数字或日期转换为字符串。',
    parameters: [
      { name: 'expression', type: 'numeric or date/time' },
      { name: 'format', type: 'text' },
    ],
    returnType: 'text',
    example: "SELECT TO_CHAR(current_timestamp, 'YYYY-MM-DD HH24:MI') AS formatted_date;",
  },
  {
    name: 'TO_NUMBER',
    description: '将字符串转换为数字。',
    parameters: [
      { name: 'text', type: 'text' },
      { name: 'format', type: 'text' },
    ],
    returnType: 'numeric',
    example: "SELECT TO_NUMBER('1234', '9999') AS number;",
  },
  {
    name: 'TO_DATE',
    description: '将字符串转换为日期。',
    parameters: [
      { name: 'text', type: 'text' },
      { name: 'format', type: 'text' },
    ],
    returnType: 'date',
    example: "SELECT TO_DATE('2023-08-30', 'YYYY-MM-DD') AS date_conversion;",
  },
];

const JSON_Functions: IFunction[] = [
  {
    name: 'JSON_AGG',
    description: '将一组行转换为 JSON 数组。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'json',
    example: 'SELECT JSON_AGG(row) AS json_array FROM (SELECT * FROM users) AS row;',
  },
  {
    name: 'JSON_BUILD_OBJECT',
    description: '构建一个 JSON 对象。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'json',
    example: "SELECT JSON_BUILD_OBJECT('name', 'John', 'age', 30) AS json_object;",
  },
  {
    name: 'JSON_BUILD_ARRAY',
    description: '构建一个 JSON 数组。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'json',
    example: 'SELECT JSON_BUILD_ARRAY(1, 2, 3) AS json_array;',
  },
  {
    name: 'JSON_EXTRACT',
    description: '从 JSON 对象中提取一个值。',
    parameters: [{ name: 'json_object', type: 'json' }],
    returnType: 'text',
    example: 'SELECT JSON_EXTRACT(\'{"name": "John", "age": 30}\', \'$.name\') AS name;',
  },
  {
    name: 'JSON_OBJECT_AGG',
    description: '将一组行转换为 JSON 对象。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'json',
    example: "SELECT JSON_OBJECT_AGG('name', 'John') AS json_object;",
  },
  {
    name: 'JSON_ARRAY_AGG',
    description: '将一组行转换为 JSON 数组。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'json',
    example: 'SELECT JSON_ARRAY_AGG(row) AS json_array FROM (SELECT * FROM users) AS row;',
  },
];

const Array_Functions: IFunction[] = [
  {
    name: 'ARRAY_AGG',
    description: '将一组行转换为数组。',
    parameters: [{ name: 'expression', type: 'any' }],
    returnType: 'array',
    example: 'SELECT ARRAY_AGG(row) AS array FROM (SELECT * FROM users) AS row;',
  },
  {
    name: 'ARRAY_CAT',
    description: '连接两个数组。',
    parameters: [
      { name: 'array1', type: 'array' },
      { name: 'array2', type: 'array' },
    ],
    returnType: 'array',
    example: 'SELECT ARRAY_CAT(ARRAY[1,2,3], ARRAY[4,5]) AS concatenated_array;',
  },
  {
    name: 'ARRAY_APPEND',
    description: '将元素添加到数组的末尾。',
    parameters: [
      { name: 'array', type: 'array' },
      { name: 'element', type: 'any' },
    ],
    returnType: 'array',
    example: 'SELECT ARRAY_APPEND(ARRAY[1,2,3], 4) AS new_array;',
  },
  {
    name: 'ARRAY_LENGTH',
    description: '返回数组的长度（在指定的维度）。',
    parameters: [
      { name: 'array', type: 'array' },
      { name: 'dimension', type: 'integer' },
    ],
    returnType: 'integer',
    example: 'SELECT ARRAY_LENGTH(ARRAY[[1,2,3], [4,5,6]], 1) AS length_of_array;',
  },
];

const Condition_Functions: IFunction[] = [
  {
    name: 'COALESCE',
    description: '返回参数列表中的第一个非 NULL 值。',
    parameters: [{ name: 'value', type: 'any', optional: true }],
    returnType: 'same as first non-null input',
    example: "SELECT COALESCE(NULL, NULL, 'third value', 'fourth value') AS first_non_null;",
  },
  {
    name: 'NULLIF',
    description: '如果两个参数相等，则返回 NULL，否则返回第一个参数。',
    parameters: [
      { name: 'value1', type: 'any' },
      { name: 'value2', type: 'any' },
    ],
    returnType: 'same as input type',
    example: "SELECT NULLIF('A', 'B') AS result;",
  },
  {
    name: 'GREATEST',
    description: '返回所有参数中的最大值。',
    parameters: [{ name: 'value', type: 'any', optional: true }],
    returnType: 'same as input type',
    example: 'SELECT GREATEST(1, 2, 3) AS max_value;',
  },
  {
    name: 'LEAST',
    description: '返回所有参数中的最小值。',
    parameters: [{ name: 'value', type: 'any', optional: true }],
    returnType: 'same as input type',
    example: 'SELECT LEAST(1, 2, 3) AS min_value;',
  },
];

const Pg: IKeyword = {
  type: DatabaseTypeCode.POSTGRESQL,
  priority_keywords: ['SELECT'],
  keywords: [
    'INSERT',
    'UPDATE',
    'DELETE',
    'FROM',
    'WHERE',
    'INNER',
    'JOIN',
    'LEFT',
    'RIGHT',
    'FULL',
    'OUTER',
    'GROUP',
    'GROUP BY',
    'ORDER',
    'ORDER BY',
    'BY',
    'HAVING',
    'LIMIT',
    'OFFSET',
    'FETCH',
    'IN',
    'AND',
    'OR',
    'NOT',
    'EXISTS',
    'COUNT',
    'SUM',
    'AVG',
    'MIN',
    'MAX',
    'AS',
    'ON',
    'ANY',
    'ALL',
    'DISTINCT',
    'TABLE',
    'INDEX',
    'VIEW',
    'SEQUENCE',
    'TRIGGER',
    'USER',
    'PASSWORD',
    'ALTER',
    'DROP',
    'DROP TABLE',
    'DROP DATABASE',
    'DROP FUNCTION',
    'DROP INDEX',
    'DROP PROCEDURE',
    'DROP VIEW',
    'DROP ROLE',
    'DROP USER',
    'CREATE',
    'CREATE TABLE',
    'CREATE DATABASE',
    'CREATE SCHEMA',
    'CREATE FUNCTION',
    'CREATE INDEX',
    'CREATE PROCEDURE',
    'CREATE VIEW',
    'CREATE TRIGGER',
    'CREATE ROLE',
    'CREATE USER',
    'GRANT',
    'REVOKE',
    'ROLE',
    'PUBLIC',
    'NULL',
    'TRUE',
    'FALSE',
    'UNKNOWN',
    'CASE',
    'WHEN',
    'THEN',
    'ELSE',
    'END',
    'TYPE',
    'TRUNCATE',
    'TRUNCATE TABLE',
    'CAST',
    'COLUMN',
    'DATABASE',
    'UNIQUE',
    'PRIMARY',
    'FOREIGN',
    'REFERENCES',
    'EXPLAIN',
    'WITH',
    'WITHOUT',
    'SET',
    'IS',
    'LIKE',
    'ILIKE',
    'SIMILAR',
    'TO',
    'IF',
    'ELSEIF',
    'LOOP',
    'WHILE',
    'FOR',
    'RETURN',
    'FUNCTION',
    'DO',
    'LEFT JOIN',
    'LEFT OUTER JOIN',
    'RIGHT JOIN',
    'RIGHT OUTER JOIN',
    'INNER JOIN',
    'OUTER JOIN',
    'SEARCH_PATH',
    'UNION',
    'UNION ALL',
    'UNION DISTINCT',
    'bigint',
    'int',
    'smallint',
    'tinyint',
    'bit',
    'boolean',
    'varchar',
    'char',
    'text',
    'xml',
    'json',
    'jsonb',
    'array',
    'date',
    'time',
    'timestamp',
    'interval',
    'geometry',
    'characters',
    'numeric',
    'double precision',
    'real',
    'float',
    'double',
    'decimal',
    'integer',
  ],
  priority_functions: [],
  functions: [
    ...Math_Functions,
    ...Date_Functions,
    ...String_Functions,
    ...Aggregation_Functions,
    ...Window_Functions,
    ...Geometry_Functions,
    ...JSON_Functions,
    ...Array_Functions,
    ...Condition_Functions,
    ...System_Functions,
    ...Type_Functions,
  ],
};

export default Pg;
