import { DatabaseTypeCode } from '@/constants';
import { IFunction, IKeyword } from '.';

const Math_Functions: IFunction[] = [
  {
    name: 'ABS',
    description: '返回数值的绝对值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'ACOS',
    description: '返回指定浮点表达式的反余弦值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'ASIN',
    description: '返回指定浮点表达式的反正弦值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'ATAN',
    description: '返回指定浮点表达式的反正切值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'ATN2',
    description: '返回两个指定浮点表达式之间的角度。',
    parameters: [
      { name: 'expression_y', type: 'numeric' },
      { name: 'expression_x', type: 'numeric' },
    ],
    returnType: 'numeric',
  },
  {
    name: 'CEILING',
    description: '向上舍入为最接近的整数。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'int',
  },
  {
    name: 'COS',
    description: '返回指定角度的余弦值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'COT',
    description: '返回指定角度的余切值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'DEGREES',
    description: '将弧度转换为度。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'EXP',
    description: '返回 e 的指定次方。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'FLOOR',
    description: '向下舍入为最接近的整数。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'int',
  },
  {
    name: 'LOG',
    description: '返回指定表达式的自然对数。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'LOG10',
    description: '返回指定表达式的以10为底的对数。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'PI',
    description: '返回 PI 的值。',
    parameters: [],
    returnType: 'numeric',
  },
  {
    name: 'POWER',
    description: '返回指定表达式的指定次方。',
    parameters: [
      { name: 'expression', type: 'numeric' },
      { name: 'power', type: 'numeric' },
    ],
    returnType: 'numeric',
  },
  {
    name: 'RADIANS',
    description: '将度转换为弧度。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'RAND',
    description: '返回一个伪随机数。',
    parameters: [{ name: 'seed', type: 'int', optional: true }],
    returnType: 'float',
  },
  {
    name: 'ROUND',
    description: '返回指定长度或精度的四舍五入值。',
    parameters: [
      { name: 'expression', type: 'numeric' },
      { name: 'length', type: 'int' },
    ],
    returnType: 'numeric',
  },
  {
    name: 'SIGN',
    description: '返回指定表达式的符号。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'int',
  },
  {
    name: 'SIN',
    description: '返回指定角度的正弦值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'SQRT',
    description: '返回指定表达式的平方根。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'SQUARE',
    description: '返回指定表达式的平方。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
  {
    name: 'TAN',
    description: '返回指定角度的正切值。',
    parameters: [{ name: 'expression', type: 'numeric' }],
    returnType: 'numeric',
  },
];

const Date_Functions: IFunction[] = [
  {
    name: 'GETDATE',
    description: '返回 SQL Server 实例运行计算机的当前日期和时间。',
    parameters: [],
    returnType: 'datetime',
  },
  {
    name: 'GETUTCDATE',
    description: '返回协调世界时（UTC）。',
    parameters: [],
    returnType: 'datetime',
  },
  {
    name: 'CURRENT_TIMESTAMP',
    description: '返回 SQL Server 实例运行计算机的当前日期和时间。',
    parameters: [],
    returnType: 'datetime',
  },
  {
    name: 'DAY',
    description: '返回指定日期的日部分。',
    parameters: [{ name: 'date', type: 'date' }],
    returnType: 'int',
  },
  {
    name: 'MONTH',
    description: '返回指定日期的月部分。',
    parameters: [{ name: 'date', type: 'date' }],
    returnType: 'int',
  },
  {
    name: 'YEAR',
    description: '返回指定日期的年部分。',
    parameters: [{ name: 'date', type: 'date' }],
    returnType: 'int',
  },
  {
    name: 'DATEPART',
    description: '返回指定日期的指定部分。',
    parameters: [
      { name: 'datepart', type: 'varchar' },
      { name: 'date', type: 'date' },
    ],
    returnType: 'int',
  },
  {
    name: 'DATENAME',
    description: '返回指定日期的指定部分的名称。',
    parameters: [
      { name: 'datepart', type: 'varchar' },
      { name: 'date', type: 'date' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'DATEADD',
    description: '返回一个新日期，该日期在指定的日期部分上增加了一定数量的间隔。',
    parameters: [
      { name: 'datepart', type: 'varchar' },
      { name: 'number', type: 'int' },
      { name: 'date', type: 'date' },
    ],
    returnType: 'datetime',
  },
  {
    name: 'DATEDIFF',
    description: '返回两个日期之间的指定日期部分的差异。',
    parameters: [
      { name: 'datepart', type: 'varchar' },
      { name: 'startdate', type: 'date' },
      { name: 'enddate', type: 'date' },
    ],
    returnType: 'int',
  },
  {
    name: 'EOMONTH',
    description: '返回指定日期所在月份的最后一天。',
    parameters: [
      { name: 'start_date', type: 'date' },
      { name: 'month_to_add', type: 'int', optional: true },
    ],
    returnType: 'date',
  },
];

const String_Functions: IFunction[] = [
  {
    name: 'ASCII',
    description: '返回字符表达式最左边字符的 ASCII 码值。',
    parameters: [{ name: 'expression', type: 'char' }],
    returnType: 'int',
  },
  {
    name: 'CHAR',
    description: '根据指定的整数 ASCII 码值返回相应的字符。',
    parameters: [{ name: 'integer', type: 'int' }],
    returnType: 'char',
  },
  {
    name: 'CHARINDEX',
    description: '返回一个表达式中另一个表达式的第一个实例的起始位置。',
    parameters: [
      { name: 'expressionToFind', type: 'varchar' },
      { name: 'expressionToSearch', type: 'varchar' },
      { name: 'startLocation', type: 'int', optional: true },
    ],
    returnType: 'int',
  },
  {
    name: 'CONCAT',
    description: '将两个或多个字符串值连接成一个字符串。',
    parameters: [
      { name: 'string_value1', type: 'varchar' },
      { name: 'string_value2', type: 'varchar' },
      { name: '...', type: 'varchar' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'CONCAT_WS',
    description: '使用指定的分隔符连接两个或多个字符串值。',
    parameters: [
      { name: 'separator', type: 'varchar' },
      { name: 'string_value1', type: 'varchar' },
      { name: 'string_value2', type: 'varchar' },
      { name: '...', type: 'varchar' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'LEFT',
    description: '返回字符串最左边的指定数量的字符。',
    parameters: [
      { name: 'character_expression', type: 'varchar' },
      { name: 'integer_expression', type: 'int' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'LEN',
    description: '返回字符串的长度。',
    parameters: [{ name: 'string_expression', type: 'varchar' }],
    returnType: 'int',
  },
  {
    name: 'LOWER',
    description: '将字符数据转换为小写。',
    parameters: [{ name: 'character_expression', type: 'varchar' }],
    returnType: 'varchar',
  },
  {
    name: 'LTRIM',
    description: '从字符串的开始部分去除空格。',
    parameters: [{ name: 'character_expression', type: 'varchar' }],
    returnType: 'varchar',
  },
  {
    name: 'REPLACE',
    description: '将字符串中的某些字符替换为另一组字符。',
    parameters: [
      { name: 'string_expression', type: 'varchar' },
      { name: 'string_pattern', type: 'varchar' },
      { name: 'string_replacement', type: 'varchar' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'REVERSE',
    description: '返回一个字符串，其中字符串的字符顺序被反转。',
    parameters: [{ name: 'character_expression', type: 'varchar' }],
    returnType: 'varchar',
  },
  {
    name: 'RIGHT',
    description: '返回字符串最右边的指定数量的字符。',
    parameters: [
      { name: 'character_expression', type: 'varchar' },
      { name: 'integer_expression', type: 'int' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'RTRIM',
    description: '从字符串的末尾去除空格。',
    parameters: [{ name: 'character_expression', type: 'varchar' }],
    returnType: 'varchar',
  },
  {
    name: 'SUBSTRING',
    description: '返回字符串的子字符串，从指定的位置开始，指定的长度。',
    parameters: [
      { name: 'expression', type: 'varchar' },
      { name: 'start', type: 'int' },
      { name: 'length', type: 'int' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'UPPER',
    description: '将字符数据转换为大写。',
    parameters: [{ name: 'character_expression', type: 'varchar' }],
    returnType: 'varchar',
  },
];

const JSON_Functions: IFunction[] = [
  {
    name: 'ISJSON',
    description: '检测字符串是否包含有效的 JSON。',
    parameters: [{ name: 'expression', type: 'varchar' }],
    returnType: 'int',
  },
  {
    name: 'JSON_VALUE',
    description: '从 JSON 字符串中提取标量值。',
    parameters: [
      { name: 'expression', type: 'varchar' },
      { name: 'path', type: 'varchar' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'JSON_QUERY',
    description: '从 JSON 字符串中提取对象或数组。',
    parameters: [
      { name: 'expression', type: 'varchar' },
      { name: 'path', type: 'varchar' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'JSON_MODIFY',
    description: '更新 JSON 字符串中的属性值并返回更新后的 JSON 字符串。',
    parameters: [
      { name: 'expression', type: 'varchar' },
      { name: 'path', type: 'varchar' },
      { name: 'newValue', type: 'varchar' },
    ],
    returnType: 'varchar',
  },
  {
    name: 'OPENJSON',
    description: '解析 JSON 文本并返回 JSON 输入中的对象和属性作为行和列。',
    parameters: [
      { name: 'jsonExpression', type: 'varchar' },
      { name: 'withClause', type: 'varchar', optional: true },
    ],
    returnType: 'table',
  },
  {
    name: 'JSON_OBJECT',
    description: '从一个或多个表达式中构造 JSON 对象文本。',
    parameters: [],
    returnType: 'varchar',
  },
  {
    name: 'JSON_ARRAY',
    description: '从零个或多个值中构造 JSON 数组文本。',
    parameters: [],
    returnType: 'varchar',
  },
];

const SQLServer: IKeyword = {
  type: DatabaseTypeCode.SQLSERVER,
  priority_keywords: ['SELECT'],
  keywords: [
    'ADD',
    'EXTERNAL',
    'PROCEDURE',
    'ALL',
    'FETCH',
    'PUBLIC',
    'ALTER',
    'FILE',
    'RAISERROR',
    'AND',
    'FILLFACTOR',
    'READ',
    'ANY',
    'FOR',
    'READTEXT',
    'AS',
    'FOREIGN',
    'RECONFIGURE',
    'ASC',
    'FREETEXT',
    'REFERENCES',
    'AUTHORIZATION',
    'FREETEXTTABLE',
    'REPLICATION',
    'BACKUP',
    'FROM',
    'RESTORE',
    'BEGIN',
    'FULL',
    'RESTRICT',
    'BETWEEN',
    'FUNCTION',
    'RETURN',
    'BREAK',
    'GOTO',
    'REVERT',
    'BROWSE',
    'GRANT',
    'REVOKE',
    'BULK',
    'GROUP',
    'GROUP BY',
    'ORDER',
    'ORDER BY',
    'RIGHT',
    'BY',
    'HAVING',
    'ROLLBACK',
    'CASCADE',
    'HOLDLOCK',
    'ROWCOUNT',
    'CASE',
    'IDENTITY',
    'ROWGUIDCOL',
    'CHECK',
    'IDENTITY_INSERT',
    'RULE',
    'CHECKPOINT',
    'IDENTITYCOL',
    'SAVE',
    'CLOSE',
    'IF',
    'SCHEMA',
    'CLUSTERED',
    'IN',
    'SECURITYAUDIT',
    'COALESCE',
    'INDEX',
    'SELECT',
    'COLLATE',
    'INNER',
    'SEMANTICKEYPHRASETABLE',
    'COLUMN',
    'INSERT',
    'SEMANTICSIMILARITYDETAILSTABLE',
    'COMMIT',
    'INTERSECT',
    'SEMANTICSIMILARITYTABLE',
    'COMPUTE',
    'INTO',
    'SESSION_USER',
    'CONSTRAINT',
    'IS',
    'SET',
    'CONTAINS',
    'JOIN',
    'SETUSER',
    'CONTAINSTABLE',
    'KEY',
    'SHUTDOWN',
    'CONTINUE',
    'KILL',
    'SOME',
    'CONVERT',
    'LEFT',
    'STATISTICS',
    'CREATE',
    'CREATE TABLE',
    'CREATE DATABASE',
    'CREATE SCHEMA',
    'CREATE FUNCTION',
    'CREATE INDEX',
    'CREATE PROCEDURE',
    'CREATE VIEW',
    'CREATE TRIGGER',
    'CREATE ROLE',
    'CREATE USER',
    'LIKE',
    'SYSTEM_USER',
    'CROSS',
    'LINENO',
    'TABLE',
    'CURRENT',
    'LOAD',
    'TABLESAMPLE',
    'CURRENT_DATE',
    'MERGE',
    'TEXTSIZE',
    'CURRENT_TIME',
    'NATIONAL',
    'THEN',
    'CURRENT_TIMESTAMP',
    'NOCHECK',
    'TO',
    'CURRENT_USER',
    'NONCLUSTERED',
    'TOP',
    'CURSOR',
    'NOT',
    'TRAN',
    'DATABASE',
    'NULL',
    'TRANSACTION',
    'DBCC',
    'NULLIF',
    'TRIGGER',
    'DEALLOCATE',
    'OF',
    'TRUNCATE',
    'TRUNCATE TABLE',
    'DECLARE',
    'OFF',
    'TRY_CONVERT',
    'DEFAULT',
    'OFFSETS',
    'TSEQUAL',
    'DELETE',
    'ON',
    'UNION',
    'DENY',
    'OPEN',
    'UNIQUE',
    'DESC',
    'OPENDATASOURCE',
    'UNPIVOT',
    'DISK',
    'OPENQUERY',
    'UPDATE',
    'DISTINCT',
    'OPENROWSET',
    'UPDATETEXT',
    'DISTRIBUTED',
    'OPENXML',
    'USE',
    'DOUBLE',
    'OPTION',
    'USER',
    'DROP',
    'DROP TABLE',
    'DROP DATABASE',
    'DROP FUNCTION',
    'DROP INDEX',
    'DROP PROCEDURE',
    'DROP VIEW',
    'DROP ROLE',
    'DROP USER',
    'OR',
    'VALUES',
    'DUMP',
    'VARYING',
    'ELSE',
    'OUTER',
    'VIEW',
    'END',
    'OVER',
    'WAITFOR',
    'ERRLVL',
    'PERCENT',
    'WHEN',
    'ESCAPE',
    'PIVOT',
    'WHERE',
    'EXCEPT',
    'PLAN',
    'WHILE',
    'EXEC',
    'PRECISION',
    'WITH',
    'EXECUTE',
    'PRIMARY',
    'WITHIN GROUP',
    'EXISTS',
    'PRINT',
    'WRITETEXT',
    'EXIT',
    'PROC',
    'UPDATE',
    'LEFT JOIN',
    'LEFT OUTER JOIN',
    'RIGHT JOIN',
    'RIGHT OUTER JOIN',
    'INNER JOIN',
    'OUTER JOIN',

    'tinyint',
    'smallint',
    'int',
    'bigint',
    'decimal',
    'numeric',
    'money',
    'smallmoney',
    'float',
    'real',
    'datetime',
    'smalldatetime',
    'date',
    'time',
    'datetime2',
    'datetimeoffset',
    'char',
    'varchar',
    'text',
    'nchar',
    'nvarchar',
    'binary',
    'varbinary',
    'image',
    'cursor',
    'timestamp',
    'hierarchyid',
    'geography',
    'geometry',
    'sysname',
    'variant',
    'rowversion',
    'xml',
  ],
  priority_functions: [],
  functions: [...Math_Functions, ...Date_Functions, ...String_Functions, ...JSON_Functions],
};

export default SQLServer;
