create sequence test_constraint_table_employee_id_seq
    as integer;

create sequence orders_order_id_seq
    as integer;

create sequence user_data_user_id_seq
    as integer;

create sequence my_sequence;

create type position_level as enum ('junior', 'mid-level', 'senior', 'manager');

create type "position_level2'" as enum ('junior', 'mid-level', 'senior', 'manager');

create type inventory_item as
(
    name        text,
    supplier_id integer,
    price       numeric
);

create table if not exists numeric_test
(
    id                        serial
        primary key,
    smallint_col              smallserial,
    int_col                   serial,
    bigint_col                bigserial,
    numeric_default_col       numeric,
    numeric_prec10_scale2_col numeric(10, 2),
    numeric_prec20_scale5_col numeric(20, 5),
    numeric_max_prec_col      numeric(1000),
    numeric_nan_col           numeric          default 47467.88 not null,
    column_10                 numeric(1, 1),
    column_11                 numeric(1),
    column_12                 numeric(1),
    column_13                 numeric(5, 2),
    column_14                 numeric(1000, 78),
    column_15                 numeric,
    column_16                 double precision default 67.88,
    column_17                 smallserial,
    column_18                 bigserial,
    column_19                 integer generated by default as identity,
    column_22                 money,
    column_23                 real             default 6,
    column_20                 integer generated by default as identity,
    column_21                 integer generated by default as identity,
    column_24                 integer generated by default as identity,
    column_25                 integer generated by default as identity,
    column_26                 smallserial
);

comment on table numeric_test is '数字测试表‘、@#￥！￥！%&！……#%&……%*%“@%@#%!$"''/-=·';

comment on column numeric_test.bigint_col is 'asfa''';

create unique index if not exists numeric_test_smallint_col_uindex
    on numeric_test (smallint_col);

create table if not exists text_types_test
(
    id               serial
        primary key,
    char_varying_col varchar(50),
    varchar_col      varchar(100),
    text_col         text,
    char_col         char(2) default 'b'::bpchar,
    char_no_col      char,
    var_col          varchar,
    var2_col         varchar(255),
    name_col         name,
    name_no_col      name,
    chara_col        char(2),
    chara_no_col     char,
    column_13        varchar(1)
);

comment on table text_types_test is '字符串类型测试表';

create table if not exists bytea_test
(
    id          serial
        primary key,
    binary_data bytea,
    text_data   text
);

comment on table bytea_test is '测试二进制类型';

create table if not exists datetime_test
(
    id                       serial
        primary key,
    date_col                 date    default '2024-06-15'::date,
    time_without_tz_col      time(3) default '20:24:00'::time without time zone,
    time_with_tz_col         time(3) with time zone,
    timestamp_without_tz_col timestamp(3),
    timestamp_with_tz_col    timestamp(3) with time zone,
    interval_col             interval,
    column_8                 time,
    column_9                 time(0),
    column_10                interval(4),
    column_11                interval(0)
);

comment on table datetime_test is '时间类型测试表';

create table if not exists boolean_tests
(
    id                  serial
        primary key,
    bool_column         boolean,
    bool_text_column    text,
    bool_numeric_column integer
);

comment on table boolean_tests is '测试布尔类型';

create table if not exists employee
(
    id         serial
        primary key,
    first_name varchar(50),
    last_name  varchar(50),
    position   "ddl_test'".position_level,
    hire_date  date
);

comment on table employee is '测试自定义类型';

create table if not exists employee2
(
    id         serial
        primary key,
    first_name varchar(50),
    last_name  varchar(50),
    position   "ddl_test'"."position_level2'",
    hire_date  date
);

create table if not exists geometric_shapes
(
    id            serial
        primary key,
    point_shape   point,
    line_shape    line,
    lseg_shape    lseg,
    box_shape     box,
    closed_path   path,
    open_path     path,
    polygon_shape polygon,
    circle_shape  circle
);

comment on table geometric_shapes is '空间类型测试';

create table if not exists network_addresses
(
    id                   serial
        primary key,
    ipv4_cidr            cidr,
    ipv6_cidr            cidr,
    ipv4_inet            inet,
    ipv6_inet            inet,
    mac_address          macaddr,
    extended_mac_address macaddr8
);

comment on table network_addresses is '网络类型测试';

create table if not exists bit_types
(
    id                           serial
        primary key,
    fixed_bit_column             bit(8),
    varying_bit_column           bit varying(16),
    unlimited_varying_bit_column bit varying,
    column_5                     bit,
    column_6                     bit,
    column_7                     bit varying(1)
);

comment on table bit_types is '测试位串类型';

create table if not exists text_search_type
(
    column_1 tsquery,
    column_2 tsvector
);

comment on table text_search_type is '文本搜索类型测试表';

create table if not exists xml_type
(
    column_1 xml
);

comment on table xml_type is 'xml类型测试表';

create table if not exists json_types
(
    column_1 json,
    column_2 jsonb,
    column_3 jsonpath
);

comment on table json_types is 'json类型测试';

create table if not exists array_type
(
    name           text,
    pay_by_quarter integer[],
    schedule       text[][],
    column_2       char[],
    column_3       integer[][],
    column_4       json[][],
    column_5       json[][],
    column_8       character varying[],
    column_9       bit[],
    column_10      bit varying[],
    column_11      smallint[],
    column_12      bigint[],
    column_13      jsonb[],
    column_14      jsonpath[],
    column_15      time without time zone[],
    column_16      timestamp without time zone[],
    column_17      time with time zone[],
    column_18      timestamp with time zone[],
    column_19      point[],
    column_20      path[],
    column_21      line[],
    column_22      lseg[],
    column_23      box[],
    column_24      polygon[],
    column_25      circle[],
    column_26      cidr[],
    column_27      inet[],
    column_28      macaddr[],
    column_29      macaddr8[],
    column_30      xml[],
    column_31      tsvector[],
    column_32      tsquery[]
);

comment on table array_type is '测试数组类型';

comment on column array_type.column_11 is 'klnl''';

create table if not exists cities_parent_table
(
    name       text,
    population double precision,
    altitude   integer
);

comment on table cities_parent_table is '测试父子表关系父表';

create table if not exists capitals_sub_table
(
    state    char(2),
    column_5 integer
)
    inherits (cities_parent_table);

comment on table capitals_sub_table is '测试表继承关系子表';

create table if not exists combination_type_table
(
    item  "ddl_test'".inventory_item,
    count integer
);

comment on table combination_type_table is '测试组合类型';

create table if not exists capitals_sub_table2
(
    state    char(2),
    column_5 integer
)
    inherits (cities_parent_table);

create table if not exists test_comment_table
(
    id            serial
        primary key,
    first_name    varchar(50) not null,
    last_name     varchar(50) not null,
    email         varchar(100)
        unique,
    hire_date     date        not null,
    department_id integer
);

comment on table test_comment_table is '注释测试表';

comment on column test_comment_table.id is '''员工的唯一标识符';

comment on column test_comment_table.first_name is '员工的名字';

comment on column test_comment_table.last_name is '员工的姓氏';

comment on column test_comment_table.email is '员工的工作电子邮件地址';

comment on column test_comment_table.hire_date is '员工入职公司的日期';

comment on column test_comment_table.department_id is '员工所属部门的ID';

create index if not exists idx_employees_email
    on test_comment_table (email);

comment on index idx_employees_email is '用于快速查找员工的电子邮件地址';

create table if not exists test_comment_table2
(
    id            serial
        primary key,
    first_name    varchar(50) not null,
    last_name     varchar(50) not null,
    email         varchar(100)
        unique,
    hire_date     date        not null,
    department_id integer
);

comment on table test_comment_table2 is '员工信息表，存储所有员工的详细信息''';

comment on column test_comment_table2.id is '''员工的唯一标识符';

comment on column test_comment_table2.first_name is '员工的名字';

comment on column test_comment_table2.last_name is '员工的姓氏';

comment on column test_comment_table2.email is '员工的工作电子邮件地址';

comment on column test_comment_table2.hire_date is '员工入职公司的日期';

comment on column test_comment_table2.department_id is '员工所属部门的ID';

create index if not exists idx_employees2_email
    on test_comment_table2 (email);

comment on index idx_employees2_email is '用于快速查找员工的电子邮件地址';

create table if not exists foreign_table
(
    department_id   serial
        primary key,
    department_name varchar(100) not null
        unique
);

create table if not exists test_constraint_index_table
(
    employee_id   integer default nextval('"ddl_test''".test_constraint_table_employee_id_seq'::regclass) not null
        constraint test_constraint_table_pkey
            primary key,
    first_name    varchar(50)                                                                             not null,
    last_name     varchar(50)                                                                             not null,
    email         varchar(100)
        constraint test_constraint_table_email_key
            unique,
    hire_date     date                                                                                    not null
        constraint test_constraint_table_hire_date_check
            check (hire_date <= CURRENT_DATE),
    age           integer
        constraint test_constraint_table_age_check
            check ((age >= 18) AND (age <= 65)),
    department_id integer
        constraint fk_department_id
            references foreign_table,
    level         integer                                                                                 not null,
    position      varchar(50)                                                                             not null,
    constraint unique_first_last_name
        unique (first_name, last_name)
);

comment on table test_constraint_index_table is '约束以及索引测试表';

comment on column test_constraint_index_table.employee_id is '员工ID';

comment on column test_constraint_index_table.first_name is '员工的名字';

comment on column test_constraint_index_table.last_name is '员工的姓氏';

comment on column test_constraint_index_table.email is '员工的电子邮件';

comment on column test_constraint_index_table.hire_date is '员工的入职日期';

comment on column test_constraint_index_table.age is '员工的年龄';

comment on column test_constraint_index_table.department_id is '部门ID';

comment on constraint fk_department_id on test_constraint_index_table is '员工所属部门的外键引用';

alter sequence test_constraint_table_employee_id_seq owned by test_constraint_index_table.employee_id;

create index if not exists idx_level_department_id
    on test_constraint_index_table (level asc, department_id desc);

comment on index idx_level_department_id is '根据级别和部门ID（降序）的复合索引，优化特定排序和查询';

create index if not exists idx_first_last_name
    on test_constraint_index_table (first_name, last_name);

comment on index idx_first_last_name is '基于名字和姓氏的复合唯一性索引，确保姓名组合的唯一性';

create index if not exists idx_position_department_id
    on test_constraint_index_table (position, department_id);

comment on index idx_position_department_id is '职位与部门ID的复合索引，用于加速涉及职位和部门的查询';

create table if not exists test_constraint_index_table2
(
    employee_id   serial
        constraint test_constraint_table2_pkey
            primary key,
    first_name    varchar(50) not null,
    last_name     varchar(50) not null,
    email         varchar(100)
        constraint test_constraint_table2_email_key
            unique,
    hire_date     date        not null
        constraint test_constraint_table_hire_date2_check
            check (hire_date <= CURRENT_DATE),
    age           integer
        constraint test_constraint_table_age2_check
            check ((age >= 18) AND (age <= 65)),
    department_id integer
        constraint fk_department2_id
            references foreign_table,
    level         integer     not null,
    position      varchar(50) not null,
    constraint unique_first_last2_name
        unique (first_name, last_name)
);

comment on column test_constraint_index_table2.employee_id is '员工ID';

comment on column test_constraint_index_table2.first_name is '员工的名字';

comment on column test_constraint_index_table2.last_name is '员工的姓氏';

comment on column test_constraint_index_table2.email is '员工的电子邮件';

comment on column test_constraint_index_table2.hire_date is '员工的入职日期';

comment on column test_constraint_index_table2.age is '员工的年龄';

comment on column test_constraint_index_table2.department_id is '部门ID';

create index if not exists idx_level_department2_id
    on test_constraint_index_table2 (level asc, department_id desc);

comment on index idx_level_department2_id is '根据级别和部门ID（降序）的复合索引，优化特定排序和查询';

create index if not exists idx_first_last_name2
    on test_constraint_index_table2 (first_name, last_name);

comment on index idx_first_last_name2 is '基于名字和姓氏的复合唯一性索引，确保姓名组合的唯一性';

create index if not exists idx_position_department2_id
    on test_constraint_index_table2 (position, department_id);

comment on index idx_position_department2_id is '职位与部门ID的复合索引，用于加速涉及职位和部门的查询';

create table if not exists foreign_parent_table
(
    id1  integer not null,
    id2  integer not null,
    data varchar(255),
    primary key (id1, id2)
);

comment on table foreign_parent_table is '测试复合主键以及复合外键约束';

create table if not exists foreign_sub_table
(
    sub_id     serial
        primary key,
    parent_id1 integer not null,
    parent_id2 integer not null,
    sub_data   varchar(255),
    foreign key (parent_id1, parent_id2) references foreign_parent_table
);

create table if not exists measurement
(
    city_id   integer not null,
    logdate   date    not null,
    peaktemp  integer,
    unitsales integer
)
    partition by RANGE (logdate);

comment on table measurement is '范围分区表主表';

create table if not exists measurement_y2006m02
    partition of measurement
        FOR VALUES FROM ('2006-02-01') TO ('2006-03-01');

create table if not exists measurement_y2006m03
    partition of measurement
        FOR VALUES FROM ('2006-03-01') TO ('2006-04-01');

create table if not exists measurement_y2007m11
    partition of measurement
        FOR VALUES FROM ('2007-11-01') TO ('2007-12-01');

create table if not exists measurement2
(
    city_id   integer not null,
    logdate   date    not null,
    peaktemp  integer,
    unitsales integer
)
    partition by RANGE (logdate);

comment on table measurement2 is '范围分区表主表';

create table if not exists measurement2_y2006m02
    partition of measurement2
        FOR VALUES FROM ('2006-02-01') TO ('2006-03-01');

create table if not exists measurement2_y2006m03
    partition of measurement2
        FOR VALUES FROM ('2006-03-01') TO ('2006-04-01');

create table if not exists measurement2_y2007m11
    partition of measurement2
        FOR VALUES FROM ('2007-11-01') TO ('2007-12-01');

create table if not exists measurement2_y2008m01
    partition of measurement2
        FOR VALUES FROM ('2008-01-01') TO ('2008-02-01')
    with (parallel_workers = 4);

create table if not exists measurement_y2008m01
    partition of measurement
        FOR VALUES FROM ('2008-01-01') TO ('2008-02-01')
    with (fillfactor = 70, autovacuum_enabled = true, autovacuum_vacuum_threshold = 50, autovacuum_vacuum_scale_factor = 0.2, autovacuum_analyze_threshold = 50, autovacuum_analyze_scale_factor = 0.1, autovacuum_vacuum_cost_delay = 20, autovacuum_vacuum_cost_limit = 200, autovacuum_freeze_min_age = 50000000, autovacuum_freeze_max_age = 150000000, autovacuum_multixact_freeze_min_age = 5000000, autovacuum_multixact_freeze_max_age = 15000000, parallel_workers = 4);

create table if not exists measurement_y2008m03
    partition of measurement
        FOR VALUES FROM ('2008-03-01') TO ('2008-04-01')
    with (fillfactor = 70, autovacuum_enabled = true, autovacuum_vacuum_threshold = 50, autovacuum_vacuum_scale_factor = 0.2, autovacuum_analyze_threshold = 50, autovacuum_analyze_scale_factor = 0.1, autovacuum_vacuum_cost_delay = 20, autovacuum_vacuum_cost_limit = 200, autovacuum_freeze_min_age = 50000000, autovacuum_freeze_max_age = 150000000, autovacuum_multixact_freeze_min_age = 5000000, autovacuum_multixact_freeze_max_age = 15000000, parallel_workers = 4);

create table if not exists measurement_y2008m06
    partition of measurement
        FOR VALUES FROM ('2008-07-01') TO ('2008-08-01')
    with (fillfactor = 70, autovacuum_enabled = true, autovacuum_vacuum_threshold = 50, autovacuum_vacuum_scale_factor = 0.2, autovacuum_analyze_threshold = 50, autovacuum_analyze_scale_factor = 0.1, autovacuum_vacuum_cost_delay = 20, autovacuum_vacuum_cost_limit = 200, autovacuum_freeze_min_age = 50000000, autovacuum_freeze_max_age = 150000000, autovacuum_multixact_freeze_min_age = 5000000, autovacuum_multixact_freeze_max_age = 15000000, parallel_workers = 4);

create table if not exists numeric_test2
(
    id                        serial
        constraint numeric2_test_pkey
            primary key,
    smallint_col              smallserial,
    int_col                   serial,
    bigint_col                bigserial,
    numeric_default_col       numeric,
    numeric_prec10_scale2_col numeric(10, 2),
    numeric_prec20_scale5_col numeric(20, 5),
    numeric_max_prec_col      numeric(1000),
    numeric_nan_col           numeric,
    column_10                 numeric(1, 1),
    column_11                 numeric(1),
    column_12                 numeric(1),
    column_13                 numeric(5, 2),
    column_14                 numeric(1000, 78),
    column_15                 numeric,
    column_16                 double precision,
    column_17                 smallserial,
    column_18                 bigserial,
    column_19                 integer generated by default as identity,
    column_22                 money,
    column_23                 real,
    column_20                 integer generated by default as identity,
    column_21                 integer generated by default as identity,
    column_24                 integer generated by default as identity,
    column_25                 integer generated by default as identity (start with 100 increment by 2)
);

create table if not exists numeric_test3
(
    id                        serial
        constraint numeric3_test_pkey
            primary key,
    smallint_col              smallserial,
    int_col                   serial,
    bigint_col                bigserial,
    numeric_default_col       numeric,
    numeric_prec10_scale2_col numeric(10, 2),
    numeric_prec20_scale5_col numeric(20, 5),
    numeric_max_prec_col      numeric(1000),
    numeric_nan_col           numeric,
    column_10                 numeric(1, 1),
    column_11                 numeric(1),
    column_12                 numeric(1),
    column_13                 numeric(5, 2),
    column_14                 numeric(1000, 78),
    column_15                 numeric,
    column_16                 double precision,
    column_17                 smallserial,
    column_18                 bigserial,
    column_19                 integer generated by default as identity,
    column_22                 money,
    column_23                 real,
    column_20                 integer generated by default as identity,
    column_21                 integer generated by default as identity,
    column_24                 integer generated by default as identity,
    column_25                 integer generated by default as identity (start with 100 increment by 2)
)
    inherits (cities_parent_table)
    with (autovacuum_enabled = true, autovacuum_vacuum_threshold = 50);

create table if not exists numeric_test4
(
    id                        serial
        primary key,
    smallint_col              smallserial,
    int_col                   serial,
    bigint_col                bigserial,
    numeric_default_col       numeric,
    numeric_prec10_scale2_col numeric(10, 2),
    numeric_prec20_scale5_col numeric(20, 5),
    numeric_max_prec_col      numeric(1000),
    numeric_nan_col           numeric,
    column_10                 numeric(1, 1),
    column_11                 numeric(1),
    column_12                 numeric(1),
    column_13                 numeric(5, 2),
    column_14                 numeric(1000, 78),
    column_15                 numeric,
    column_16                 double precision,
    column_17                 smallserial,
    column_18                 bigserial,
    column_19                 integer generated by default as identity,
    column_22                 money,
    column_23                 real,
    column_20                 integer generated by default as identity,
    column_21                 integer generated by default as identity,
    column_24                 integer generated by default as identity,
    column_25                 integer generated by default as identity (start with 100 increment by 2)
)
    inherits (cities_parent_table)
    with (autovacuum_enabled = true, autovacuum_vacuum_threshold = 50);

create table if not exists orders
(
    order_id     integer default nextval('"ddl_test''".orders_order_id_seq'::regclass) not null,
    customer_id  integer                                                               not null,
    order_status text                                                                  not null,
    column_4     integer,
    primary key (order_id, order_status)
)
    partition by LIST (order_status);

comment on table orders is '列表分区';

create table if not exists orders_pending
    partition of orders
        FOR VALUES IN ('pending');

create table if not exists orders_completed
    partition of orders
        FOR VALUES IN ('completed');

create table if not exists orders_cancelled
    partition of orders
        FOR VALUES IN ('cancelled');

create table if not exists user_data
(
    user_id   integer default nextval('"ddl_test''".user_data_user_id_seq'::regclass) not null
        primary key,
    user_name text                                                                    not null
)
    partition by HASH (user_id);

comment on table user_data is '哈希分区';

create table if not exists user_data_p0
    partition of user_data
        FOR VALUES WITH (modulus 4, remainder 0);

create table if not exists user_data_p1
    partition of user_data
        FOR VALUES WITH (modulus 4, remainder 1);

create table if not exists user_data_p2
    partition of user_data
        FOR VALUES WITH (modulus 4, remainder 2);

create table if not exists user_data_p3
    partition of user_data
        FOR VALUES WITH (modulus 4, remainder 3);

create table if not exists empty
(
);

comment on table empty is '空表';

create table if not exists empty2
(
);

create table if not exists test_int_table
(
    column_1 smallint,
    column_2 integer,
    column_3 bigint,
    column_4 smallserial,
    column_5 serial,
    column_6 bigserial
);

create table if not exists my_table
(
    id       integer default nextval('"ddl_test''".my_sequence'::regclass) not null
        primary key,
    column1  varchar(255),
    column2  integer,
    column_3 serial
);

create table if not exists v_coldef
(
    data_type text
);

create table if not exists measurement_y2008m010
    partition of measurement
        FOR VALUES FROM ('2008-10-01') TO ('2008-11-01')
    with (fillfactor = 70, autovacuum_enabled = true, autovacuum_vacuum_threshold = 50, autovacuum_vacuum_scale_factor = 0.2, autovacuum_analyze_threshold = 50, autovacuum_analyze_scale_factor = 0.1, autovacuum_vacuum_cost_delay = 20, autovacuum_vacuum_cost_limit = 200, autovacuum_freeze_min_age = 50000000, autovacuum_freeze_max_age = 150000000, autovacuum_multixact_freeze_min_age = 5000000, autovacuum_multixact_freeze_max_age = 15000000, parallel_workers = 4);

create table if not exists original_table
(
    id         serial
        primary key,
    name       varchar(100) not null,
    created_at timestamp default CURRENT_TIMESTAMP
);

create table if not exists new_table
(
    id         integer   default nextval('"ddl_test''".original_table_id_seq'::regclass) not null
        primary key,
    name       varchar(100)                                                              not null,
    created_at timestamp default CURRENT_TIMESTAMP
);


